package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

import juranometria.app.AboutDialog;
import juranometria.app.AppInfo;
import juranometria.ui.language.AboutText;
import juranometria.ui.language.InterfaceText;

/**
 * Every word About says, in both languages (Sprint 33, issue #350).
 *
 * <p>The <strong>real packed dialog</strong>, opened the way a reader
 * opens it and pressed through to the bundled documents with its own
 * button. Both views, both languages, both themes: eight captures,
 * and the generator refuses to write a companion from fewer.
 *
 * <p>It installs its own look and feel before any component exists
 * (#362).
 *
 * <p><strong>The companion does not copy the bundled documents.</strong>
 * They are 25 235 characters of somebody else's licence text; a study
 * that pasted them in would be a fourth copy to drift, and the
 * exact-composition contract in {@code AboutTextTest} already holds
 * them character for character. They are listed by path and length
 * instead, which is what a reader of the companion needs to check.
 */
public final class AboutSheetMain {

    private AboutSheetMain() {
    }

    private static final Path OUT =
            Path.of("docs/studies/interface-language");

    /** What was reached, so a partial run cannot be reported. */
    private static final Set<String> reached = new LinkedHashSet<>();

    public static void main(String[] args) throws Exception {
        if (java.awt.GraphicsEnvironment.isHeadless()) {
            System.err.println("About is a window, and a panel drawn"
                    + " without one is not the dialog");
            System.exit(1);
        }
        Files.createDirectories(OUT);
        StringBuilder said = new StringBuilder();
        said.append("""
                # Every word About says

                Issue #350. Generated by
                `juranometria.tool.AboutSheetMain` from compiled
                application classes and their classpath resources.
                Packaged acceptance separately verifies that the
                interface language resources ship in the application
                image.

                %s

                ## Three kinds of words, kept apart

                | kind | what happens to it |
                |---|---|
                | application prose | translated: twelve values and seven headings |
                | identity and fact | exact in every language: the name, the version, the source and project names, every licence identifier |
                | bundled legal documents | **never translated, never reflowed**: 25 235 characters of upstream text, passed through untouched |

                The compact summary sits between the first two: it is
                JUranometria's own account of its legal position, so it
                is translated - as a **whole document**, held to the
                same licensing map as the English one, never mixed
                with it paragraph by paragraph.

                """.formatted(juranometria.tool.InterfaceLanguageStatus
                        .statement("nb-NO")));

        int sheet = 1;
        for (String language : List.of("en", "nb-NO")) {
            InterfaceText words = InterfaceText.forLanguage(language);
            AboutText about = AboutText.in(words);
            said.append("## ").append(language.equals("en") ? "English"
                            : "Norsk bokmål").append(" (`")
                    .append(language).append("`)\n\n")
                    .append(prose(about)).append(headings(about));
            for (String theme : List.of("light", "dark")) {
                boolean dark = theme.equals("dark");
                said.append("### ").append(dark ? "Dark" : "Light")
                        .append("\n\n")
                        .append(draw(language, words, dark, false,
                                OUT.resolve("about-" + language + "-"
                                        + (sheet++) + "-compact-"
                                        + theme + ".png")))
                        .append(draw(language, words, dark, true,
                                OUT.resolve("about-" + language + "-"
                                        + (sheet++) + "-notices-"
                                        + theme + ".png")))
                        .append('\n');
            }
            said.append(summary(language, about));
        }
        said.append(documents()).append(decorative());

        require("compact/en/light", "compact/en/dark",
                "compact/nb-NO/light", "compact/nb-NO/dark",
                "notices/en/light", "notices/en/dark",
                "notices/nb-NO/light", "notices/nb-NO/dark",
                "summary/en", "summary/nb-NO");
        for (AboutDialog.Notice notice : AboutDialog.NOTICES) {
            require("heading/" + notice.id(), "body/" + notice.id());
        }
        Files.writeString(OUT.resolve("about-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("about sheets: 8 images and "
                + OUT.resolve("about-strings.md"));
    }

    /** The twelve translated values. */
    private static String prose(AboutText said) {
        StringBuilder out = new StringBuilder(
                "### Application prose\n\n| channel | words |\n|---|---|\n");
        row(out, "window title", said.title(AppInfo.NAME));
        row(out, "window, spoken", said.windowExplain());
        row(out, "heading", said.heading(AppInfo.NAME, AppInfo.version()));
        row(out, "description", said.description());
        row(out, "summary, spoken name", said.summaryName());
        row(out, "summary, explanation", said.summaryExplain());
        row(out, "notices button", said.noticesButton());
        row(out, "notices button, spoken", said.noticesButtonName());
        row(out, "notices button, explanation",
                said.noticesButtonExplain());
        row(out, "notices view, spoken name", said.noticesName());
        row(out, "notices view, explanation", said.noticesExplain());
        row(out, "close", said.closeButton());
        row(out, "close, explanation", said.closeExplain());
        return out.append('\n').toString();
    }

    /** The seven headings the atlas puts over other people's text. */
    private static String headings(AboutText said) {
        StringBuilder out = new StringBuilder(
                "### Section headings\n\n| document | heading |\n|---|---|\n");
        for (AboutDialog.Notice notice : AboutDialog.NOTICES) {
            row(out, "`" + notice.id() + "`", said.heading(notice));
            reached.add("heading/" + notice.id());
        }
        return out.append('\n').toString();
    }

    /** The compact summary, whole, because it is one statement. */
    private static String summary(String language, AboutText said) {
        String text = said.summary();
        reached.add("summary/" + language);
        return "### The compact licensing summary, in full\n\n"
                + "Its own document (" + text.length()
                + " characters), " + (said.hasOwnSummary()
                        ? "written in this language"
                        : "the canonical English one, used whole"
                                + " because this language has not"
                                + " written its own")
                + ". Every licence identifier below is exact and"
                + " untranslated.\n\n```\n" + text + "```\n\n";
    }

    /** What is shown and never touched, by path and length. */
    private static String documents() {
        StringBuilder out = new StringBuilder(
                "## The bundled documents\n\nNot reproduced here: they"
                + " are upstream text, and a copy in a study is a copy"
                + " that can drift. `AboutTextTest` rebuilds the whole"
                + " notices view from these and compares it entire, so"
                + " a document trimmed or reflowed on its way to a"
                + " reader fails there.\n\n"
                + "| document | path | characters |\n|---|---|---|\n");
        int total = 0;
        for (AboutDialog.Notice notice : AboutDialog.NOTICES) {
            String body = AboutText.noticesBody(notice);
            total += body.length();
            out.append("| `").append(notice.id()).append("` | `")
                    .append(notice.resourcePath()).append("` | ")
                    .append(body.length()).append(" |\n");
            reached.add("body/" + notice.id());
        }
        return out.append("| **seven** | | **").append(total)
                .append("** |\n\n").toString();
    }

    /** Silent on purpose, and said so. */
    private static String decorative() {
        return """
                ## The application mark

                The mark beside the name is **decorative and
                deliberately silent**: no text, no accessible name, no
                accessible description. A screen reader is told the
                application's name, in words, immediately beside it,
                and gains nothing from the position of three stars.

                It is recorded here because a channel that is empty by
                decision and a channel that was missed look identical
                in a report that omits both.
                """;
    }

    /** Draws one view in one language and theme. */
    private static String draw(String language, InterfaceText words,
                               boolean dark, boolean notices, Path to)
            throws Exception {
        JFrame[] owner = new JFrame[1];
        JDialog[] about = new JDialog[1];
        try {
            SwingUtilities.invokeAndWait(() -> {
                juranometria.app.UiTheme.apply(dark);
                owner[0] = new JFrame("study");
                owner[0].setSize(900, 700);
                owner[0].setVisible(true);
                AboutDialog.open(owner[0], words);
            });
            SwingUtilities.invokeAndWait(() -> { });
            SwingUtilities.invokeAndWait(() -> {
                about[0] = dialogOf(owner[0]);
                if (about[0] == null) {
                    throw new IllegalStateException("About did not open");
                }
                if (notices) {
                    JButton button = buttonNamed(
                            about[0].getContentPane(),
                            AboutText.in(words).noticesButton());
                    if (button == null) {
                        throw new IllegalStateException("the compact"
                                + " view offers no notices button");
                    }
                    button.doClick();
                }
            });
            SwingUtilities.invokeAndWait(() -> { });
            reached.add((notices ? "notices/" : "compact/") + language
                    + "/" + (dark ? "dark" : "light"));
            return capture(about[0], language, notices, to);
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (about[0] != null) {
                    about[0].dispose();
                }
                if (owner[0] != null) {
                    owner[0].dispose();
                }
            });
        }
    }

    private static String capture(JDialog dialog, String language,
                                  boolean notices, Path to)
            throws Exception {
        Set<String> shown = new LinkedHashSet<>();
        BufferedImage[] image = new BufferedImage[1];
        String[] window = new String[2];
        SwingUtilities.invokeAndWait(() -> {
            Container content = dialog.getContentPane();
            window[0] = dialog.getTitle();
            window[1] = dialog.getAccessibleContext()
                    .getAccessibleDescription();
            BufferedImage drawn = new BufferedImage(
                    Math.max(1, content.getWidth()),
                    Math.max(1, content.getHeight()),
                    BufferedImage.TYPE_INT_RGB);
            Graphics2D g = drawn.createGraphics();
            try {
                g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                        RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g.setColor(content.getBackground() == null
                        ? Color.WHITE : content.getBackground());
                g.fillRect(0, 0, drawn.getWidth(), drawn.getHeight());
                content.paint(g);
            } finally {
                g.dispose();
            }
            image[0] = drawn;
            collect(content, shown);
        });
        ImageIO.write(image[0], "png", to.toFile());

        StringBuilder out = new StringBuilder();
        out.append("#### ").append(notices
                        ? "Full notices and licences" : "Compact")
                .append("\n\n![](").append(to.getFileName())
                .append(")\n\n").append(image[0].getWidth())
                .append(" × ").append(image[0].getHeight())
                .append(" px, `").append(language).append("`");
        if (notices) {
            out.append(" — the **viewport**: the stream behind it is"
                    + " 25 235 characters and is accounted for by the"
                    + " table below and by the exact-composition"
                    + " contract, not by this picture");
        }
        out.append(".\n\n| channel | words |\n|---|---|\n");
        row(out, "window title", window[0]);
        row(out, "window, spoken", window[1]);
        for (String one : shown) {
            row(out, "shown", one);
        }
        return out.append('\n').toString();
    }

    /**
     * What the view shows, with the long documents summarised.
     *
     * <p>A companion row is for reading. The compact summary is
     * printed whole in its own section and the notices stream is
     * accounted for by path and length, so neither is pasted into a
     * table cell here.
     */
    private static void collect(Container from, Set<String> shown) {
        for (Component child : from.getComponents()) {
            if (child instanceof JComponent widget) {
                if (widget instanceof AbstractButton button) {
                    add(shown, button.getText());
                }
                if (widget instanceof JLabel label) {
                    if (label.getIcon() != null
                            && (label.getText() == null
                                    || label.getText().isBlank())) {
                        shown.add("*(the application mark: decorative,"
                                + " no text, no spoken name)*");
                    } else {
                        add(shown, label.getText());
                    }
                }
                if (widget instanceof JTextArea area) {
                    shown.add("*(read-only document, "
                            + area.getText().length()
                            + " characters — printed in full below or"
                            + " listed by path)*");
                }
            }
            if (child instanceof Container nested) {
                collect(nested, shown);
            }
        }
    }

    private static JDialog dialogOf(JFrame owner) {
        for (Window window : owner.getOwnedWindows()) {
            if (window instanceof JDialog dialog && dialog.isShowing()) {
                return dialog;
            }
        }
        return null;
    }

    private static JButton buttonNamed(Container from, String text) {
        for (Component child : from.getComponents()) {
            if (child instanceof JButton button
                    && text.equals(button.getText())) {
                return button;
            }
            if (child instanceof Container nested) {
                JButton found = buttonNamed(nested, text);
                if (found != null) {
                    return found;
                }
            }
        }
        return null;
    }

    /** A companion is written from a complete run or not at all. */
    private static void require(String... needed) {
        List<String> missing = new ArrayList<>();
        for (String one : needed) {
            if (!reached.contains(one)) {
                missing.add(one);
            }
        }
        if (!missing.isEmpty()) {
            throw new IllegalStateException("this run did not reach "
                    + missing + ". A companion written from a partial"
                    + " run reports a smaller thing under the name of"
                    + " the whole.");
        }
    }

    private static void row(StringBuilder out, String what,
                            String words) {
        out.append("| ").append(what).append(" | ")
                .append(words == null ? "—"
                        : words.replace("|", "\\|")
                                .replaceAll("\\s+", " ").trim())
                .append(" |\n");
    }

    private static void add(Set<String> said, String text) {
        if (text != null && !text.isBlank()) {
            said.add(text.replaceAll("\\s+", " ").trim());
        }
    }
}
