package juranometria.tool;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.function.Function;

import javax.imageio.ImageIO;

import juranometria.app.Atlas;
import juranometria.chart.ChartScene;
import juranometria.chart.ChartViewState;
import juranometria.chart.SkyPosition;
import juranometria.chart.StarSizePolicy;
import juranometria.render.ChartOptions;
import juranometria.render.ChartPalette;
import juranometria.render.ChartRenderer;

/**
 * The black-sky design study (Sprint 26, issue #246): the second
 * intentional chart palette, derived from measurement rather than
 * inverted mechanically.
 *
 * <p>Prints the measurements to stdout (the Makefile writes them to
 * the committed study document) and renders the representative pages
 * beside them, through the production renderer, in both palettes.
 * The derivation rule is executed here against the white-paper
 * palette and compared with what {@link ChartPalette#BLACK_SKY}
 * pins - the verify-icons pattern: is what we ship still what the
 * rule derives? A mismatch fails the run.
 *
 * <p>Fails loudly on any pixel breach: a bulk colour outside the
 * reviewed palette, a non-grey pixel, an invisible galaxy fill, or
 * furniture whose interior is not the ground.
 */
public final class BlackSkyStudyMain {

    private BlackSkyStudyMain() {
    }

    /** One ink purpose, read from both palettes by the same door. */
    private record Role(String name, Function<ChartPalette, Color> ink) {
    }

    private static final List<Role> ROLES = List.of(
            new Role("star discs", ChartPalette::starInk),
            new Role("label/furniture text", ChartPalette::textInk),
            new Role("frame", ChartPalette::frameInk),
            new Role("deep-sky outlines", ChartPalette::deepSkyOutline),
            new Role("constellation figures", ChartPalette::figureInk),
            new Role("constellation names",
                    ChartPalette::constellationNameInk),
            new Role("nebula boxes", ChartPalette::nebulaOutline),
            new Role("selection ring", ChartPalette::selectionInk),
            new Role("grid notation", ChartPalette::gridLabelInk),
            new Role("boundaries", ChartPalette::boundaryInk),
            new Role("equatorial grid", ChartPalette::gridInk),
            new Role("galaxy fill", ChartPalette::galaxyFill),
            new Role("interaction crosses",
                    ChartPalette::interactionInk));

    private record Page(String name, String why, double ra, double dec,
                        double field, boolean key) {
    }

    private static final List<Page> PAGES = List.of(
            new Page("m31-08", "the released reference page: the"
                    + " largest pale fill, labels, grid",
                    10.684708, 41.268750, 8.0, false),
            new Page("orion-36", "wide and dense: figures, names,"
                    + " boundaries, every symbol family",
                    83.818667, 0.0, 36.0, false),
            new Page("polar-36", "polar: converging meridians, name"
                    + " and label crowding",
                    37.946619, 89.9, 36.0, false),
            new Page("seam-24", "the 0h right-ascension seam",
                    0.3, 45.0, 24.0, false),
            new Page("m42-01", "narrow: one nebula box near its"
                    + " contrast floor", 83.818667, -5.389667, 1.0,
                    false),
            new Page("sparse-08", "sparse: mostly ground, the frame"
                    + " and grid alone must carry the page",
                    218.0, 32.0, 8.0, false),
            new Page("m31-08-key", "the reference page with the"
                    + " stellar-magnitude key: furniture interiors on"
                    + " the dark ground", 10.684708, 41.268750, 8.0,
                    true));

    public static void main(String[] args) throws Exception {
        File outDir = new File("docs/studies/black-sky");
        outDir.mkdirs();
        ChartRenderer renderer = new ChartRenderer(StarSizePolicy.DEFAULT);

        System.out.println("# Black sky: the second intentional chart"
                + " palette");
        System.out.println();
        System.out.println("Generated by `make black-sky-study`"
                + " (juranometria.tool.BlackSkyStudyMain), which"
                + " renders the representative pages beside this"
                + " document through the production renderer in both"
                + " palettes, executes the derivation rule against"
                + " the white-paper palette, and fails the run if"
                + " `ChartPalette.BLACK_SKY` is not what the rule"
                + " derives or any pixel breaches its contract. Pixel"
                + " counts are per machine, like the furniture"
                + " study's.");
        System.out.println();

        derivation();
        hierarchy();
        pages(renderer, outDir);
        constancies();
    }

    // ---- the rule, executed --------------------------------------

    /**
     * WCAG relative luminance of an sRGB grey, the standard
     * linearization.
     */
    static double luminance(int grey) {
        double c = grey / 255.0;
        return c <= 0.04045 ? c / 12.92
                : Math.pow((c + 0.055) / 1.055, 2.4);
    }

    /** WCAG contrast ratio between an ink and its ground. */
    static double contrast(int ink, int ground) {
        double lighter = Math.max(luminance(ink), luminance(ground));
        double darker = Math.min(luminance(ink), luminance(ground));
        return (lighter + 0.05) / (darker + 0.05);
    }

    /**
     * The equal-contrast partner of a white-paper ink: the sRGB grey
     * whose contrast against black is what the ink's was against
     * white, chosen as the value whose luminance is nearest the
     * exact solution. Monotone, so the prominence order survives the
     * crossing by construction.
     */
    static int equalContrastOnBlack(int whitePaperGrey) {
        double target = 0.0525 / (luminance(whitePaperGrey) + 0.05)
                - 0.05;
        int best = 0;
        double error = Double.MAX_VALUE;
        for (int grey = 0; grey <= 255; grey++) {
            double e = Math.abs(luminance(grey) - target);
            if (e < error) {
                error = e;
                best = grey;
            }
        }
        return best;
    }

    private static void derivation() {
        System.out.println("## The rule: equal contrast, not"
                + " inversion");
        System.out.println();
        System.out.println("Every ink keeps the WCAG contrast ratio"
                + " against its ground that it earned on white paper:"
                + " for a paper ink of relative luminance *l*, the"
                + " black-sky partner is the grey nearest luminance"
                + " `0.0525 / (l + 0.05) - 0.05`. Because sRGB"
                + " luminance is non-linear, this is visibly not a"
                + " channel mirror - the mid-greys land dimmer than"
                + " `255 - v` would put them, which is exactly the"
                + " restrained light ink the issue asks for, falling"
                + " out of the rule rather than being tuned by hand."
                + " The mapping is monotone, so which ink is more"
                + " prominent than which is preserved without a"
                + " separate rule.");
        System.out.println();
        System.out.println("| ink | paper | ratio | derived | pinned"
                + " | ratio on black | channel mirror |");
        System.out.println("|---|---|---|---|---|---|---|");
        List<String> breaches = new ArrayList<>();
        for (Role role : ROLES) {
            int paper = role.ink().apply(ChartPalette.WHITE_PAPER)
                    .getRed();
            int pinned = role.ink().apply(ChartPalette.BLACK_SKY)
                    .getRed();
            int derived = equalContrastOnBlack(paper);
            System.out.printf(Locale.ROOT,
                    "| %s | %d | %.2f:1 | %d | %d | %.2f:1 | %d |%n",
                    role.name(), paper, contrast(paper, 255), derived,
                    pinned, contrast(pinned, 0), 255 - paper);
            if (derived != pinned) {
                breaches.add(role.name() + ": pinned " + pinned
                        + " but the rule derives " + derived);
            }
        }
        System.out.println();
        if (!breaches.isEmpty()) {
            breaches.forEach(b ->
                    System.out.println("PALETTE BREACH: " + b));
            throw new IllegalStateException(
                    "the pinned black-sky palette is not what the"
                            + " derivation rule produces: " + breaches);
        }
        System.out.println("The pinned `ChartPalette.BLACK_SKY` is"
                + " exactly what the rule derives, verified by this"
                + " run. Both grounds themselves are exact: paper"
                + " white 255, sky black 0.");
        System.out.println();
        System.out.println("The two values nearest their readability"
                + " thresholds:");
        System.out.println();
        int nebula = ChartPalette.BLACK_SKY.nebulaOutline().getRed();
        System.out.printf(Locale.ROOT, "- the nebula box, %d, scores"
                        + " %.2f:1 against the black ground - clear"
                        + " of the 3:1 floor the deep-sky vocabulary"
                        + " decision set, mirroring its 3.74:1 on"
                        + " paper;%n", nebula, contrast(nebula, 0));
        int fill = ChartPalette.BLACK_SKY.galaxyFill().getRed();
        System.out.printf(Locale.ROOT, "- the galaxy fill, %d, scores"
                + " %.2f:1 - the same deliberate whisper as its"
                + " 1.23:1 wash on paper, and its presence on a real"
                + " page is asserted below rather than assumed.%n",
                fill, contrast(fill, 0));
        if (contrast(nebula, 0) < 3.0) {
            throw new IllegalStateException("the nebula box has sunk"
                    + " under its 3:1 floor on black: "
                    + contrast(nebula, 0));
        }
        System.out.println();
    }

    private static void hierarchy() {
        System.out.println("## The hierarchy, preserved");
        System.out.println();
        System.out.println("Ink purposes ordered by contrast against"
                + " their ground - identical on both grounds, star"
                + " discs to galaxy fill:");
        System.out.println();
        List<Role> paperOrder = new ArrayList<>(ROLES);
        paperOrder.sort((a, b) -> Double.compare(
                contrast(b.ink().apply(ChartPalette.WHITE_PAPER)
                        .getRed(), 255),
                contrast(a.ink().apply(ChartPalette.WHITE_PAPER)
                        .getRed(), 255)));
        List<Role> blackOrder = new ArrayList<>(ROLES);
        blackOrder.sort((a, b) -> Double.compare(
                contrast(b.ink().apply(ChartPalette.BLACK_SKY)
                        .getRed(), 0),
                contrast(a.ink().apply(ChartPalette.BLACK_SKY)
                        .getRed(), 0)));
        for (int i = 0; i < paperOrder.size(); i++) {
            System.out.printf("%d. %s%n", i + 1,
                    paperOrder.get(i).name());
            if (!paperOrder.get(i).name()
                    .equals(blackOrder.get(i).name())) {
                throw new IllegalStateException("the prominence order"
                        + " differs between grounds at position "
                        + (i + 1) + ": " + paperOrder.get(i).name()
                        + " vs " + blackOrder.get(i).name());
            }
        }
        System.out.println();
    }

    // ---- the pages, rendered and accounted -----------------------

    private static void pages(ChartRenderer renderer, File outDir)
            throws Exception {
        System.out.println("## The pages, and every pixel accounted");
        System.out.println();
        System.out.println("Each page is rendered in both palettes"
                + " (900x700; committed beside this document as"
                + " `<page>-paper.png` and `<page>-black.png`). For"
                + " the black render, three contracts, asserted:"
                + " every pixel is grey; every colour covering at"
                + " least 0.5% of the page is a reviewed palette"
                + " value (an accidental white island or a furniture"
                + " block on the wrong ground is thousands of"
                + " pixels; the antialiased rim of a long feature is"
                + " a legitimate concentration of a single"
                + " intermediate grey - the first run caught 531"
                + " pixels of grey 1 along M31's ellipse rim, honest"
                + " compositing a naive floor misread); and every"
                + " remaining colour is counted as antialiasing, not"
                + " waved through. Then the two renders are compared"
                + " structurally, pixel for pixel, each classified"
                + " ground / exact ink / antialiased: compositing"
                + " against the wrong ground would put antialiasing"
                + " where the paper render has none, so the"
                + " classification agreement is the halo check made"
                + " executable. \"Mask\" is the set of non-ground"
                + " pixels; its residual disagreement is rounding at"
                + " edges where coverage is marginal against one"
                + " ground but not the other.");
        System.out.println();
        System.out.println("| page | why | palette px | AA px |"
                + " AA greys | class agreement | mask agreement |"
                + " mask differs |");
        System.out.println("|---|---|---|---|---|---|---|---|");

        for (Page page : PAGES) {
            ChartViewState state = new ChartViewState(
                    new SkyPosition(page.ra(), page.dec()),
                    page.field(), 8.0, null, null);
            ChartScene scene = Atlas.assembler().assemble(
                    state, 900, 700);
            ChartOptions base = page.key()
                    ? new ChartOptions(true, true, true, true, true,
                            true, true, true, true, true, true, true,
                            true, true, true, true)
                    : ChartOptions.DEFAULTS;
            BufferedImage paper = renderer.renderToImage(scene, base);
            BufferedImage black = renderer.renderToImage(scene,
                    base.withPalette(ChartPalette.BLACK_SKY));
            ImageIO.write(paper, "png",
                    new File(outDir, page.name() + "-paper.png"));
            ImageIO.write(black, "png",
                    new File(outDir, page.name() + "-black.png"));

            accounted(page, paper, black);
        }
        System.out.println();
        System.out.println("No page carries a bulk colour outside"
                + " the reviewed palette and no pixel on any page is"
                + " other than grey - both asserted, the run fails"
                + " on a breach. The classification agreement is the"
                + " wrong-ground check: a halo would be antialiasing"
                + " on the black render where the paper render has"
                + " ground or exact ink, and the residual"
                + " disagreement above is confined to edge rounding,"
                + " the same order as the mask residual.");
        System.out.println();
    }

    /** ground / exact palette ink / antialiased blend. */
    private static int classify(int rgb, int ground,
                                java.util.Set<Integer> palette) {
        if (rgb == ground) {
            return 0;
        }
        return palette.contains(rgb) ? 1 : 2;
    }

    private static java.util.Set<Integer> inksOf(ChartPalette which) {
        java.util.Set<Integer> palette = new java.util.HashSet<>();
        for (Role role : ROLES) {
            palette.add(role.ink().apply(which).getRGB());
        }
        return palette;
    }

    private static void accounted(Page page, BufferedImage paper,
                                  BufferedImage black) {
        java.util.Set<Integer> palette = inksOf(ChartPalette.BLACK_SKY);
        int ground = ChartPalette.BLACK_SKY.ground().getRGB();
        palette.add(ground);

        Map<Integer, Integer> census = new TreeMap<>();
        int total = black.getWidth() * black.getHeight();
        for (int y = 0; y < black.getHeight(); y++) {
            for (int x = 0; x < black.getWidth(); x++) {
                int rgb = black.getRGB(x, y);
                int r = (rgb >> 16) & 0xff;
                int g = (rgb >> 8) & 0xff;
                int b = rgb & 0xff;
                if (r != g || g != b) {
                    throw new IllegalStateException(page.name()
                            + ": non-grey pixel at " + x + "," + y
                            + ": " + Integer.toHexString(rgb));
                }
                census.merge(rgb, 1, Integer::sum);
            }
        }
        int bulkFloor = (int) Math.ceil(total * 0.005);
        long palettePixels = 0;
        int aaPixels = 0;
        int aaGreys = 0;
        for (Map.Entry<Integer, Integer> colour : census.entrySet()) {
            if (palette.contains(colour.getKey())) {
                palettePixels += colour.getValue();
            } else if (colour.getValue() >= bulkFloor) {
                throw new IllegalStateException(page.name()
                        + ": bulk colour outside the reviewed palette:"
                        + " grey " + (colour.getKey() & 0xff) + " on "
                        + colour.getValue() + " pixels");
            } else {
                aaPixels += colour.getValue();
                aaGreys++;
            }
        }

        java.util.Set<Integer> paperPalette =
                inksOf(ChartPalette.WHITE_PAPER);
        int paperGround = ChartPalette.WHITE_PAPER.ground().getRGB();
        paperPalette.add(paperGround);
        long classAgree = 0;
        long maskAgree = 0;
        int maskDiffer = 0;
        for (int y = 0; y < black.getHeight(); y++) {
            for (int x = 0; x < black.getWidth(); x++) {
                int onPaper = classify(paper.getRGB(x, y),
                        paperGround, paperPalette);
                int onBlack = classify(black.getRGB(x, y), ground,
                        palette);
                if (onPaper == onBlack) {
                    classAgree++;
                }
                if ((onPaper == 0) == (onBlack == 0)) {
                    maskAgree++;
                } else {
                    maskDiffer++;
                }
            }
        }
        System.out.printf(Locale.ROOT,
                "| %s | %s | %.2f%% | %d (%.3f%%) | %d | %.3f%% |"
                        + " %.3f%% | %d |%n",
                page.name(), page.why(),
                100.0 * palettePixels / total, aaPixels,
                100.0 * aaPixels / total, aaGreys,
                100.0 * classAgree / total, 100.0 * maskAgree / total,
                maskDiffer);

        if (page.name().equals("m31-08")) {
            int fill = ChartPalette.BLACK_SKY.galaxyFill().getRGB();
            int fillPixels = census.getOrDefault(fill, 0);
            if (fillPixels == 0) {
                throw new IllegalStateException("the galaxy fill is"
                        + " invisible on the black reference page -"
                        + " the whisper has gone silent");
            }
            System.out.printf(Locale.ROOT,
                    "%n`m31-08-black`: the galaxy fill is present"
                            + " and itself - %d pixels of exact grey"
                            + " %d inside M31's ellipse.%n%n",
                    fillPixels, fill & 0xff);
        }
        if (page.key()) {
            furniture(page, black, ground);
        }
    }

    /**
     * Furniture interiors are the ground, not white islands: one
     * probe just inside each block's border, in the padding no text
     * reaches.
     */
    private static void furniture(Page page, BufferedImage black,
                                  int ground) {
        int corner = black.getRGB(3, 3);
        // The title block sits at the lower left with a 12 px margin
        // and 8 px padding; 3 px inside its border is padding.
        int titleProbe = black.getRGB(12 + 3,
                black.getHeight() - 12 - 3);
        if (titleProbe != ground) {
            throw new IllegalStateException(page.name() + ": the"
                    + " title block's interior is not the ground:"
                    + " grey " + (titleProbe & 0xff));
        }
        System.out.printf(Locale.ROOT, "`%s-black`: furniture"
                + " interiors are the ground (title-block padding"
                + " probe grey %d, page corner grey %d) - opaque"
                + " blocks, no white islands.%n%n",
                page.name(), titleProbe & 0xff, corner & 0xff);
    }

    // ---- what stays constant -------------------------------------

    private static void constancies() {
        System.out.println("## What stays constant, and where it is"
                + " proven");
        System.out.println();
        System.out.println("- **The white-paper chart is"
                + " byte-identical.** `ChartOptions.DEFAULTS` carries"
                + " white paper, every released reference comparison"
                + " and ink-count test runs through it unchanged, and"
                + " the palette reaches rendering only through the"
                + " options value.");
        System.out.println("- **The application theme never reaches"
                + " chart ink.** The palette lives in"
                + " `ChartPalette`, consulted only by the chart's"
                + " own painters; the renderer reads nothing from"
                + " `UIManager`, and the both-themes byte-identity"
                + " tests now run the black page too.");
        System.out.println("- **Enlarged application text does not"
                + " reach the page.** Chart label faces are the"
                + " renderer's own fixed fonts, not the"
                + " application's `defaultFont`; the dialog and its"
                + " Black sky control follow application text size"
                + " like every other control.");
        System.out.println("- **Switching is repaint-only.** The"
                + " palette is a `ChartOptions` component, invisible"
                + " to scene assembly by construction; the scene,"
                + " inventory, catalogue-query count, centre, field,"
                + " limit, target, selection, and working marks are"
                + " untouched, asserted by the journey tests.");
        System.out.println("- **Modules stay colour-free.** They"
                + " contribute typed geometry and ink roles; the"
                + " chart's two ink painters translate role to"
                + " palette colour.");
        System.out.println();
        System.out.println("## The Milky Way, deferred");
        System.out.println();
        System.out.println("`ChartPalette` deliberately carries no"
                + " Milky Way colour: that imagery is parked"
                + " unlicensed (Sprint 22), and choosing its"
                + " dark-ground treatment before the source is"
                + " licensed would be a palette chosen in advance of"
                + " its data. The compatibility question is recorded"
                + " in docs/decisions/black-sky.md, not answered"
                + " here.");
    }
}
