package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

import juranometria.app.ChartOptionsDialog;

/**
 * Chart Options, in both languages, for owner review
 * (Sprint 33, issue #350).
 *
 * <p>Four tabs, and a reader sees one at a time - so each is drawn
 * separately and all four are shown. A checkpoint that pictured only
 * the tab that happened to be selected would leave three quarters of
 * a surface unreviewed while looking complete.
 *
 * <p>The companion report carries what no picture can: tooltips,
 * accessible names, and the spoken descriptions - which on this
 * surface are the longest strings and the ones where a translation
 * most easily goes wrong, because nobody sees them.
 */
public final class ChartOptionsSheetMain {

    /**
     * What this photographer holds still: the application states this window’s size, and packing
     * it would photograph a width no reader meets.
     *
     * <p>Read by the display evidence gate, which refuses a
     * generator that declares one kind and asks the capture
     * coordinator for another.
     */
    public static final SheetCapture.Kind CAPTURE_KIND =
            SheetCapture.Kind.APPLICATION_SIZED;

    private ChartOptionsSheetMain() {
    }

    /**
     * Where the sheets go: the committed directory by default, or a
     * directory a caller names as {@code args[0]}.
     *
     * <p>`InterfaceEvidenceGateTest` runs every one of these into a
     * scratch directory and compares the result with what is
     * committed. It can only do that if a generator can be told
     * where to write; one that always writes over the evidence
     * cannot be used to check it.
     */
    private static Path out =
            Path.of("docs/studies/interface-language");

    /**
     * The width the dialog actually packs to.
     *
     * <p>Not a number chosen for the sheet. At 620 px the first
     * capture showed three descriptions truncated with an ellipsis -
     * which a reader never sees, because the dialog WRAPS them. A
     * checkpoint image that invents a defect wastes the reviewer's
     * attention exactly as surely as one that hides a real one.
     */
    private static final int WIDE = ChartOptionsDialog.ORDINARY_WIDTH;

    public static void main(String[] args) throws Exception {
        if (args.length > 0 && !args[0].isBlank()) {
            out = Path.of(args[0]);
        }
        Files.createDirectories(out);
        SwingUtilities.invokeAndWait(() -> juranometria.app.UiTheme.apply(false));

        StringBuilder said = new StringBuilder("""
                # Every word Chart Options says

                Issue #350. Generated by
                `juranometria.tool.ChartOptionsSheetMain` from compiled
                application classes and their classpath resources.
                Packaged acceptance separately verifies that the
                interface language resources ship in the application
                image.

                Four tabs, drawn one per image because that is how a
                reader meets them, in a real window at the width the
                dialog packs to. This table carries what the images
                cannot: the tooltip a reader sees on hovering, the
                name assistive technology speaks, and the description
                it reads out - the longest strings on the surface and
                the ones a translation most easily gets wrong,
                because nobody looks at them.

                %s

                """.formatted(juranometria.tool.InterfaceLanguageStatus
                        .statement("nb-NO")));

        for (String language : List.of("en", "nb-NO")) {
            java.util.prefs.Preferences node = java.util.prefs.Preferences
                    .userRoot().node("juranometria-study-co-"
                            + System.nanoTime());
            javax.swing.JFrame[] owner = new javax.swing.JFrame[1];
            juranometria.app.ChartOptionsDialog[] dialog =
                    new juranometria.app.ChartOptionsDialog[1];
            try {
                SwingUtilities.invokeAndWait(() -> {
                    owner[0] = new javax.swing.JFrame("study");
                    dialog[0] = ChartOptionsDialog.packedForStudy(owner[0],
                            language, new juranometria.app
                                    .ChartOptionsController(juranometria.app
                                    .ChartOptionsStore.forNode(node)));
                });
                SwingUtilities.invokeAndWait(() -> { });
                JComponent content =
                        (JComponent) dialog[0].getContentPane();
                JTabbedPane tabs = ChartOptionsDialog.tabsOf(content);
                said.append("## ").append(language.equals("en")
                        ? "English" : "Norsk bokmål").append(" (`")
                        .append(language).append("`)\n\n");
                for (int tab = 0; tab < tabs.getTabCount(); tab++) {
                    int which = tab;
                    SwingUtilities.invokeAndWait(() -> {
                        tabs.setSelectedIndex(which);
                        ChartOptionsDialog.settle(dialog[0]);
                    });
                    SwingUtilities.invokeAndWait(() -> { });
                    draw(dialog[0], content,
                            out.resolve("chartoptions-" + language
                                    + "-" + (tab + 1) + ".png"));
                    said.append("### ").append(tabs.getTitleAt(tab))
                            .append("\n\n")
                            .append("| shown | hovered | spoken as | read out |\n")
                            .append("|---|---|---|---|\n")
                            .append(describe(tabs.getComponentAt(tab)))
                            .append('\n');
                }
                // The window itself. A picture may legitimately
                // omit native chrome; a report claiming every word
                // may not omit words that are shown in a title bar
                // or spoken when the window takes focus.
                said.append("### The window itself\n\n")
                        .append("| shown | hovered | spoken as | read out |\n")
                        .append("|---|---|---|---|\n")
                        .append("| ").append(cell(dialog[0].getTitle()))
                        .append(" | — | ")
                        .append(cell(dialog[0].getAccessibleContext()
                                .getAccessibleName()))
                        .append(" | ")
                        .append(cell(dialog[0].getAccessibleContext()
                                .getAccessibleDescription()))
                        .append(" |\n| — | ")
                        .append(cell(tabs.getToolTipText()))
                        .append(" | ")
                        .append(cell(tabs.getAccessibleContext()
                                .getAccessibleName()))
                        .append(" | ")
                        .append(cell(tabs.getAccessibleContext()
                                .getAccessibleDescription()))
                        .append(" |\n\n");
                said.append("### The window's own controls\n\n")
                        .append("| shown | hovered | spoken as | read out |\n")
                        .append("|---|---|---|---|\n")
                        .append(describe(content, tabs)).append('\n');
            } finally {
                SwingUtilities.invokeAndWait(() -> {
                    if (dialog[0] != null) {
                        dialog[0].dispose();
                    }
                    if (owner[0] != null) {
                        owner[0].dispose();
                    }
                });
                node.removeNode();
            }
        }

        Files.writeString(out.resolve("chartoptions-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("chart options sheets: 8 images and "
                + out.resolve("chartoptions-strings.md"));
    }

    /**
     * One sheet, taken once its state is established.
     *
     * <p>This used to paint as soon as the tab had been selected and
     * the queue given one round-trip. About one run in six that was
     * too early: the button row came out a pixel to the right,
     * everything left of x=192 identical and everything from x=253
     * moved. `SheetCapture` requires the layout to reach a fixed
     * point first, and refuses rather than guessing.
     */
    private static void draw(java.awt.Window window,
                             JComponent content, Path to)
            throws Exception {
        // Application-sized: this dialog states ORDINARY_WIDTH
        // through sizeToScreen, so packing it would photograph a
        // preference of 394 px that no reader meets.
        SheetCapture.write(window, content,
                SheetCapture.applicationSized(
                        "ChartOptionsDialog.settle",
                        new SheetCapture.ApplicationPolicy() {

                            // ORDINARY_WIDTH and the tallest tab's
                            // height, computed by the dialog's own
                            // rule; settle() then sets that size
                            // without packing.
                            @Override
                            public java.awt.Dimension declaredContent() {
                                return juranometria.app.ChartOptionsDialog
                                        .settledContentSize(
                                                (juranometria.app
                                                        .ChartOptionsDialog)
                                                        window);
                            }

                            @Override
                            public void apply() {
                                juranometria.app.ChartOptionsDialog.settle(
                                        (juranometria.app.ChartOptionsDialog)
                                                window);
                            }
                        }),
                to);
    }

    private static void layoutDeeply(Container from) {
        from.doLayout();
        for (Component child : from.getComponents()) {
            if (child instanceof Container nested) {
                layoutDeeply(nested);
            }
        }
    }

    /** Every control's four texts, in reading order. */
    private static String describe(Component from, Component... skip) {
        StringBuilder rows = new StringBuilder();
        for (Component control : reading(from, List.of(skip))) {
            if (!(control instanceof JComponent said)) {
                continue;
            }
            String shown = control instanceof AbstractButton button
                    ? button.getText()
                    : control instanceof JLabel label ? label.getText() : null;
            String hovered = said.getToolTipText();
            String name = said.getAccessibleContext() == null ? null
                    : said.getAccessibleContext().getAccessibleName();
            String read = said.getAccessibleContext() == null ? null
                    : said.getAccessibleContext().getAccessibleDescription();
            if (blank(shown) && blank(hovered) && blank(name) && blank(read)) {
                continue;
            }
            rows.append("| ").append(cell(shown))
                    .append(" | ").append(cell(hovered))
                    .append(" | ").append(cell(name))
                    .append(" | ").append(cell(read)).append(" |\n");
        }
        return rows.toString();
    }

    private static boolean blank(String text) {
        return text == null || text.isBlank();
    }

    private static String cell(String text) {
        if (blank(text)) {
            return "—";
        }
        return plainText(text).replace("|", "\\|");
    }

    /**
     * The words inside wrapped HTML, with their boundaries intact.
     *
     * <p>The first version deleted tags outright. The dialog wraps by
     * putting {@code <br>} between lines, so deleting it welded the
     * words on either side together: "angitt i" and "katalogen"
     * became "angitt ikatalogen", and "M 13, M 22" became "M13, M22".
     * The DIALOG was right and the report was wrong - which is worse
     * than a wrong dialog, because the report is what a reviewer
     * reads when deciding whether the words are any good.
     *
     * <p>A tag is a boundary, so it becomes a space, and the runs of
     * space it leaves are collapsed afterwards.
     */
    static String plainText(String text) {
        return text.replaceAll("<[^>]*>", " ")
                .replace("&nbsp;", " ")
                .replaceAll("\\s+", " ").trim();
    }

    private static List<Component> reading(Component from,
                                           List<Component> skip) {
        List<Component> found = new ArrayList<>();
        if (!(from instanceof Container container)) {
            return found;
        }
        for (Component child : container.getComponents()) {
            if (skip.contains(child)) {
                continue;
            }
            found.add(child);
            found.addAll(reading(child, skip));
        }
        return found;
    }
}
