package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.prefs.Preferences;

import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

import juranometria.app.ChartKeyboard;
import juranometria.app.ChartKeys;
import juranometria.app.ChartOptionsController;
import juranometria.app.ChartOptionsStore;
import juranometria.app.ChartSwitches;
import juranometria.ui.language.ChartKeyboardText;
import juranometria.ui.language.InterfaceText;

/**
 * Every word the chart's keyboard says, in both languages
 * (Sprint 33, issue #350).
 *
 * <p>The real palette, shown in a real window through
 * {@code showIn}, with its state reached through the real
 * {@code ChartSwitches} over a real options controller - so what is
 * photographed is what the availability rule actually produces,
 * rather than a picture of a state drawn by hand.
 *
 * <p>It installs its own look and feel before any component exists
 * (#362), and it draws each arrangement under both, because the
 * greyed rows take their colour from the theme.
 *
 * <p><strong>It refuses a partial run.</strong> Sixteen captures are
 * required and each is counted; a companion written from fewer would
 * be a report of a smaller thing wearing the name of the whole.
 */
public final class ChartKeyboardSheetMain {

    private ChartKeyboardSheetMain() {
    }

    private static final Path OUT =
            Path.of("docs/studies/interface-language");

    /** One arrangement of the switches, and why it is here. */
    private record State(String name, String title, String note) {
    }

    private static final List<State> STATES = List.of(
            new State("all-off", "Everything off",
                    "Every switch clear. All seven dependent rows are"
                            + " unavailable and each names the master"
                            + " it waits for - the state that proves"
                            + " the dependency sentence, which is the"
                            + " one no language can keep in English"
                            + " order."),
            new State("all-on", "Everything on",
                    "Every switch set, including the three whose"
                            + " letter differs from the one on their"
                            + " own control - so all three notes are"
                            + " visible at once."),
            new State("deepsky-off", "The deep-sky master off",
                    "Six families and the deep-sky names wait on one"
                            + " switch. Greyed, and said in words as"
                            + " well as in colour, because a reader"
                            + " who cannot see the grey needs the same"
                            + " answer."),
            new State("figures-off", "The figures master off",
                    "The second dependency, with a different master:"
                            + " the constellation names ride the"
                            + " figures."));

    public static void main(String[] args) throws Exception {
        if (java.awt.GraphicsEnvironment.isHeadless()) {
            System.err.println("a palette has to be on screen to be"
                    + " photographed, and a panel drawn without a"
                    + " window is not the palette");
            System.exit(1);
        }
        Files.createDirectories(OUT);
        StringBuilder said = new StringBuilder();
        said.append("""
                # Every word the chart's keyboard says

                Issue #350. Generated by
                `juranometria.tool.ChartKeyboardSheetMain` from
                compiled application classes and their classpath
                resources. Packaged acceptance separately verifies
                that the interface language resources ship in the
                application image.

                %s

                ## A palette, not a window

                `ChartKeyboard` is a panel added to the frame's
                layered pane, so it has **no window and no title**.
                Its outer channel is its own accessible context, and
                both halves of it are listed with every capture.

                It carries **no hover text at all**: not one
                `setToolTipText` in the class. That channel is empty
                rather than unread, and is recorded as empty.

                ## What is language here, and what is not

                The letter beside each row and the prefix `⌘K` are
                notation and are identical in both languages. What is
                **between** two keystrokes is not: `ChartKeys.Toggle`
                joined them with the English word "then" until this
                issue, and it now comes from `ShortcutText` like every
                other shortcut sentence in the atlas.

                The three notes are **language-specific by design**.
                They explain why the letter here differs from the one
                on the switch's own control in Chart Options, which is
                a fact about a particular language's collisions - so a
                language declares a note or declares `!none`, and a
                key simply missing is a fault rather than a silence.

                """.formatted(juranometria.tool.InterfaceLanguageStatus
                        .statement("nb-NO")));

        int sheet = 1;
        int drawn = 0;
        for (String language : List.of("en", "nb-NO")) {
            InterfaceText text = InterfaceText.forLanguage(language);
            ChartKeyboardText words = ChartKeyboardText.in(text);
            said.append("## ").append(language.equals("en") ? "English"
                            : "Norsk bokmål").append(" (`")
                    .append(language).append("`)\n\n")
                    .append(chrome(words)).append(notes(words))
                    .append(announcements(words));
            for (String theme : List.of("light", "dark")) {
                said.append("### ").append(theme.equals("dark")
                        ? "Dark" : "Light").append("\n\n");
                for (State state : STATES) {
                    said.append("#### ").append(state.title())
                            .append("\n\n").append(state.note())
                            .append("\n\n")
                            .append(draw(language, text, state,
                                    theme.equals("dark"),
                                    OUT.resolve("chartkeyboard-"
                                            + language + "-"
                                            + (sheet++) + "-"
                                            + state.name() + "-"
                                            + theme + ".png")))
                            .append('\n');
                    drawn++;
                }
            }
        }
        said.append(deferred());
        if (drawn != 16) {
            throw new IllegalStateException("sixteen captures are"
                    + " required - four arrangements, two themes, two"
                    + " languages - and this run drew " + drawn
                    + ". A companion written from a partial run"
                    + " reports a smaller thing under the name of the"
                    + " whole.");
        }
        Files.writeString(OUT.resolve("chartkeyboard-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("chart keyboard sheets: " + drawn
                + " images and " + OUT.resolve("chartkeyboard-strings.md"));
    }

    /** The palette's own two channels, and the words around the rows. */
    private static String chrome(ChartKeyboardText said) {
        StringBuilder out = new StringBuilder(
                "### The palette itself\n\n| channel | words |\n|---|---|\n");
        row(out, "accessible name", said.title());
        row(out, "accessible description, **before any press**",
                said.explain());
        row(out, "heading", said.heading());
        row(out, "instruction", said.instruction());
        row(out, "refused row, shown",
                said.refusedRow(ChartKeys.refused().get(0)));
        row(out, "refused row, spoken",
                said.refusedSpoken(ChartKeys.refused().get(0)));
        return out.append('\n').toString();
    }

    /** Which switches this language explains, and which stay silent. */
    private static String notes(ChartKeyboardText said) {
        StringBuilder out = new StringBuilder(
                "### The notes this language gives\n\n"
                        + "| switch | note |\n|---|---|\n");
        int given = 0;
        for (ChartKeys.Toggle toggle : ChartKeys.toggles()) {
            String note = said.note(toggle);
            if (note != null) {
                row(out, said.label(toggle), note);
                given++;
            }
        }
        out.append("\n").append(given).append(" of ")
                .append(ChartKeys.toggles().size())
                .append(" switches carry a note; the rest declare")
                .append(" `!none`, which is a decision rather than a")
                .append(" gap.\n\n");
        return out.toString();
    }

    /**
     * What the palette says as it acts.
     *
     * <p>Transient, and worth writing down because it is the one
     * thing here no photograph of a resting palette can show.
     */
    private static String announcements(ChartKeyboardText said) {
        ChartKeys.Toggle grid = ChartKeys.toggle("chart.equatorialGrid");
        ChartKeys.Toggle meridian = ChartKeys.toggle("module.meridian");
        ChartKeys.Toggle galaxies = ChartKeys.toggle("chart.galaxies");
        ChartKeys.Toggle names =
                ChartKeys.toggle("chart.constellationNames");
        StringBuilder out = new StringBuilder(
                "### What it says as it acts\n\n"
                        + "Three patterns, six rendered forms. After any"
                        + " of them the palette's accessible"
                        + " **description** carries the sentence below"
                        + " instead of the standing instruction - see"
                        + " the deferred finding at the end.\n\n"
                        + "| occasion | words |\n|---|---|\n");
        row(out, "a remembered switch, on", said.announce(grid, true));
        row(out, "a remembered switch, off", said.announce(grid, false));
        row(out, "a session-only switch, on",
                said.announce(meridian, true));
        row(out, "a session-only switch, off",
                said.announce(meridian, false));
        row(out, "a letter that reaches a waiting switch",
                said.announceUnavailable(galaxies,
                        ChartKeys.toggle("chart.deepSkyObjects")));
        row(out, "and the other master",
                said.announceUnavailable(names,
                        ChartKeys.toggle("chart.constellationFigures")));
        return out.append('\n').toString();
    }

    /** Said rather than fixed, and said so. */
    private static String deferred() {
        return """
                ## Deferred, and not fixed here

                After a reader's first keystroke the palette's
                accessible **description** stops carrying its standing
                instructions and carries the last announcement
                instead. One accessible property is doing two jobs -
                stable help, and transient status - so the help is
                gone for the rest of the session.

                Both are translated here and **neither behaviour
                changes**. Separating them needs an announcement seam
                proved to reach a screen reader, which is an
                accessibility question rather than a localisation one.
                This checkpoint does not fix it, and the tables above
                mark which description is which so that nothing here
                reads as though it had.
                """;
    }

    /** Draws one arrangement in one language and returns its strings. */
    private static String draw(String language, InterfaceText text,
                               State state, boolean dark, Path to)
            throws Exception {
        Preferences node = Preferences.userRoot()
                .node("juranometria-study-chartkeyboard-"
                        + System.nanoTime());
        JFrame[] owner = new JFrame[1];
        ChartKeyboard[] palette = new ChartKeyboard[1];
        try {
            SwingUtilities.invokeAndWait(() -> {
                // Stated before any component exists (#362).
                juranometria.app.UiTheme.apply(dark);

                ChartOptionsController options =
                        new ChartOptionsController(
                                ChartOptionsStore.forNode(node));
                boolean[] ecliptic = {false};
                boolean[] lines = {false, false};
                ChartSwitches switches = switches(options, ecliptic,
                        lines);
                arrange(switches, state.name());

                palette[0] = ChartKeyboard.of(switches, text);
                owner[0] = new JFrame("study");
                owner[0].setSize(900, 700);
                owner[0].setVisible(true);
                palette[0].showIn(owner[0].getRootPane());
                palette[0].refresh();
            });
            SwingUtilities.invokeAndWait(() -> { });
            return capture(palette[0], language, to);
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (palette[0] != null) {
                    palette[0].close();
                }
                if (owner[0] != null) {
                    owner[0].dispose();
                }
            });
            try {
                node.removeNode();
            } catch (java.util.prefs.BackingStoreException leaving) {
                // An empty node is a blemish, not a failure.
            }
        }
    }

    /** Reaches a state through the real transitions, never by hand. */
    private static void arrange(ChartSwitches switches, String state) {
        boolean wantOn = !state.equals("all-off");
        for (ChartKeys.Toggle toggle : ChartKeys.toggles()) {
            if (switches.available(toggle.id())
                    && switches.on(toggle.id()) != wantOn) {
                switches.toggle(toggle.id());
            }
        }
        if (state.equals("deepsky-off")
                && switches.on(ChartKeys.DEEP_SKY)) {
            switches.toggle(ChartKeys.DEEP_SKY);
        }
        if (state.equals("figures-off")
                && switches.on(ChartKeys.FIGURES)) {
            switches.toggle(ChartKeys.FIGURES);
        }
    }

    private static ChartSwitches switches(ChartOptionsController options,
                                          boolean[] ecliptic,
                                          boolean[] lines) {
        return ChartSwitches.of(options, new ChartSwitches.Ecliptic() {
            @Override
            public boolean showing() {
                return ecliptic[0];
            }

            @Override
            public void toggle() {
                ecliptic[0] = !ecliptic[0];
            }
        }, new ChartSwitches.ObserverLines() {
            @Override
            public boolean meridianShowing() {
                return lines[0];
            }

            @Override
            public boolean horizonShowing() {
                return lines[1];
            }

            @Override
            public void showing(boolean meridian, boolean horizon) {
                lines[0] = meridian;
                lines[1] = horizon;
            }
        });
    }

    private static String capture(ChartKeyboard palette, String language,
                                  Path to) throws Exception {
        Set<String> shown = new LinkedHashSet<>();
        List<String> spoken = new ArrayList<>();
        BufferedImage[] image = new BufferedImage[1];
        SwingUtilities.invokeAndWait(() -> {
            BufferedImage drawn = new BufferedImage(
                    Math.max(1, palette.getWidth()),
                    Math.max(1, palette.getHeight()),
                    BufferedImage.TYPE_INT_RGB);
            Graphics2D g = drawn.createGraphics();
            try {
                g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                        RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g.setColor(palette.getBackground() == null
                        ? Color.WHITE : palette.getBackground());
                g.fillRect(0, 0, drawn.getWidth(), drawn.getHeight());
                palette.paint(g);
            } finally {
                g.dispose();
            }
            image[0] = drawn;
            collect(palette, shown, spoken);
        });
        ImageIO.write(image[0], "png", to.toFile());

        StringBuilder out = new StringBuilder();
        out.append("![](").append(to.getFileName()).append(")\n\n")
                .append(image[0].getWidth()).append(" × ")
                .append(image[0].getHeight()).append(" px, `")
                .append(language).append("`.\n\n")
                .append("| shown | spoken |\n|---|---|\n");
        List<String> rows = new ArrayList<>(shown);
        for (int i = 0; i < Math.max(rows.size(), spoken.size()); i++) {
            out.append("| ")
                    .append(i < rows.size() ? escape(rows.get(i)) : "")
                    .append(" | ")
                    .append(i < spoken.size() ? escape(spoken.get(i)) : "")
                    .append(" |\n");
        }
        return out.toString();
    }

    private static void collect(Container from, Set<String> shown,
                                List<String> spoken) {
        for (Component child : from.getComponents()) {
            if (child instanceof JLabel label) {
                String text = label.getText();
                if (text != null && !text.isBlank()) {
                    shown.add(text.replaceAll("\\s+", " ").trim()
                            + (label.isEnabled() ? "" : "  [greyed]"));
                }
                if (label.getAccessibleContext() != null) {
                    String name = label.getAccessibleContext()
                            .getAccessibleName();
                    String description = label.getAccessibleContext()
                            .getAccessibleDescription();
                    for (String one : List.of(
                            name == null ? "" : name,
                            description == null ? "" : description)) {
                        if (!one.isBlank() && !spoken.contains(one)) {
                            spoken.add(one);
                        }
                    }
                }
            }
            if (child instanceof Container nested) {
                collect(nested, shown, spoken);
            }
        }
    }

    private static void row(StringBuilder out, String what, String words) {
        out.append("| ").append(what).append(" | ")
                .append(escape(words)).append(" |\n");
    }

    private static String escape(String text) {
        return text == null ? "—" : text.replace("|", "\\|");
    }
}
