package juranometria.tool;

import java.awt.Component;
import java.awt.Container;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.prefs.Preferences;

import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import juranometria.meridian.MeridianModule;
import juranometria.sky.Observer;
import juranometria.ui.companion.CompanionStore;
import juranometria.ui.companion.CompanionWindow;
import juranometria.ui.language.InterfaceText;
import juranometria.ui.placeandtime.PlaceAndTimePanel;
import juranometria.ui.placeandtime.PlaceStore;

/**
 * The companion window, in both languages, for owner review (#434).
 *
 * <p>The production window with its one production section, Place and
 * Time, in a real window at the size its own policy states: open in
 * the light and the dark appearance, with the section collapsed, and
 * with an entry refused. The companion report carries what no picture
 * can - what each control is called, hovered and read out.
 *
 * <p>Process-wide state is the photographer's to put back: the
 * contract runs every generator in one process, and an earlier one may
 * leave a default font behind (#362).
 */
public final class CompanionSheetMain {

    /**
     * Application-sized: the companion states its own width and the
     * height its sections ask for, and packing it would photograph a
     * window no reader meets.
     */
    public static final SheetCapture.Kind CAPTURE_KIND =
            SheetCapture.Kind.APPLICATION_SIZED;

    private static Path out = Path.of("docs/studies/interface-language");

    /** One arrangement, and what it shows. */
    private record State(String name, boolean dark, boolean collapsed,
                         String refused) {
    }

    private static final List<State> STATES = List.of(
            new State("open", false, false, null),
            new State("dark", true, false, null),
            new State("collapsed", false, true, null),
            new State("refused", false, false, "91"));

    private CompanionSheetMain() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length > 0 && !args[0].isBlank()) {
            out = Path.of(args[0]);
        }
        if (java.awt.GraphicsEnvironment.isHeadless()) {
            System.err.println("a window needs a display, and a stand-in"
                    + " panel is what the review rejected");
            System.exit(1);
        }
        Files.createDirectories(out);
        javax.swing.LookAndFeel before = UIManager.getLookAndFeel();
        boolean hadFont = UIManager.getDefaults().containsKey("defaultFont");
        Object font = hadFont ? UIManager.get("defaultFont") : null;
        PlaceAndTimeSheetMain.State oslo = PlaceAndTimeSheetMain.STATES.stream()
                .filter(state -> state.name().equals("oslo"))
                .findFirst().orElseThrow();
        StringBuilder said = new StringBuilder("""
                # Every word the companion says

                Issue #434. Generated by
                `juranometria.tool.CompanionSheetMain` from compiled
                application classes and their classpath resources.

                The production companion window, holding its one
                production section - the same `PlaceAndTimePanel` the
                Place and Time dialog holds - in a real window at the
                size the companion's own policy states. Place and Time
                is `PlaceAndTimeSheetMain`'s Oslo arrangement at its
                frozen instant.

                %s

                """.formatted(InterfaceLanguageStatus.statement("nb-NO")));
        try {
            SwingUtilities.invokeAndWait(() -> UIManager.put("defaultFont", null));
            for (String language : List.of("en", "nb-NO")) {
                said.append("## ").append(language.equals("en")
                        ? "English" : "Norsk bokmål").append(" (`")
                        .append(language).append("`)\n\n");
                int number = 1;
                for (State state : STATES) {
                    String name = "companion-" + language + "-" + number++
                            + "-" + state.name() + ".png";
                    said.append(sheet(language, state, oslo, out.resolve(name)));
                }
            }
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                UIManager.put("defaultFont", font);
                try {
                    UIManager.setLookAndFeel(before);
                } catch (javax.swing.UnsupportedLookAndFeelException gone) {
                    throw new IllegalStateException(gone);
                }
            });
        }
        Files.writeString(out.resolve("companion-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("companion sheets: 8 images and "
                + out.resolve("companion-strings.md"));
    }

    private static String sheet(String language, State state,
                                PlaceAndTimeSheetMain.State place, Path to)
            throws Exception {
        Preferences node = Preferences.userRoot().node(
                "juranometria-study-companion-sheet-" + System.nanoTime());
        JFrame[] owner = new JFrame[1];
        CompanionWindow[] window = new CompanionWindow[1];
        PlaceAndTimePanel[] panel = new PlaceAndTimePanel[1];
        try {
            SwingUtilities.invokeAndWait(() -> {
                juranometria.app.UiTheme.apply(state.dark());
                InterfaceText words = InterfaceText.forLanguage(language);
                MeridianModule module = new MeridianModule(new Observer(
                        place.latitude(), place.eastLongitude(),
                        PlaceAndTimeSheetMain.WHEN));
                module.showing(place.meridian(), place.horizon(),
                        place.zenith());
                PlaceStore store = PlaceStore.forNode(node);
                store.save(place.latitude(), place.eastLongitude());
                owner[0] = new JFrame("study");
                window[0] = new CompanionWindow(owner[0], words,
                        CompanionStore.forNode(node));
                panel[0] = new PlaceAndTimePanel(module, store,
                        () -> PlaceAndTimeSheetMain.WHEN, words);
                window[0].addSection("placeandtime",
                        words.say("placeandtime.title"), panel[0]);
                if (state.collapsed()) {
                    window[0].sections().get(0).heading().doClick();
                }
                if (state.refused() != null) {
                    JTextField latitude = (JTextField) named(panel[0],
                            "latitudeField");
                    latitude.setText(state.refused());
                    latitude.postActionEvent();
                }
                window[0].applySizePolicy();
            });
            SwingUtilities.invokeAndWait(() -> { });
            JComponent content = (JComponent) window[0].getContentPane();
            SheetCapture.write(window[0], content,
                    SheetCapture.applicationSized(
                            "CompanionWindow.applySizePolicy",
                            new SheetCapture.ApplicationPolicy() {
                                @Override
                                public java.awt.Dimension declaredContent() {
                                    return window[0].sizePolicyContent();
                                }

                                @Override
                                public void apply() {
                                    window[0].applySizePolicy();
                                }
                            }),
                    to);
            StringBuilder rows = new StringBuilder();
            rows.append("### ").append(state.name()).append("\n\n")
                    .append("![](").append(to.getFileName()).append(")\n\n")
                    .append("| shown | hovered | spoken as | read out |\n")
                    .append("|---|---|---|---|\n")
                    .append("| ").append(cell(window[0].getTitle()))
                    .append(" | — | ")
                    .append(cell(window[0].getAccessibleContext()
                            .getAccessibleName()))
                    .append(" | ")
                    .append(cell(window[0].getAccessibleContext()
                            .getAccessibleDescription()))
                    .append(" |\n")
                    .append(describe(content)).append('\n');
            return rows.toString();
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (window[0] != null) {
                    window[0].dispose();
                }
                if (owner[0] != null) {
                    owner[0].dispose();
                }
            });
            try {
                node.removeNode();
            } catch (java.util.prefs.BackingStoreException leaving) {
                // An empty node is a blemish, not a failure.
            }
        }
    }

    private static Component named(Component root, String name) {
        if (name.equals(root.getName())) {
            return root;
        }
        if (root instanceof Container container) {
            for (Component child : container.getComponents()) {
                Component found = named(child, name);
                if (found != null) {
                    return found;
                }
            }
        }
        return null;
    }

    /** Every visible control's four texts, in reading order. */
    private static String describe(Component from) {
        StringBuilder rows = new StringBuilder();
        for (Component control : reading(from)) {
            if (!(control instanceof JComponent said) || !control.isVisible()) {
                continue;
            }
            String shown = control instanceof AbstractButton button
                    ? button.getText()
                    : control instanceof JLabel label ? label.getText()
                    : control instanceof JTextField field ? field.getText()
                    : null;
            String hovered = said.getToolTipText();
            String name = said.getAccessibleContext() == null ? null
                    : said.getAccessibleContext().getAccessibleName();
            String read = said.getAccessibleContext() == null ? null
                    : said.getAccessibleContext().getAccessibleDescription();
            if (blank(shown) && blank(hovered) && blank(name) && blank(read)) {
                continue;
            }
            rows.append("| ").append(cell(shown))
                    .append(" | ").append(cell(hovered))
                    .append(" | ").append(cell(name))
                    .append(" | ").append(cell(read)).append(" |\n");
        }
        return rows.toString();
    }

    private static List<Component> reading(Component from) {
        List<Component> found = new ArrayList<>();
        if (!(from instanceof Container container) || !from.isVisible()) {
            return found;
        }
        for (Component child : container.getComponents()) {
            if (!child.isVisible()) {
                continue;
            }
            found.add(child);
            found.addAll(reading(child));
        }
        return found;
    }

    private static boolean blank(String text) {
        return text == null || text.isBlank();
    }

    private static String cell(String text) {
        return blank(text) ? "—" : ChartOptionsSheetMain.plainText(text)
                .replace("|", "\\|");
    }
}
