package juranometria.tool;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.imageio.ImageIO;
import javax.swing.UIManager;

import juranometria.catalog.TiledCatalogue;
import juranometria.chart.DeepSkyObject;
import juranometria.chart.DsoType;
import juranometria.chart.SkyPosition;
import juranometria.chart.SkyRegion;
import juranometria.render.ChartRenderer;
import juranometria.render.SymbolFamily;
import juranometria.ui.SymbolChip;

/**
 * The deep-sky vocabulary gate's evidence (Sprint 21, issue #184):
 * what the bundled pack actually contains, which catalogue types
 * share one chart symbol, which are deliberately left undrawn, and
 * whether the chart's own symbols can teach a reader at dialog scale
 * in both application themes.
 *
 * <p>Every symbol is drawn by {@link ChartRenderer#drawLegendSymbol}
 * and every family is derived from
 * {@link ChartRenderer#symbolForType}. The study owns no vocabulary
 * of its own, so a legend cannot come to teach a symbol the chart has
 * stopped drawing.
 */
public final class DeepSkyVocabularyStudyMain {

    private DeepSkyVocabularyStudyMain() {
    }

    private static final File DIR =
            new File("docs/studies/deep-sky-vocabulary");

    /**
     * The five families, read from production. The gate proposed
     * them; #185 moved the words into {@link SymbolFamily} beside the
     * symbols, so the dialog a reader sees, the chart that draws them
     * and this study cannot come to differ.
     */
    static final java.util.List<SymbolFamily> FAMILIES =
            java.util.List.of(SymbolFamily.values());


    public static void main(String[] args) throws IOException {
        DIR.mkdirs();
        System.out.println("# Deep-sky vocabulary study (issue #184)");
        System.out.println();
        System.out.println("Generated by `make deep-sky-study`. Every"
                + " count is swept from the bundled pack and every"
                + " symbol is painted by the production renderer"
                + " (`ChartRenderer.drawLegendSymbol`).");
        System.out.println();

        List<DeepSkyObject> pack = wholePack();
        census(pack);
        reconciliation(pack);
        exclusivity();
        exemplars(pack);
        geometry();
        distinguishability();
        contrast();
        sourceTypeSurvives(pack);
        legendStrips();
        mockups();
    }

    /** Every bundled deep-sky row, swept once, exactly as #169 does. */
    static List<DeepSkyObject> wholePack() {
        TiledCatalogue catalogue = TiledCatalogue.load();
        List<DeepSkyObject> all = new ArrayList<>();
        for (int ra = 0; ra < 360; ra += 20) {
            for (int dec = -80; dec <= 80; dec += 20) {
                all.addAll(catalogue.deepSkyObjectsIn(new SkyRegion(
                        new SkyPosition(ra, dec), 15.0)));
            }
        }
        return all.stream().distinct().toList();
    }

    /** Every source type, counted, with the family it draws as. */
    private static void census(List<DeepSkyObject> pack) {
        Map<DsoType, Integer> counts = new EnumMap<>(DsoType.class);
        for (DsoType type : DsoType.values()) {
            counts.put(type, 0);
        }
        for (DeepSkyObject dso : pack) {
            counts.merge(dso.type(), 1, Integer::sum);
        }

        System.out.println("## Every source type in the bundled pack");
        System.out.println();
        System.out.printf(Locale.ROOT,
                "**%,d** deep-sky rows, every one of them counted"
                        + " below.%n%n", pack.size());
        System.out.println("| OpenNGC token | source type | rows |"
                + " chart symbol | reader-facing family |");
        System.out.println("|---|---|---:|---|---|");
        for (DsoType type : DsoType.values()) {
            SymbolFamily family = SymbolFamily.of(type);
            System.out.printf(Locale.ROOT, "| `%s` | %s | %,d | %s | %s |%n",
                    type.openNgcToken(), readable(type), counts.get(type),
                    ChartRenderer.symbolForType(type)
                            .name().toLowerCase(Locale.ROOT)
                            .replace('_', ' '),
                    family == null ? "**none — deliberately undrawn**"
                            : family.label());
        }
        System.out.println();
        System.out.println("`Other` is OpenNGC's own word for a row it"
                + " could not classify, not a token the atlas failed to"
                + " map: an unrecognised token stops the pack build"
                + " (`DsoType.fromOpenNgcToken`), so there is no such"
                + " thing here as a silently missing classification.");
        System.out.println();
    }

    private static String readable(DsoType type) {
        return type.name().toLowerCase(Locale.ROOT).replace('_', ' ');
    }

    /** The totals, made to reconcile exactly rather than by percentage. */
    private static void reconciliation(List<DeepSkyObject> pack) {
        Map<String, Integer> rows = new LinkedHashMap<>();
        Map<String, Integer> types = new LinkedHashMap<>();
        for (SymbolFamily family : FAMILIES) {
            rows.put(family.label(), 0);
            types.put(family.label(), 0);
        }
        int undrawn = 0;
        int undrawnTypes = 0;
        for (DeepSkyObject dso : pack) {
            SymbolFamily family = SymbolFamily.of(dso.type());
            if (family == null) {
                undrawn++;
            } else {
                rows.merge(family.label(), 1, Integer::sum);
            }
        }
        for (DsoType type : DsoType.values()) {
            SymbolFamily family = SymbolFamily.of(type);
            if (family == null) {
                undrawnTypes++;
            } else {
                types.merge(family.label(), 1, Integer::sum);
            }
        }

        System.out.println("## The five families, and what is left over");
        System.out.println();
        System.out.println("| family | source types | rows |");
        System.out.println("|---|---:|---:|");
        int drawable = 0;
        int drawableTypes = 0;
        for (SymbolFamily family : FAMILIES) {
            System.out.printf(Locale.ROOT, "| %s | %d | %,d |%n",
                    family.label(), types.get(family.label()),
                    rows.get(family.label()));
            drawable += rows.get(family.label());
            drawableTypes += types.get(family.label());
        }
        System.out.printf(Locale.ROOT,
                "| **drawable** | **%d** | **%,d** |%n",
                drawableTypes, drawable);
        System.out.printf(Locale.ROOT,
                "| deliberately undrawn | %d | %,d |%n",
                undrawnTypes, undrawn);
        System.out.printf(Locale.ROOT,
                "| **the whole pack** | **%d** | **%,d** |%n",
                drawableTypes + undrawnTypes, drawable + undrawn);
        System.out.println();
        System.out.printf(Locale.ROOT,
                "%,d drawable + %,d undrawn = %,d, and the sweep loaded"
                        + " %,d rows: the totals reconcile exactly, not"
                        + " within a band.%n%n",
                drawable, undrawn, drawable + undrawn, pack.size());
        if (drawable + undrawn != pack.size()) {
            throw new IllegalStateException("totals do not reconcile");
        }
    }

    /** That every drawable type has exactly one family, and no more. */
    private static void exclusivity() {
        System.out.println("## Exactly one family per drawable type");
        System.out.println();
        System.out.println("A family is defined as one production"
                + " symbol, so the mapping is a function by"
                + " construction. What could still go wrong is two"
                + " families claiming one symbol, or a symbol the"
                + " renderer draws that no family names - a type that"
                + " would appear on the chart with no control and no"
                + " explanation. Both are checked here and again in"
                + " `DeepSkyVocabularyTest`.");
        System.out.println();
        System.out.println("| chart symbol | families naming it |"
                + " source types drawn with it |");
        System.out.println("|---|---:|---|");
        for (ChartRenderer.Symbol symbol : ChartRenderer.Symbol.values()) {
            List<String> claiming = new ArrayList<>();
            for (SymbolFamily family : FAMILIES) {
                if (family.symbol() == symbol) {
                    claiming.add(family.label());
                }
            }
            List<String> drawn = new ArrayList<>();
            for (DsoType type : DsoType.values()) {
                if (ChartRenderer.symbolForType(type) == symbol) {
                    drawn.add(type.openNgcToken());
                }
            }
            System.out.printf(Locale.ROOT, "| %s | %d%s | %s |%n",
                    symbol.name().toLowerCase(Locale.ROOT)
                            .replace('_', ' '),
                    claiming.size(),
                    claiming.isEmpty() ? "" : " (" + String.join(", ",
                            claiming) + ")",
                    String.join(", ", drawn));
            int expected = symbol == ChartRenderer.Symbol.NONE ? 0 : 1;
            if (claiming.size() != expected) {
                throw new IllegalStateException(
                        symbol + " is named by " + claiming.size()
                                + " families");
            }
        }
        System.out.println();
    }

    /**
     * The shape each family is taught by, and the pack's own median
     * axis ratio it comes from.
     *
     * <p>The gate review's P1: a legend that shares the chart's
     * painter but hands it a circle for an oriented ellipse teaches
     * the wrong mark. The exemplars now live in the renderer
     * ({@code ChartRenderer.legendShapeFor}), and this is where the
     * numbers in them are checked against the catalogue.
     */
    private static void exemplars(List<DeepSkyObject> pack) {
        System.out.println("## The shape each family is taught by");
        System.out.println();
        System.out.println("A family's exemplar is the chart's own"
                + " painter given the family's own median proportions."
                + " The median is over every bundled row of that family"
                + " recording both axes; the exemplar is that median"
                + " rounded to a twentieth, and"
                + " `DeepSkyVocabularyTest` re-measures the pack and"
                + " fails if the two part company.");
        System.out.println();
        System.out.println("| family | rows recording both axes |"
                + " median minor/major | exemplar | tilt |");
        System.out.println("|---|---:|---:|---:|---:|");
        for (SymbolFamily family : FAMILIES) {
            List<Double> ratios = new ArrayList<>();
            for (DeepSkyObject dso : pack) {
                if (ChartRenderer.symbolFor(dso) != family.symbol()) {
                    continue;
                }
                Double major = dso.recorded().majorAxisArcmin();
                Double minor = dso.recorded().minorAxisArcmin();
                if (major != null && minor != null && major > 0.0) {
                    ratios.add(minor / major);
                }
            }
            ChartRenderer.LegendShape shape =
                    ChartRenderer.legendShapeFor(family.symbol());
            java.util.Collections.sort(ratios);
            System.out.printf(Locale.ROOT,
                    "| %s | %,d | %s | %.2f | %.0f° |%n", family.label(),
                    ratios.size(),
                    ratios.isEmpty() ? "-"
                            : String.format(Locale.ROOT, "%.3f",
                                    ratios.get(ratios.size() / 2)),
                    shape.minorFraction(),
                    shape.positionAngleDegrees());
        }
        System.out.println();
        System.out.println("Two of the five are round in the chart"
                + " itself: the globular cluster's and the planetary"
                + " nebula's painters take one axis and draw a circle,"
                + " whatever the catalogue recorded. Open clusters"
                + " measure 0.933, which at legend size is half a"
                + " pixel. Only the galaxy is tilted - a tilted"
                + " ellipse still reads as an ellipse, where a tilted"
                + " box reads as a diamond, a shape the chart does not"
                + " draw. Measured: tilting the box takes it from 64%"
                + " to 59% of ink unshared with its nearest"
                + " neighbour.");
        System.out.println();
    }

    /**
     * What a symbol actually occupies at legend sizes. This is not
     * decoration: the planetary nebula's spokes reach well past its
     * nominal size, and small sizes hit the renderer's practical
     * minimum, so a row that reserved exactly the nominal box would
     * clip the chart's own drawing.
     */
    private static void geometry() {
        System.out.println("## What each symbol occupies at legend sizes");
        System.out.println();
        System.out.println("Measured from the drawn pixels, not from the"
                + " size asked for. `size` is the larger axis passed to"
                + " `drawLegendSymbol`.");
        System.out.println();
        System.out.print("| size |");
        for (SymbolFamily family : FAMILIES) {
            System.out.printf(" %s |", family.label());
        }
        System.out.println();
        System.out.print("|---:|");
        for (int i = 0; i < FAMILIES.size(); i++) {
            System.out.print("---|");
        }
        System.out.println();
        for (int size : SIZES) {
            System.out.printf("| %d px |", size);
            for (SymbolFamily family : FAMILIES) {
                java.awt.Rectangle ink = inkBounds(swatch(family, size, 60));
                System.out.printf(Locale.ROOT, " %dx%d px |",
                        ink.width, ink.height);
            }
            System.out.println();
        }
        System.out.println();
        System.out.println("**The planetary nebula is the exception**,"
                + " and it is the renderer's own doing: its four spokes"
                + " reach 1.7 times its nominal radius, so it draws"
                + " almost twice the box every other family draws. A"
                + " legend row that reserved the size it asked for"
                + " would clip the chart's own symbol. The round"
                + " families overrun the asked-for size by the one"
                + " pixel of their outline stroke; the galaxy and the"
                + " nebula are narrower than they are tall, which is"
                + " the whole point of giving them the family's own"
                + " proportions.");
        System.out.println();
        int widest = 0;
        for (SymbolFamily family : FAMILIES) {
            java.awt.Rectangle ink = inkBounds(swatch(family,
                    (int) SymbolChip.SYMBOL_PX, 60));
            widest = Math.max(widest, Math.max(ink.width, ink.height));
        }
        System.out.printf(Locale.ROOT,
                "The mock-up draws its symbols at %.0f px on a %d px"
                        + " chip. The widest ink at that size is %d px"
                        + " (the planetary nebula), so the chip holds"
                        + " every family with %d px to spare.%n%n",
                SymbolChip.SYMBOL_PX,
                SymbolChip.CHIP_PX, widest,
                SymbolChip.CHIP_PX - widest);
        if (widest > SymbolChip.CHIP_PX) {
            throw new IllegalStateException(
                    "the chip clips the chart's own symbol");
        }
    }

    private static final int[] SIZES = {9, 11, 14, 18, 24};

    /** Whether the five symbols stay apart at the sizes a row gives. */
    private static void distinguishability() {
        System.out.println("## Do the five symbols read apart?");
        System.out.println();
        System.out.println("Each family is drawn at a size and compared"
                + " pixel by pixel against every other: the share of"
                + " inked pixels the two do **not** share, taken"
                + " against the family it resembles most. Two families"
                + " drawing the same shape would score 0%.");
        System.out.println();
        System.out.print("| size |");
        for (SymbolFamily family : FAMILIES) {
            System.out.printf(" %s |", family.label());
        }
        System.out.println(" nearest pair |");
        System.out.print("|---:|");
        for (int i = 0; i <= FAMILIES.size(); i++) {
            System.out.print("---:|");
        }
        System.out.println();
        for (int size : SIZES) {
            List<BufferedImage> drawn = new ArrayList<>();
            for (SymbolFamily family : FAMILIES) {
                drawn.add(swatch(family, size, 60));
            }
            System.out.printf("| %d px |", size);
            double worst = 100.0;
            String worstPair = "";
            for (int i = 0; i < FAMILIES.size(); i++) {
                double nearest = 100.0;
                for (int j = 0; j < FAMILIES.size(); j++) {
                    if (i == j) {
                        continue;
                    }
                    double difference =
                            difference(drawn.get(i), drawn.get(j));
                    if (difference < nearest) {
                        nearest = difference;
                    }
                    if (difference < worst) {
                        worst = difference;
                        worstPair = FAMILIES.get(i).label() + " / "
                                + FAMILIES.get(j).label();
                    }
                }
                System.out.printf(Locale.ROOT, " %.0f%% |", nearest);
            }
            System.out.printf(Locale.ROOT, " %.0f%% (%s) |%n", worst,
                    worstPair);
        }
        System.out.println();
    }

    /**
     * The contrast question the dark theme forces. Chart ink is
     * mid-grey on white and never follows the application theme, so a
     * symbol painted straight onto a dark dialog is nearly invisible.
     */
    private static void contrast() {
        System.out.println("## The chart's ink on a dialog's ground");
        System.out.println();
        System.out.println("WCAG contrast ratios for the chart's own"
                + " ink. **Direct** paints the symbol onto the"
                + " dialog's panel colour. **On paper** paints it onto"
                + " a scrap of the chart's own white paper, which is"
                + " what the mock-up does. **Faded** is the same chip"
                + " at 45% while its family is switched off - the"
                + " treatment this gate rejects. 3:1 is the WCAG floor"
                + " for a graphical object.");
        System.out.println();
        System.out.println("| theme | panel | ink | direct | on paper |"
                + " faded to 45% |");
        System.out.println("|---|---|---|---:|---:|---:|");
        // The inks are read from what the renderer actually drew, so
        // this table cannot come to quote a palette the chart has
        // stopped using.
        Color outlineInk = darkest(swatch(SymbolFamily.GLOBULAR_CLUSTERS,
                24, 60));
        Color nebulaInk = darkest(swatch(SymbolFamily.NEBULAE, 24, 60));
        Color[] inks = {outlineInk, nebulaInk};
        String[] inkNames = {
                "outline grey " + outlineInk.getRed()
                        + " (all but nebulae)",
                "nebula grey " + nebulaInk.getRed()};
        // The fade the gate rejected, kept only so the study can
        // keep pricing the alternative.
        float alpha = 0.45f;
        // Kept so the conclusions below quote the figures this run
        // actually measured, rather than figures typed beside them.
        double darkDirect = 0.0;
        double onPaper = 0.0;
        double nebulaOnPaper = 0.0;
        double fadedOutline = 0.0;
        double fadedNebula = 0.0;
        for (boolean dark : new boolean[] {false, true}) {
            DeepSkyVocabularyMockupMain.theme(dark, 1.0);
            Color panel = UIManager.getColor("Panel.background");
            for (int i = 0; i < inks.length; i++) {
                double direct = ratio(inks[i], panel);
                double paper = ratio(inks[i], Color.WHITE);
                double faded = ratio(blend(inks[i], panel, alpha),
                        blend(Color.WHITE, panel, alpha));
                System.out.printf(Locale.ROOT,
                        "| %s | %s | %s | %.2f:1 | %.2f:1 | %.2f:1 |%n",
                        dark ? "dark" : "light", hex(panel), inkNames[i],
                        direct, paper, faded);
                if (dark && i == 0) {
                    darkDirect = direct;
                    onPaper = paper;
                }
                if (!dark && i == 0) {
                    fadedOutline = faded;
                }
                if (!dark && i == 1) {
                    nebulaOnPaper = paper;
                    fadedNebula = faded;
                }
            }
        }
        System.out.println();
        rendered();
        System.out.println("### The rule, stated once");
        System.out.println();
        System.out.println("**Every mark in the legend clears 3:1"
                + " against the ground it is drawn on, as rendered.**"
                + " One threshold, applied to every state - not to the"
                + " rejected design only. Three things follow.");
        System.out.println();
        System.out.printf(Locale.ROOT,
                "1. **The symbol sits on paper.** In the dark theme the"
                        + " chart's outline grey scores %.2f:1 straight"
                        + " onto the panel - invisible - and %.2f:1 on"
                        + " the chart's own white. The chip is not"
                        + " decoration; it is the only way a dark"
                        + " dialog can show the chart's ink at all.%n",
                darkDirect, onPaper);
        System.out.printf(Locale.ROOT,
                "2. **A switched-off family does not fade its symbol.**"
                        + " Fading the chip to %.0f%% drops it to"
                        + " %.2f:1 and %.2f:1 - below the floor, in the"
                        + " very state where a reader consults the"
                        + " legend to decide what to switch back on."
                        + " The checkbox and its text take the"
                        + " platform's disabled styling; the symbol"
                        + " stays fully drawn, because it is"
                        + " information rather than a control.%n",
                alpha * 100.0, fadedOutline, fadedNebula);
        System.out.printf(Locale.ROOT,
                "3. **The nebula box was the one mark that failed the"
                        + " rule, and its ink changed.** At grey 150 it"
                        + " scored 2.96:1 - under the same threshold"
                        + " that rejected the fade, in a mark the"
                        + " legend depends on to teach and control a"
                        + " family. Rounding 2.96 up to 3 would have"
                        + " been marking our own homework. #185 raised"
                        + " it to grey %d, measured here at %.2f:1.%n",
                nebulaInk.getRed(), nebulaOnPaper);
        System.out.println();
        correction(nebulaInk);
    }

    /**
     * Contrast as drawn, not as declared. A one-pixel stroke on a
     * curve is antialiased, so the ink that reaches the screen is
     * lighter than the colour asked for - which is exactly what makes
     * a nominal 2.96:1 brittle rather than merely short.
     */
    private static void rendered() {
        System.out.println("### As rendered, not as declared");
        System.out.println();
        System.out.println("The colour a symbol is drawn in is not the"
                + " colour that reaches the screen: a one-pixel stroke"
                + " on a curve is antialiased across two, and both are"
                + " paler than the ink. Measured on the chip the dialog"
                + " draws, at the size it draws it - so the galaxy's"
                + " curve comes back paler than the grey it was drawn"
                + " in, while the nebula's straight edges do not.");
        System.out.println();
        System.out.println("| family | darkest pixel drawn |"
                + " contrast, as drawn |");
        System.out.println("|---|---|---:|");
        for (SymbolFamily family : FAMILIES) {
            Color darkest = darkest(swatch(family,
                    (int) SymbolChip.SYMBOL_PX, 60));
            System.out.printf(Locale.ROOT, "| %s | %s | %.2f:1 |%n",
                    family.label(), hex(darkest),
                    ratio(darkest, Color.WHITE));
        }
        System.out.println();
    }

    /** The darkest pixel a swatch actually put on the paper. */
    private static Color darkest(BufferedImage image) {
        int found = 0xffffff;
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                int rgb = image.getRGB(x, y) & 0xffffff;
                if ((rgb & 0xff) < (found & 0xff)) {
                    found = rgb;
                }
            }
        }
        return new Color(found);
    }

    /**
     * The nebula ink the rule requires, and exactly what changing it
     * cost. The gate costed it and assigned it; #185 paid it, rather
     * than either shipping under the threshold or quietly repainting
     * the chart inside a design gate.
     *
     * <p>Which row is the current ink is read from what the renderer
     * drew, not written here: a label saying "proposed" outlived the
     * proposal once already (PR #188 review).
     */
    private static void correction(Color nebulaInk) {
        System.out.println("### The correction, applied");
        System.out.println();
        System.out.println("| nebula grey | contrast on white |"
                + " margin over 3:1 |");
        System.out.println("|---:|---:|---:|");
        java.util.TreeSet<Integer> greys = new java.util.TreeSet<>(
                java.util.List.of(150, 148, 140, 132, 128));
        greys.add(nebulaInk.getRed());
        for (int grey : greys.descendingSet()) {
            double contrast = ratio(new Color(grey, grey, grey),
                    Color.WHITE);
            System.out.printf(Locale.ROOT,
                    "| %d%s | %.2f:1 | %+.0f%% |%n", grey,
                    grey == nebulaInk.getRed() ? " **(current)**"
                            : grey == 150 ? " (before Sprint 21)" : "",
                    contrast, 100.0 * (contrast - 3.0) / 3.0);
        }
        System.out.println();
        System.out.printf(Locale.ROOT,
                "**Grey %d** was chosen, not the 148 that merely"
                        + " crosses the line. 148 clears 3:1 by one"
                        + " part in a hundred, which a different"
                        + " rasteriser, a fractional scale factor or a"
                        + " paler antialiased edge would eat; %d clears"
                        + " it by a quarter, and stays visibly lighter"
                        + " than the 102 the other four symbols use, so"
                        + " the nebula box keeps the restraint it was"
                        + " given. `LegendContrastTest` holds the chart"
                        + " to it, and fails on either 150 or 148.%n",
                nebulaInk.getRed(), nebulaInk.getRed());
        System.out.println();
        System.out.println("The cost was measured rather than"
                + " estimated - the ink was changed, every image"
                + " regenerated, and the difference recorded - and then"
                + " paid in #185:");
        System.out.println();
        System.out.println("- `docs/reference/m31-stars.png` — **byte-"
                + "identical**. The released default page draws no"
                + " nebula box.");
        System.out.println("- `docs/studies/chart-furniture/` — **six"
                + " images changed**: Crux, Orion and Sagittarius, with"
                + " and without the magnitude key. Its"
                + " `measurements.md` did not; both greys count as"
                + " ink.");
        System.out.println("- `docs/studies/point-and-identify/` — no"
                + " change at all.");
        System.out.println();
        System.out.println("Those six images were regenerated in the"
                + " commit that changed the ink, and the reference page"
                + " was proved byte-identical.");
        System.out.println();
    }

    /** What a colour becomes when drawn at an alpha over a ground. */
    private static Color blend(Color over, Color under, float alpha) {
        return new Color(
                Math.round(over.getRed() * alpha
                        + under.getRed() * (1 - alpha)),
                Math.round(over.getGreen() * alpha
                        + under.getGreen() * (1 - alpha)),
                Math.round(over.getBlue() * alpha
                        + under.getBlue() * (1 - alpha)));
    }

    private static String hex(Color color) {
        return color == null ? "-"
                : String.format(Locale.ROOT, "#%02x%02x%02x",
                        color.getRed(), color.getGreen(), color.getBlue());
    }

    /** The WCAG 2.1 contrast ratio between two opaque colours. */
    static double ratio(Color a, Color b) {
        if (a == null || b == null) {
            return Double.NaN;
        }
        double la = luminance(a);
        double lb = luminance(b);
        return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05);
    }

    private static double luminance(Color color) {
        return 0.2126 * channel(color.getRed())
                + 0.7152 * channel(color.getGreen())
                + 0.0722 * channel(color.getBlue());
    }

    private static double channel(int value) {
        double v = value / 255.0;
        return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    }

    /**
     * That grouping types into families takes nothing away. The chart
     * draws a triplet and a lone galaxy identically; the Inspector
     * must still be able to tell a reader which one they clicked.
     */
    private static void sourceTypeSurvives(List<DeepSkyObject> pack) {
        System.out.println("## The source type survives the grouping");
        System.out.println();
        System.out.println("A family is derived from the type"
                + " (`ChartRenderer.symbolForType`); the type itself is"
                + " carried on the object and untouched. So objects"
                + " that share a symbol still differ where it matters -"
                + " in what the Inspector can say about them.");
        System.out.println();
        System.out.println("| object | source type | drawn as | the"
                + " Inspector's words |");
        System.out.println("|---|---|---|---|");
        for (DsoType type : DsoType.values()) {
            DeepSkyObject example = pack.stream()
                    .filter(dso -> dso.type() == type)
                    .min(java.util.Comparator.comparing(DeepSkyObject::id))
                    .orElse(null);
            if (example == null) {
                continue;
            }
            SymbolFamily family = SymbolFamily.of(type);
            System.out.printf(Locale.ROOT, "| %s | `%s` | %s | %s |%n",
                    example.id(), type.openNgcToken(),
                    family == null ? "nothing" : family.label(),
                    type == DsoType.OTHER ? "type not classified"
                            : readable(type));
        }
        System.out.println();
        System.out.println("The last column is"
                + " `InspectorPanel.readableType`, which reads"
                + " `dso.type()` and knows nothing about families."
                + " Four distinct source types draw the same ellipse"
                + " and the Inspector still names each of them.");
        System.out.println();
    }

    /** One family's symbol on a square of the chart's paper. */
    static BufferedImage swatch(SymbolFamily family, int sizePx, int boxPx) {
        BufferedImage image = new BufferedImage(boxPx, boxPx,
                BufferedImage.TYPE_INT_RGB);
        Graphics2D g = image.createGraphics();
        try {
            g.setColor(Color.WHITE);
            g.fillRect(0, 0, boxPx, boxPx);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
            ChartRenderer.drawLegendSymbol(g, SymbolChip.exampleType(family),
                    boxPx / 2.0, boxPx / 2.0, sizePx);
        } finally {
            g.dispose();
        }
        return image;
    }

    /** The share of inked pixels two swatches do not share. */
    static double difference(BufferedImage a, BufferedImage b) {
        int differing = 0;
        int inked = 0;
        for (int y = 0; y < a.getHeight(); y++) {
            for (int x = 0; x < a.getWidth(); x++) {
                boolean inkA = isInk(a, x, y);
                boolean inkB = isInk(b, x, y);
                if (inkA || inkB) {
                    inked++;
                    if (inkA != inkB) {
                        differing++;
                    }
                }
            }
        }
        return inked == 0 ? 0.0 : 100.0 * differing / inked;
    }

    private static boolean isInk(BufferedImage image, int x, int y) {
        return (image.getRGB(x, y) & 0xff) < 250;
    }

    /** The bounding box of everything a swatch drew. */
    static java.awt.Rectangle inkBounds(BufferedImage image) {
        int minX = image.getWidth();
        int minY = image.getHeight();
        int maxX = -1;
        int maxY = -1;
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                if (isInk(image, x, y)) {
                    minX = Math.min(minX, x);
                    minY = Math.min(minY, y);
                    maxX = Math.max(maxX, x);
                    maxY = Math.max(maxY, y);
                }
            }
        }
        return maxX < 0 ? new java.awt.Rectangle(0, 0, 0, 0)
                : new java.awt.Rectangle(minX, minY, maxX - minX + 1,
                        maxY - minY + 1);
    }

    /** The five legend rows as one strip, at two sizes, for the review. */
    private static void legendStrips() throws IOException {
        for (int size : new int[] {11, 14}) {
            int cell = 40;
            BufferedImage strip = new BufferedImage(cell * FAMILIES.size(),
                    cell, BufferedImage.TYPE_INT_RGB);
            Graphics2D g = strip.createGraphics();
            try {
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, strip.getWidth(), strip.getHeight());
                g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                        RenderingHints.VALUE_ANTIALIAS_ON);
                for (int i = 0; i < FAMILIES.size(); i++) {
                    ChartRenderer.drawLegendSymbol(g,
                            SymbolChip.exampleType(FAMILIES.get(i)),
                            cell / 2.0 + cell * i, cell / 2.0, size);
                }
            } finally {
                g.dispose();
            }
            ImageIO.write(strip, "png",
                    new File(DIR, "symbols-" + size + "px.png"));
        }
        System.out.println("## The five symbols, side by side");
        System.out.println();
        System.out.println("![the five symbols at 11 px]"
                + "(symbols-11px.png)  ");
        System.out.println("![the five symbols at 14 px]"
                + "(symbols-14px.png)");
        System.out.println();
        System.out.println("Left to right: galaxies, open clusters,"
                + " globular clusters, nebulae, planetary nebulae.");
        System.out.println();
    }

    /** The dialog mock-ups, and what inspecting them found. */
    private static void mockups() throws IOException {
        System.out.println("## The dialog mock-ups");
        System.out.println();
        System.out.println("Real Swing controls under the real"
                + " application themes, shown in a real window - so"
                + " keyboard focus is genuine focus and clipping is"
                + " genuine clipping. Production options and the"
                + " production dialog are untouched by this issue.");
        System.out.println();
        for (String line : DeepSkyVocabularyMockupMain.write()) {
            System.out.println(line);
        }
        System.out.println();
        SymbolFamily longest = FAMILIES.get(0);
        for (SymbolFamily family : FAMILIES) {
            if (family.prose().length() > longest.prose().length()) {
                longest = family;
            }
        }
        System.out.printf(Locale.ROOT,
                "The longest explanation is **%s**, at %d characters,"
                        + " and it is in every mock-up above rather"
                        + " than in one of its own: the row that wraps"
                        + " worst is the row the narrow and the"
                        + " enlarged layouts have to survive.%n%n",
                longest.label(), longest.prose().length());
        System.out.println("Why each one exists:");
        System.out.println();
        for (DeepSkyVocabularyMockupMain.Shot shot
                : DeepSkyVocabularyMockupMain.SHOTS) {
            System.out.println("- `" + shot.name() + "` — " + shot.why());
        }
        System.out.println();
        System.out.println("### Keyboard");
        System.out.println();
        for (String line : DeepSkyVocabularyMockupMain.mnemonics()) {
            System.out.println(line);
        }
        System.out.println();
        System.out.println("A mnemonic reaches only the controls on the"
                + " tab in front, which is a property of tabs rather"
                + " than of this design: pressing a family's letter"
                + " while the Stars tab shows does nothing. Tabs are"
                + " therefore reached the way tabs are reached -"
                + " Control-Page Up and Control-Page Down, or the"
                + " arrow keys once a tab has focus - and no meaning"
                + " anywhere depends on the pointer.");
        System.out.println();
    }
}
