package juranometria.tool;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.imageio.ImageIO;
import javax.swing.UIManager;

import juranometria.catalog.TiledCatalogue;
import juranometria.chart.DeepSkyObject;
import juranometria.chart.DsoType;
import juranometria.chart.SkyPosition;
import juranometria.chart.SkyRegion;
import juranometria.render.ChartRenderer;

/**
 * The deep-sky vocabulary gate's evidence (Sprint 21, issue #184):
 * what the bundled pack actually contains, which catalogue types
 * share one chart symbol, which are deliberately left undrawn, and
 * whether the chart's own symbols can teach a reader at dialog scale
 * in both application themes.
 *
 * <p>Every symbol is drawn by {@link ChartRenderer#drawLegendSymbol}
 * and every family is derived from
 * {@link ChartRenderer#symbolForType}. The study owns no vocabulary
 * of its own, so a legend cannot come to teach a symbol the chart has
 * stopped drawing.
 */
public final class DeepSkyVocabularyStudyMain {

    private DeepSkyVocabularyStudyMain() {
    }

    private static final File DIR =
            new File("docs/studies/deep-sky-vocabulary");

    /**
     * A reader-facing family: the chart symbol it is, the name a
     * reader sees, what it means, and objects they may know.
     */
    public record Family(ChartRenderer.Symbol symbol, String name,
                         char mnemonic, String description,
                         String examples) {
    }

    /**
     * The five proposed families. Each is named by <em>one</em>
     * production symbol, which is what makes the proposal checkable:
     * a family is exactly the set of catalogue types the renderer
     * already draws the same way.
     */
    public static final List<Family> FAMILIES = List.of(
            new Family(ChartRenderer.Symbol.ELLIPSE, "Galaxies", 'G',
                    "Galaxies, drawn at their catalogued size and"
                            + " orientation, including close pairs,"
                            + " triplets and groups.",
                    "M 31, M 51, NGC 3628"),
            new Family(ChartRenderer.Symbol.DOTTED_CIRCLE,
                    "Open clusters", 'O',
                    "Loose clusters of young stars in the plane of the"
                            + " Milky Way.",
                    "M 45, M 44, NGC 869"),
            new Family(ChartRenderer.Symbol.CROSSED_CIRCLE,
                    "Globular clusters", 'C',
                    "Dense, ancient balls of stars in the galactic"
                            + " halo.",
                    "M 13, M 22, NGC 5139"),
            new Family(ChartRenderer.Symbol.BOX, "Nebulae", 'u',
                    "Clouds of gas and dust: emission, reflection and"
                            + " dark nebulae, H II regions, supernova"
                            + " remnants, and clusters still wrapped in"
                            + " nebulosity.",
                    "M 42, M 1, NGC 7000"),
            new Family(ChartRenderer.Symbol.PLANETARY,
                    "Planetary nebulae", 'P',
                    "Shells thrown off by dying stars, drawn small and"
                            + " crossed so they read apart from the"
                            + " other nebulae.",
                    "M 57, M 27, NGC 7009"));

    public static void main(String[] args) throws IOException {
        DIR.mkdirs();
        System.out.println("# Deep-sky vocabulary study (issue #184)");
        System.out.println();
        System.out.println("Generated by `make deep-sky-study`. Every"
                + " count is swept from the bundled pack and every"
                + " symbol is painted by the production renderer"
                + " (`ChartRenderer.drawLegendSymbol`).");
        System.out.println();

        List<DeepSkyObject> pack = wholePack();
        census(pack);
        reconciliation(pack);
        exclusivity();
        geometry();
        distinguishability();
        contrast();
        sourceTypeSurvives(pack);
        legendStrips();
        mockups();
    }

    /** Every bundled deep-sky row, swept once, exactly as #169 does. */
    static List<DeepSkyObject> wholePack() {
        TiledCatalogue catalogue = TiledCatalogue.load();
        List<DeepSkyObject> all = new ArrayList<>();
        for (int ra = 0; ra < 360; ra += 20) {
            for (int dec = -80; dec <= 80; dec += 20) {
                all.addAll(catalogue.deepSkyObjectsIn(new SkyRegion(
                        new SkyPosition(ra, dec), 15.0)));
            }
        }
        return all.stream().distinct().toList();
    }

    /**
     * A family's visible explanation: one sentence and its examples,
     * which is also the control's accessible description, so the two
     * cannot say different things.
     */
    public static String prose(Family family) {
        return family.description() + " For example: "
                + family.examples() + ".";
    }

    /** The family a type draws as, or null when it draws nothing. */
    public static Family familyOf(DsoType type) {
        ChartRenderer.Symbol symbol = ChartRenderer.symbolForType(type);
        for (Family family : FAMILIES) {
            if (family.symbol() == symbol) {
                return family;
            }
        }
        return null;
    }

    /** Every source type, counted, with the family it draws as. */
    private static void census(List<DeepSkyObject> pack) {
        Map<DsoType, Integer> counts = new EnumMap<>(DsoType.class);
        for (DsoType type : DsoType.values()) {
            counts.put(type, 0);
        }
        for (DeepSkyObject dso : pack) {
            counts.merge(dso.type(), 1, Integer::sum);
        }

        System.out.println("## Every source type in the bundled pack");
        System.out.println();
        System.out.printf(Locale.ROOT,
                "**%,d** deep-sky rows, every one of them counted"
                        + " below.%n%n", pack.size());
        System.out.println("| OpenNGC token | source type | rows |"
                + " chart symbol | reader-facing family |");
        System.out.println("|---|---|---:|---|---|");
        for (DsoType type : DsoType.values()) {
            Family family = familyOf(type);
            System.out.printf(Locale.ROOT, "| `%s` | %s | %,d | %s | %s |%n",
                    type.openNgcToken(), readable(type), counts.get(type),
                    ChartRenderer.symbolForType(type)
                            .name().toLowerCase(Locale.ROOT)
                            .replace('_', ' '),
                    family == null ? "**none — deliberately undrawn**"
                            : family.name());
        }
        System.out.println();
        System.out.println("`Other` is OpenNGC's own word for a row it"
                + " could not classify, not a token the atlas failed to"
                + " map: an unrecognised token stops the pack build"
                + " (`DsoType.fromOpenNgcToken`), so there is no such"
                + " thing here as a silently missing classification.");
        System.out.println();
    }

    private static String readable(DsoType type) {
        return type.name().toLowerCase(Locale.ROOT).replace('_', ' ');
    }

    /** The totals, made to reconcile exactly rather than by percentage. */
    private static void reconciliation(List<DeepSkyObject> pack) {
        Map<String, Integer> rows = new LinkedHashMap<>();
        Map<String, Integer> types = new LinkedHashMap<>();
        for (Family family : FAMILIES) {
            rows.put(family.name(), 0);
            types.put(family.name(), 0);
        }
        int undrawn = 0;
        int undrawnTypes = 0;
        for (DeepSkyObject dso : pack) {
            Family family = familyOf(dso.type());
            if (family == null) {
                undrawn++;
            } else {
                rows.merge(family.name(), 1, Integer::sum);
            }
        }
        for (DsoType type : DsoType.values()) {
            Family family = familyOf(type);
            if (family == null) {
                undrawnTypes++;
            } else {
                types.merge(family.name(), 1, Integer::sum);
            }
        }

        System.out.println("## The five families, and what is left over");
        System.out.println();
        System.out.println("| family | source types | rows |");
        System.out.println("|---|---:|---:|");
        int drawable = 0;
        int drawableTypes = 0;
        for (Family family : FAMILIES) {
            System.out.printf(Locale.ROOT, "| %s | %d | %,d |%n",
                    family.name(), types.get(family.name()),
                    rows.get(family.name()));
            drawable += rows.get(family.name());
            drawableTypes += types.get(family.name());
        }
        System.out.printf(Locale.ROOT,
                "| **drawable** | **%d** | **%,d** |%n",
                drawableTypes, drawable);
        System.out.printf(Locale.ROOT,
                "| deliberately undrawn | %d | %,d |%n",
                undrawnTypes, undrawn);
        System.out.printf(Locale.ROOT,
                "| **the whole pack** | **%d** | **%,d** |%n",
                drawableTypes + undrawnTypes, drawable + undrawn);
        System.out.println();
        System.out.printf(Locale.ROOT,
                "%,d drawable + %,d undrawn = %,d, and the sweep loaded"
                        + " %,d rows: the totals reconcile exactly, not"
                        + " within a band.%n%n",
                drawable, undrawn, drawable + undrawn, pack.size());
        if (drawable + undrawn != pack.size()) {
            throw new IllegalStateException("totals do not reconcile");
        }
    }

    /** That every drawable type has exactly one family, and no more. */
    private static void exclusivity() {
        System.out.println("## Exactly one family per drawable type");
        System.out.println();
        System.out.println("A family is defined as one production"
                + " symbol, so the mapping is a function by"
                + " construction. What could still go wrong is two"
                + " families claiming one symbol, or a symbol the"
                + " renderer draws that no family names - a type that"
                + " would appear on the chart with no control and no"
                + " explanation. Both are checked here and again in"
                + " `DeepSkyVocabularyTest`.");
        System.out.println();
        System.out.println("| chart symbol | families naming it |"
                + " source types drawn with it |");
        System.out.println("|---|---:|---|");
        for (ChartRenderer.Symbol symbol : ChartRenderer.Symbol.values()) {
            List<String> claiming = new ArrayList<>();
            for (Family family : FAMILIES) {
                if (family.symbol() == symbol) {
                    claiming.add(family.name());
                }
            }
            List<String> drawn = new ArrayList<>();
            for (DsoType type : DsoType.values()) {
                if (ChartRenderer.symbolForType(type) == symbol) {
                    drawn.add(type.openNgcToken());
                }
            }
            System.out.printf(Locale.ROOT, "| %s | %d%s | %s |%n",
                    symbol.name().toLowerCase(Locale.ROOT)
                            .replace('_', ' '),
                    claiming.size(),
                    claiming.isEmpty() ? "" : " (" + String.join(", ",
                            claiming) + ")",
                    String.join(", ", drawn));
            int expected = symbol == ChartRenderer.Symbol.NONE ? 0 : 1;
            if (claiming.size() != expected) {
                throw new IllegalStateException(
                        symbol + " is named by " + claiming.size()
                                + " families");
            }
        }
        System.out.println();
    }

    /**
     * What a symbol actually occupies at legend sizes. This is not
     * decoration: the planetary nebula's spokes reach well past its
     * nominal size, and small sizes hit the renderer's practical
     * minimum, so a row that reserved exactly the nominal box would
     * clip the chart's own drawing.
     */
    private static void geometry() {
        System.out.println("## What each symbol occupies at legend sizes");
        System.out.println();
        System.out.println("Measured from the drawn pixels, not from the"
                + " size asked for. `size` is the larger axis passed to"
                + " `drawLegendSymbol`.");
        System.out.println();
        System.out.print("| size |");
        for (Family family : FAMILIES) {
            System.out.printf(" %s |", family.name());
        }
        System.out.println();
        System.out.print("|---:|");
        for (int i = 0; i < FAMILIES.size(); i++) {
            System.out.print("---|");
        }
        System.out.println();
        for (int size : SIZES) {
            System.out.printf("| %d px |", size);
            for (Family family : FAMILIES) {
                java.awt.Rectangle ink = inkBounds(swatch(family, size, 60));
                System.out.printf(Locale.ROOT, " %dx%d px |",
                        ink.width, ink.height);
            }
            System.out.println();
        }
        System.out.println();
        System.out.println("**The planetary nebula is the exception**,"
                + " and it is the renderer's own doing: its four spokes"
                + " reach 1.7 times its nominal radius, so it draws"
                + " almost twice the box every other family draws. A"
                + " legend row that reserved the size it asked for"
                + " would clip the chart's own symbol. The other four"
                + " overrun the asked-for size by a pixel, which is the"
                + " one-pixel outline stroke.");
        System.out.println();
        int widest = 0;
        for (Family family : FAMILIES) {
            java.awt.Rectangle ink = inkBounds(swatch(family,
                    (int) DeepSkyVocabularyMockupMain.SYMBOL_PX, 60));
            widest = Math.max(widest, Math.max(ink.width, ink.height));
        }
        System.out.printf(Locale.ROOT,
                "The mock-up draws its symbols at %.0f px on a %d px"
                        + " chip. The widest ink at that size is %d px"
                        + " (the planetary nebula), so the chip holds"
                        + " every family with %d px to spare.%n%n",
                DeepSkyVocabularyMockupMain.SYMBOL_PX,
                DeepSkyVocabularyMockupMain.CHIP_PX, widest,
                DeepSkyVocabularyMockupMain.CHIP_PX - widest);
        if (widest > DeepSkyVocabularyMockupMain.CHIP_PX) {
            throw new IllegalStateException(
                    "the chip clips the chart's own symbol");
        }
    }

    private static final int[] SIZES = {9, 11, 14, 18, 24};

    /** Whether the five symbols stay apart at the sizes a row gives. */
    private static void distinguishability() {
        System.out.println("## Do the five symbols read apart?");
        System.out.println();
        System.out.println("Each family is drawn at a size and compared"
                + " pixel by pixel against every other: the share of"
                + " inked pixels the two do **not** share, taken"
                + " against the family it resembles most. Two families"
                + " drawing the same shape would score 0%.");
        System.out.println();
        System.out.print("| size |");
        for (Family family : FAMILIES) {
            System.out.printf(" %s |", family.name());
        }
        System.out.println(" nearest pair |");
        System.out.print("|---:|");
        for (int i = 0; i <= FAMILIES.size(); i++) {
            System.out.print("---:|");
        }
        System.out.println();
        for (int size : SIZES) {
            List<BufferedImage> drawn = new ArrayList<>();
            for (Family family : FAMILIES) {
                drawn.add(swatch(family, size, 60));
            }
            System.out.printf("| %d px |", size);
            double worst = 100.0;
            String worstPair = "";
            for (int i = 0; i < FAMILIES.size(); i++) {
                double nearest = 100.0;
                for (int j = 0; j < FAMILIES.size(); j++) {
                    if (i == j) {
                        continue;
                    }
                    double difference =
                            difference(drawn.get(i), drawn.get(j));
                    if (difference < nearest) {
                        nearest = difference;
                    }
                    if (difference < worst) {
                        worst = difference;
                        worstPair = FAMILIES.get(i).name() + " / "
                                + FAMILIES.get(j).name();
                    }
                }
                System.out.printf(Locale.ROOT, " %.0f%% |", nearest);
            }
            System.out.printf(Locale.ROOT, " %.0f%% (%s) |%n", worst,
                    worstPair);
        }
        System.out.println();
    }

    /**
     * The contrast question the dark theme forces. Chart ink is
     * mid-grey on white and never follows the application theme, so a
     * symbol painted straight onto a dark dialog is nearly invisible.
     */
    private static void contrast() {
        System.out.println("## The chart's ink on a dialog's ground");
        System.out.println();
        System.out.println("WCAG contrast ratios for the chart's own"
                + " ink. **Direct** paints the symbol onto the"
                + " dialog's panel colour. **On paper** paints it onto"
                + " a scrap of the chart's own white paper, which is"
                + " what the mock-up does. **Faded** is the same chip"
                + " at 45% while its family is switched off - the"
                + " treatment this gate rejects. 3:1 is the WCAG floor"
                + " for a graphical object.");
        System.out.println();
        System.out.println("| theme | panel | ink | direct | on paper |"
                + " faded to 45% |");
        System.out.println("|---|---|---|---:|---:|---:|");
        Color[] inks = {new Color(102, 102, 102), new Color(150, 150, 150)};
        String[] inkNames = {"outline grey 102 (all but nebulae)",
                "nebula grey 150"};
        float alpha = DeepSkyVocabularyMockupMain.REJECTED_DISABLED_ALPHA;
        // Kept so the conclusions below quote the figures this run
        // actually measured, rather than figures typed beside them.
        double darkDirect = 0.0;
        double onPaper = 0.0;
        double nebulaOnPaper = 0.0;
        double fadedOutline = 0.0;
        double fadedNebula = 0.0;
        for (boolean dark : new boolean[] {false, true}) {
            DeepSkyVocabularyMockupMain.theme(dark, 1.0);
            Color panel = UIManager.getColor("Panel.background");
            for (int i = 0; i < inks.length; i++) {
                double direct = ratio(inks[i], panel);
                double paper = ratio(inks[i], Color.WHITE);
                double faded = ratio(blend(inks[i], panel, alpha),
                        blend(Color.WHITE, panel, alpha));
                System.out.printf(Locale.ROOT,
                        "| %s | %s | %s | %.2f:1 | %.2f:1 | %.2f:1 |%n",
                        dark ? "dark" : "light", hex(panel), inkNames[i],
                        direct, paper, faded);
                if (dark && i == 0) {
                    darkDirect = direct;
                    onPaper = paper;
                }
                if (!dark && i == 0) {
                    fadedOutline = faded;
                }
                if (!dark && i == 1) {
                    nebulaOnPaper = paper;
                    fadedNebula = faded;
                }
            }
        }
        System.out.println();
        System.out.println("Three things follow, and only the third is"
                + " a choice this gate is free to make:");
        System.out.println();
        System.out.printf(Locale.ROOT,
                "1. **The symbol must sit on paper.** In the dark theme"
                        + " the chart's outline grey scores %.2f:1"
                        + " straight onto the panel - invisible - and"
                        + " %.2f:1 on the chart's own white. The chip"
                        + " is not decoration; it is the only way a"
                        + " dark dialog can show the chart's ink at"
                        + " all.%n", darkDirect, onPaper);
        System.out.printf(Locale.ROOT,
                "2. **The nebula box is the chart's weakest mark**, at"
                        + " %.2f:1 even on paper. That is the chart's"
                        + " existing palette, not the legend's: the"
                        + " legend shows what the page draws, and"
                        + " changing the chart's ink would change the"
                        + " released rendering. It is recorded as a"
                        + " residual risk rather than quietly"
                        + " corrected in the legend.%n", nebulaOnPaper);
        System.out.printf(Locale.ROOT,
                "3. **A switched-off family does not fade its symbol.**"
                        + " Fading the chip to %.0f%% drops it to"
                        + " %.2f:1 and %.2f:1 - below the floor, in the"
                        + " very state where a reader consults the"
                        + " legend to decide what to switch back on."
                        + " The checkbox and its text take the"
                        + " platform's disabled styling; the symbol"
                        + " stays fully drawn, because it is"
                        + " information rather than a control.%n",
                alpha * 100.0, fadedOutline, fadedNebula);
        System.out.println();
    }

    /** What a colour becomes when drawn at an alpha over a ground. */
    private static Color blend(Color over, Color under, float alpha) {
        return new Color(
                Math.round(over.getRed() * alpha
                        + under.getRed() * (1 - alpha)),
                Math.round(over.getGreen() * alpha
                        + under.getGreen() * (1 - alpha)),
                Math.round(over.getBlue() * alpha
                        + under.getBlue() * (1 - alpha)));
    }

    private static String hex(Color color) {
        return color == null ? "-"
                : String.format(Locale.ROOT, "#%02x%02x%02x",
                        color.getRed(), color.getGreen(), color.getBlue());
    }

    /** The WCAG 2.1 contrast ratio between two opaque colours. */
    static double ratio(Color a, Color b) {
        if (a == null || b == null) {
            return Double.NaN;
        }
        double la = luminance(a);
        double lb = luminance(b);
        return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05);
    }

    private static double luminance(Color color) {
        return 0.2126 * channel(color.getRed())
                + 0.7152 * channel(color.getGreen())
                + 0.0722 * channel(color.getBlue());
    }

    private static double channel(int value) {
        double v = value / 255.0;
        return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    }

    /**
     * That grouping types into families takes nothing away. The chart
     * draws a triplet and a lone galaxy identically; the Inspector
     * must still be able to tell a reader which one they clicked.
     */
    private static void sourceTypeSurvives(List<DeepSkyObject> pack) {
        System.out.println("## The source type survives the grouping");
        System.out.println();
        System.out.println("A family is derived from the type"
                + " (`ChartRenderer.symbolForType`); the type itself is"
                + " carried on the object and untouched. So objects"
                + " that share a symbol still differ where it matters -"
                + " in what the Inspector can say about them.");
        System.out.println();
        System.out.println("| object | source type | drawn as | the"
                + " Inspector's words |");
        System.out.println("|---|---|---|---|");
        for (DsoType type : DsoType.values()) {
            DeepSkyObject example = pack.stream()
                    .filter(dso -> dso.type() == type)
                    .min(java.util.Comparator.comparing(DeepSkyObject::id))
                    .orElse(null);
            if (example == null) {
                continue;
            }
            Family family = familyOf(type);
            System.out.printf(Locale.ROOT, "| %s | `%s` | %s | %s |%n",
                    example.id(), type.openNgcToken(),
                    family == null ? "nothing" : family.name(),
                    type == DsoType.OTHER ? "type not classified"
                            : readable(type));
        }
        System.out.println();
        System.out.println("The last column is"
                + " `InspectorPanel.readableType`, which reads"
                + " `dso.type()` and knows nothing about families."
                + " Four distinct source types draw the same ellipse"
                + " and the Inspector still names each of them.");
        System.out.println();
    }

    /** One family's symbol on a square of the chart's paper. */
    static BufferedImage swatch(Family family, int sizePx, int boxPx) {
        BufferedImage image = new BufferedImage(boxPx, boxPx,
                BufferedImage.TYPE_INT_RGB);
        Graphics2D g = image.createGraphics();
        try {
            g.setColor(Color.WHITE);
            g.fillRect(0, 0, boxPx, boxPx);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
            ChartRenderer.drawLegendSymbol(g, typeFor(family),
                    boxPx / 2.0, boxPx / 2.0, sizePx);
        } finally {
            g.dispose();
        }
        return image;
    }

    /** A catalogue type that draws this family's symbol. */
    public static DsoType typeFor(Family family) {
        for (DsoType type : DsoType.values()) {
            if (ChartRenderer.symbolForType(type) == family.symbol()) {
                return type;
            }
        }
        throw new IllegalStateException("no type draws " + family.symbol());
    }

    /** The share of inked pixels two swatches do not share. */
    static double difference(BufferedImage a, BufferedImage b) {
        int differing = 0;
        int inked = 0;
        for (int y = 0; y < a.getHeight(); y++) {
            for (int x = 0; x < a.getWidth(); x++) {
                boolean inkA = isInk(a, x, y);
                boolean inkB = isInk(b, x, y);
                if (inkA || inkB) {
                    inked++;
                    if (inkA != inkB) {
                        differing++;
                    }
                }
            }
        }
        return inked == 0 ? 0.0 : 100.0 * differing / inked;
    }

    private static boolean isInk(BufferedImage image, int x, int y) {
        return (image.getRGB(x, y) & 0xff) < 250;
    }

    /** The bounding box of everything a swatch drew. */
    static java.awt.Rectangle inkBounds(BufferedImage image) {
        int minX = image.getWidth();
        int minY = image.getHeight();
        int maxX = -1;
        int maxY = -1;
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                if (isInk(image, x, y)) {
                    minX = Math.min(minX, x);
                    minY = Math.min(minY, y);
                    maxX = Math.max(maxX, x);
                    maxY = Math.max(maxY, y);
                }
            }
        }
        return maxX < 0 ? new java.awt.Rectangle(0, 0, 0, 0)
                : new java.awt.Rectangle(minX, minY, maxX - minX + 1,
                        maxY - minY + 1);
    }

    /** The five legend rows as one strip, at two sizes, for the review. */
    private static void legendStrips() throws IOException {
        for (int size : new int[] {11, 14}) {
            int cell = 40;
            BufferedImage strip = new BufferedImage(cell * FAMILIES.size(),
                    cell, BufferedImage.TYPE_INT_RGB);
            Graphics2D g = strip.createGraphics();
            try {
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, strip.getWidth(), strip.getHeight());
                g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                        RenderingHints.VALUE_ANTIALIAS_ON);
                for (int i = 0; i < FAMILIES.size(); i++) {
                    ChartRenderer.drawLegendSymbol(g,
                            typeFor(FAMILIES.get(i)),
                            cell / 2.0 + cell * i, cell / 2.0, size);
                }
            } finally {
                g.dispose();
            }
            ImageIO.write(strip, "png",
                    new File(DIR, "symbols-" + size + "px.png"));
        }
        System.out.println("## The five symbols, side by side");
        System.out.println();
        System.out.println("![the five symbols at 11 px]"
                + "(symbols-11px.png)  ");
        System.out.println("![the five symbols at 14 px]"
                + "(symbols-14px.png)");
        System.out.println();
        System.out.println("Left to right: galaxies, open clusters,"
                + " globular clusters, nebulae, planetary nebulae.");
        System.out.println();
    }

    /** The dialog mock-ups, and what inspecting them found. */
    private static void mockups() throws IOException {
        System.out.println("## The dialog mock-ups");
        System.out.println();
        System.out.println("Real Swing controls under the real"
                + " application themes, shown in a real window - so"
                + " keyboard focus is genuine focus and clipping is"
                + " genuine clipping. Production options and the"
                + " production dialog are untouched by this issue.");
        System.out.println();
        for (String line : DeepSkyVocabularyMockupMain.write()) {
            System.out.println(line);
        }
        System.out.println();
        Family longest = FAMILIES.get(0);
        for (Family family : FAMILIES) {
            if (prose(family).length() > prose(longest).length()) {
                longest = family;
            }
        }
        System.out.printf(Locale.ROOT,
                "The longest explanation is **%s**, at %d characters,"
                        + " and it is in every mock-up above rather"
                        + " than in one of its own: the row that wraps"
                        + " worst is the row the narrow and the"
                        + " enlarged layouts have to survive.%n%n",
                longest.name(), prose(longest).length());
        System.out.println("Why each one exists:");
        System.out.println();
        for (DeepSkyVocabularyMockupMain.Shot shot
                : DeepSkyVocabularyMockupMain.SHOTS) {
            System.out.println("- `" + shot.name() + "` — " + shot.why());
        }
        System.out.println();
        System.out.println("### Keyboard");
        System.out.println();
        for (String line : DeepSkyVocabularyMockupMain.mnemonics()) {
            System.out.println(line);
        }
        System.out.println();
        System.out.println("A mnemonic reaches only the controls on the"
                + " tab in front, which is a property of tabs rather"
                + " than of this design: pressing a family's letter"
                + " while the Stars tab shows does nothing. Tabs are"
                + " therefore reached the way tabs are reached -"
                + " Control-Page Up and Control-Page Down, or the"
                + " arrow keys once a tab has focus - and no meaning"
                + " anywhere depends on the pointer.");
        System.out.println();
    }
}
