package juranometria.tool;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import juranometria.chart.SkyPosition;
import juranometria.sky.GreatCircle;
import juranometria.sky.SkyFrame;

/**
 * The reproducible measurements behind the ecliptic gate (Sprint 28,
 * issue #271): which ecliptic belongs on a fixed J2000 chart, proved
 * with numbers rather than asserted.
 *
 * <p>Pure astronomy, deterministic on every platform: no fonts, no
 * rendering, no clock, no locale-dependent output. The rendered
 * study pages are produced separately; this is the arithmetic the
 * decision stands on, regenerated byte-for-byte by the evidence
 * contracts.
 */
public final class EclipticStudyMain {

    private EclipticStudyMain() {
    }

    /** The J2000 mean obliquity, from the atlas's own model. */
    private static final double EPS0 = SkyFrame.meanObliquityDegrees(0.0);

    /** The fixed mean ecliptic of J2000, as a great circle. */
    private static final SkyPosition ECLIPTIC_POLE =
            new SkyPosition(270.0, 90.0 - EPS0);

    private static final String[] DATES = {
        "1900-01-01T00:00:00Z", "2000-01-01T12:00:00Z",
        "2026-03-20T21:33:00Z", "2050-07-04T03:00:00Z",
        "2100-01-01T00:00:00Z",
    };

    public static void main(String[] args) throws Exception {
        p("# Which ecliptic belongs on a fixed J2000 chart");
        p("");
        p("Measured by `make ecliptic-study`. Reproduced byte-for-byte"
                + " by the evidence contracts. Pure astronomy: no"
                + " fonts, rendering, clock, or locale in these"
                + " numbers.");
        p("");

        frame();
        landmarks();
        twoMotions();
        againstSofa();
        pixelScale();
    }

    /** The chosen frame and its defining constant. */
    private static void frame() {
        p("## The frame");
        p("");
        p("The chart is ICRS/J2000, so the reference circle is the"
                + " **mean ecliptic of J2000**: a permanent great"
                + " circle, not a line that drifts with the date.");
        p("");
        p(String.format(Locale.ROOT,
                "- J2000 mean obliquity ε₀ = **%.7f°** (%.3f″)",
                EPS0, EPS0 * 3600.0));
        p(String.format(Locale.ROOT,
                "- Ecliptic north pole: RA %.4f°, Dec %+.5f°"
                        + " — exactly ε₀ from the celestial pole"
                        + " (measured %.5f°)",
                ECLIPTIC_POLE.raDegrees(), ECLIPTIC_POLE.decDegrees(),
                ECLIPTIC_POLE.separationDegrees(new SkyPosition(0, 90))));
        p("");
    }

    /** The four cardinal landmarks, each exactly on the circle. */
    private static void landmarks() {
        GreatCircle ecliptic = new GreatCircle(ECLIPTIC_POLE);
        p("## The cardinal landmarks");
        p("");
        p("Fixed points, named in the interface (issue #271 chose"
                + " named marks). Each lies on the circle to machine"
                + " precision.");
        p("");
        p("| landmark | RA | Dec | off-circle |");
        p("|---|---:|---:|---:|");
        landmark(ecliptic, "Vernal equinox", 0.0, 0.0);
        landmark(ecliptic, "Summer solstice", 90.0, EPS0);
        landmark(ecliptic, "Autumnal equinox", 180.0, 0.0);
        landmark(ecliptic, "Winter solstice", 270.0, -EPS0);
        p("");
        p("The vernal equinox falls at exactly RA 0h, Dec 0° — right"
                + " ascension is measured from it, so on a J2000 chart"
                + " the ecliptic crosses the equator at the RA origin"
                + " by definition.");
        p("");
    }

    private static void landmark(GreatCircle circle, String name,
                                 double ra, double dec) {
        SkyPosition at = new SkyPosition(ra, dec);
        double off = Math.abs(90.0 - ECLIPTIC_POLE.separationDegrees(at));
        p(String.format(Locale.ROOT, "| %s | %.3f° | %+.4f° | %.1e° |",
                name, ra, dec, off));
    }

    /**
     * The heart of the gate: the circle is nearly timeless, the
     * equinox is where precession lives.
     */
    private static void twoMotions() {
        p("## Two motions of very different size");
        p("");
        p("An of-date ecliptic and the fixed J2000 ecliptic differ in"
                + " two ways, and the sizes are what settle the"
                + " decision:");
        p("");
        p("- the **circle** (the plane) barely moves — the of-date"
                + " ecliptic pole, transformed into J2000, sits a"
                + " fraction of an arcminute from the J2000 pole;");
        p("- the **equinox** slides ~50″/yr *along* the circle — the"
                + " of-date vernal equinox, correctly transformed into"
                + " J2000, drifts degrees from (0h, 0°).");
        p("");
        p("| date | ε(t) | circle: pole shift | equinox: drift from (0h,0°) |");
        p("|---|---:|---:|---:|");
        for (String iso : DATES) {
            double jd = SkyFrame.julianDate(Instant.parse(iso));
            double t = SkyFrame.centuries(jd);
            double epsT = SkyFrame.meanObliquityDegrees(t);
            SkyPosition poleShift = SkyFrame.toJ2000(
                    new SkyPosition(270.0, 90.0 - epsT), jd);
            double circle = poleShift.separationDegrees(ECLIPTIC_POLE);
            SkyPosition equinox = SkyFrame.toJ2000(
                    new SkyPosition(0.0, 0.0), jd);
            double drift = equinox.separationDegrees(new SkyPosition(0, 0));
            p(String.format(Locale.ROOT,
                    "| %s | %.5f° | %.2f′ | %.3f° |",
                    iso.substring(0, 10), epsT, circle * 60.0, drift));
        }
        p("");
        p("So a naive of-date *line* would look almost right — under an"
                + " arcminute — and only the **equinox landmark**"
                + " betrays a wrong frame. That is why a fixed atlas"
                + " anchors both the circle and its landmarks to J2000,"
                + " and why the gate insists on landmark checks at"
                + " dates far from J2000 rather than the line alone.");
        p("");
    }

    /** The model held to the SOFA oracle checked in beside this. */
    private static void againstSofa() throws Exception {
        p("## Agreement with the SOFA oracle");
        p("");
        p("`docs/studies/ecliptic/reference-vectors.txt` carries the"
                + " ICRS/J2000 equatorial direction of eight ecliptic"
                + " longitudes, computed by IAU SOFA (iauObl80,"
                + " iauEcm06). The atlas takes no dependency on SOFA;"
                + " these are an authority's numbers, checked in.");
        p("");
        double worst = 0;
        double sofaObliquity = 0;
        for (String line : Files.readAllLines(Path.of(
                "docs/studies/ecliptic/reference-vectors.txt"))) {
            if (line.startsWith("obliquity_j2000_deg")) {
                sofaObliquity = Double.parseDouble(line.split("\\s+")[1]);
            } else if (line.startsWith("ecl ")) {
                String[] f = line.split("\\s+");
                double lambda = Double.parseDouble(f[1]);
                SkyPosition mine = eclipticToEquatorial(lambda);
                SkyPosition sofa = new SkyPosition(
                        Double.parseDouble(f[3]), Double.parseDouble(f[4]));
                worst = Math.max(worst,
                        mine.separationDegrees(sofa) * 3600.0);
            }
        }
        p(String.format(Locale.ROOT,
                "- obliquity: model %.9f° vs SOFA %.9f° — agree to %.1e°",
                EPS0, sofaObliquity, Math.abs(EPS0 - sofaObliquity)));
        p(String.format(Locale.ROOT,
                "- ecliptic longitudes: worst separation **%.4f″**"
                        + " over eight directions", worst));
        p("");
        p("The residual is the ICRS-vs-mean-J2000 frame bias plus the"
                + " IAU 2006-vs-1980 obliquity difference: below a"
                + " twentieth of an arcsecond, and far below chart"
                + " scale. The implementation's tolerance is derived"
                + " from this measured residual, not copied from"
                + " production.");
        p("");
    }

    /** What these angles are worth in pixels at chart scale. */
    private static void pixelScale() {
        p("## At chart scale");
        p("");
        p("A page is 900 px wide, so a degree spans this many pixels:");
        p("");
        p("| field | px per degree | 1.4° equinox drift | 0.9′ circle shift |");
        p("|---:|---:|---:|---:|");
        for (double field : new double[] {8, 18, 36}) {
            double pxPerDeg = 900.0 / field;
            p(String.format(Locale.ROOT,
                    "| %.0f° | %.1f | %.0f px | %.1f px |",
                    field, pxPerDeg, 1.398 * pxPerDeg,
                    (0.93 / 60.0) * pxPerDeg));
        }
        p("");
        p("The equinox drift is a chart-scale distance a reader would"
                + " see; the circle shift is a fraction of a pixel."
                + " The line can be called timeless; its equinox cannot.");
    }

    /** Ecliptic (λ, β=0) to J2000 equatorial, via the mean obliquity. */
    private static SkyPosition eclipticToEquatorial(double lambdaDegrees) {
        double lambda = Math.toRadians(lambdaDegrees);
        double eps = Math.toRadians(EPS0);
        double x = Math.cos(lambda);
        double y = Math.sin(lambda) * Math.cos(eps);
        double z = Math.sin(lambda) * Math.sin(eps);
        double ra = Math.toDegrees(Math.atan2(y, x));
        double dec = Math.toDegrees(Math.asin(z));
        return new SkyPosition(ra < 0 ? ra + 360.0 : ra, dec);
    }

    private static void p(String line) {
        System.out.println(line);
    }
}
