package juranometria.tool;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import juranometria.chart.ChartViewport;
import juranometria.chart.SkyPosition;
import juranometria.project.GnomonicProjection;
import juranometria.project.PixelPoint;
import juranometria.project.ViewportMapping;
import juranometria.sky.Ecliptic;
import juranometria.sky.GreatCircle;
import juranometria.sky.SkyFrame;

/**
 * The reproducible measurements behind the ecliptic gate (Sprint 28,
 * issue #271): which ecliptic belongs on a fixed J2000 chart, proved
 * with numbers rather than asserted.
 *
 * <p>Pure astronomy, deterministic on every platform: no fonts, no
 * rendering, no clock, no locale-dependent output. The rendered
 * study pages are produced separately; this is the arithmetic the
 * decision stands on, regenerated byte-for-byte by the evidence
 * contracts.
 */
public final class EclipticStudyMain {

    private EclipticStudyMain() {
    }

    // The production model (#272), not a second copy of it: the
    // study measures what the atlas will draw, and one
    // transformation in the tree cannot disagree with itself.
    private static final double EPS0 = Ecliptic.OBLIQUITY_DEGREES;
    private static final SkyPosition ECLIPTIC_POLE = Ecliptic.POLE;

    /** The fields the rendered study pages use. */
    private static final double[] FIELDS = {8.0, 18.0, 36.0};

    /** A page is 900x700, as every rendered study page is. */
    private static final int PAGE_WIDTH = 900;
    private static final int PAGE_HEIGHT = 700;

    /**
     * The rival candidate at one date, as SOFA gives it: the
     * <em>mean</em> ecliptic and equinox of date, already expressed in
     * ICRS/J2000.
     */
    private record OfDate(String iso, double obliquity, SkyPosition pole,
                          SkyPosition equinox) {
    }

    public static void main(String[] args) throws Exception {
        p("# Which ecliptic belongs on a fixed J2000 chart");
        p("");
        p("Measured by `make ecliptic-study`. Reproduced byte-for-byte"
                + " by the evidence contracts. Pure astronomy: no"
                + " fonts, rendering, clock, or locale in these"
                + " numbers.");
        p("");

        frame();
        landmarks();
        twoMotions();
        againstSofa();
        pixelScale();
    }

    /** The chosen frame and its defining constant. */
    private static void frame() {
        p("## The frame");
        p("");
        p("The chart is ICRS/J2000, so the reference circle is the"
                + " **mean ecliptic of J2000**: a permanent great"
                + " circle, not a line that drifts with the date.");
        p("");
        p(String.format(Locale.ROOT,
                "- J2000 mean obliquity ε₀ = **%.7f°** (%.3f″)",
                EPS0, EPS0 * 3600.0));
        p(String.format(Locale.ROOT,
                "- Ecliptic north pole: RA %.4f°, Dec %+.5f°"
                        + " — exactly ε₀ from the celestial pole"
                        + " (measured %.5f°)",
                ECLIPTIC_POLE.raDegrees(), ECLIPTIC_POLE.decDegrees(),
                ECLIPTIC_POLE.separationDegrees(new SkyPosition(0, 90))));
        p("");
    }

    /** The four cardinal landmarks, each exactly on the circle. */
    private static void landmarks() {
        GreatCircle ecliptic = Ecliptic.circle();
        p("## The cardinal landmarks");
        p("");
        p("Fixed points, named in the interface (issue #271 chose"
                + " named marks). Each lies on the circle to machine"
                + " precision.");
        p("");
        p("**Named by month, not by season.** \"Summer solstice\""
                + " reverses for a southern reader, and \"vernal\""
                + " carries the same northern assumption, while this"
                + " geometry has no observer at all (PR #276 review)."
                + " The month names are true everywhere.");
        p("");
        p("| landmark | RA | Dec | off-circle |");
        p("|---|---:|---:|---:|");
        for (Ecliptic.Landmark each : Ecliptic.landmarks()) {
            landmark(each);
        }
        p("");
        p("The March equinox falls at exactly RA 0h, Dec 0° — right"
                + " ascension is measured from it, so on a J2000 chart"
                + " the ecliptic crosses the equator at the RA origin"
                + " by definition.");
        p("");
    }

    private static void landmark(Ecliptic.Landmark landmark) {
        SkyPosition at = landmark.at();
        double off = Math.abs(Ecliptic.latitudeDegrees(at));
        p(String.format(Locale.ROOT, "| %s | %.3f° | %+.4f° | %.1e° |",
                landmark.name(), at.raDegrees(), at.decDegrees(), off));
    }

    /**
     * The heart of the gate: the circle is nearly timeless, the
     * equinox is where precession lives.
     */
    private static void twoMotions() throws Exception {
        p("## Two motions of very different size");
        p("");
        p("The two candidates are the **mean ecliptic and equinox of"
                + " J2000** and the **mean ecliptic and equinox of"
                + " date**. Both are *mean*: no nutation is applied to"
                + " either, because nutation belongs to neither"
                + " candidate.");
        p("");
        p("**Both come from SOFA, not from the atlas.** An earlier"
                + " draft built the of-date pole and equinox in mean"
                + " coordinates and passed them to `SkyFrame.toJ2000`,"
                + " whose input is a *true* direction and which"
                + " therefore removes a nutation that was never there"
                + " (PR #276 review). That added a rotation belonging"
                + " to neither candidate, and measured the comparison"
                + " with production's own transformation rather than"
                + " with the independent authority. Both candidates are"
                + " now read from"
                + " `docs/studies/ecliptic/reference-vectors.txt`,"
                + " where SOFA's `iauEcm06` supplies each date's"
                + " ecliptic frame directly in ICRS.");
        p("");
        p("They differ in two ways, and the sizes are what settle the"
                + " decision:");
        p("");
        p("- the **circle** (the plane) moves very little — the"
                + " of-date ecliptic pole stays under an arcminute from"
                + " the J2000 pole across two centuries;");
        p("- the **equinox** slides ~50″/yr *along* the circle,"
                + " drifting well over a degree.");
        p("");
        p("| date | ε(t) | circle: pole offset | equinox: offset from J2000 equinox |");
        p("|---|---:|---:|---:|");
        List<OfDate> candidates = ofDateCandidates();
        SkyPosition j2000Equinox = sofaEquinoxJ2000();
        SkyPosition j2000Pole = sofaPoleJ2000();
        for (OfDate row : candidates) {
            p(String.format(Locale.ROOT,
                    "| %s | %.5f° | %.2f′ | %.3f° |",
                    row.iso().substring(0, 10), row.obliquity(),
                    row.pole().separationDegrees(j2000Pole) * 60.0,
                    row.equinox().separationDegrees(j2000Equinox)));
        }
        p("");
        p("At J2000 itself both offsets are exactly zero — the of-date"
                + " candidate *is* the J2000 candidate there — which is"
                + " the check that the two are being read in one frame.");
        p("");
        p("**The dates are UTC, and SOFA's `iauEcm06` and `iauObl06`"
                + " take TT.** No conversion is applied. What follows"
                + " is a **sensitivity experiment**, not the"
                + " conversion: no single offset is the true one for"
                + " all five dates, because UTC did not exist in 1900"
                + " and the leap seconds after today have not been"
                + " decided (PR #276 round 3).");
        p("");
        p("| date shifted by | worst displacement | against the 0.06″ tolerance |");
        p("|---|---:|---:|");
        p(String.format(Locale.ROOT,
                "| %.3f s — today's TT−UTC | %.6f″ | %.0f× smaller |",
                SHIFT_TODAY, shiftCost(SHIFT_TODAY),
                0.06 / shiftCost(SHIFT_TODAY)));
        p(String.format(Locale.ROOT,
                "| %.0f s — an allowance over 1900–2100 | %.6f″ | %.0f× smaller |",
                SHIFT_ALLOWANCE, shiftCost(SHIFT_ALLOWANCE),
                0.06 / shiftCost(SHIFT_ALLOWANCE)));
        p("");
        p("The second row is an **allowance, not a bound**: ΔT was"
                + " near zero around 1900, is about 69 s now, and"
                + " published projections for 2100 are of order 200 s"
                + " with wide uncertainty. 300 s is chosen to sit above"
                + " all of that; no maximum beyond it is claimed, and"
                + " the atlas ships no ΔT table. Even so the"
                + " displacement stays two orders of magnitude below"
                + " the tolerance, so **no time-scale choice available"
                + " here can affect the decision**.");
        p("");
        p("So a naive of-date *line* would look nearly right, and only"
                + " the **equinox landmark** betrays a wrong frame."
                + " That is why a fixed atlas anchors both the circle"
                + " and its landmarks to J2000, and why the oracle"
                + " check is made at dates far from J2000 rather than"
                + " on the line alone.");
        p("");
    }

    /** The model held to the SOFA oracle checked in beside this. */
    private static void againstSofa() throws Exception {
        p("## Agreement with the SOFA oracle");
        p("");
        p("`docs/studies/ecliptic/reference-vectors.txt` carries the"
                + " ICRS/J2000 equatorial direction of eight ecliptic"
                + " longitudes, computed by IAU SOFA (iauObl80,"
                + " iauEcm06). The atlas takes no dependency on SOFA;"
                + " these are an authority's numbers, checked in.");
        p("");
        double worst = 0;
        double sofaObliquity = 0;
        for (String line : Files.readAllLines(Path.of(
                "docs/studies/ecliptic/reference-vectors.txt"))) {
            if (line.startsWith("obliquity_j2000_deg")) {
                sofaObliquity = Double.parseDouble(line.split("\\s+")[1]);
            } else if (line.startsWith("ecl ")) {
                String[] f = line.split("\\s+");
                double lambda = Double.parseDouble(f[1]);
                SkyPosition mine = Ecliptic.toEquatorial(lambda, 0.0);
                SkyPosition sofa = new SkyPosition(
                        Double.parseDouble(f[3]), Double.parseDouble(f[4]));
                worst = Math.max(worst,
                        mine.separationDegrees(sofa) * 3600.0);
            }
        }
        p(String.format(Locale.ROOT,
                "- obliquity: model %.9f° vs SOFA %.9f° — agree to %.1e°",
                EPS0, sofaObliquity, Math.abs(EPS0 - sofaObliquity)));
        p(String.format(Locale.ROOT,
                "- ecliptic longitudes: worst separation **%.4f″**"
                        + " over eight directions", worst));
        p("");
        p("The residual is the ICRS-vs-mean-J2000 frame bias plus the"
                + " IAU 2006-vs-1980 obliquity difference: below a"
                + " twentieth of an arcsecond, and far below chart"
                + " scale. The implementation's tolerance is derived"
                + " from this measured residual, not copied from"
                + " production.");
        p("");
    }

    /**
     * What the two offsets are worth on the paper, measured through
     * the production projection and viewport mapping.
     */
    private static void pixelScale() throws Exception {
        p("## On the paper");
        p("");
        p("Measured through the atlas's own `GnomonicProjection` and"
                + " `ViewportMapping` at the positions concerned, on"
                + " the 900x700 page every rendered study page uses."
                + " An earlier draft used a flat `900 / field`, which"
                + " is neither the gnomonic scale nor the mapping"
                + " production applies (PR #276 review).");
        p("");
        p("**Each is measured on the page where it is worst**, which"
                + " is not the same page. The two circles *cross* at"
                + " the equinoxes, so an equinox page is the one place"
                + " the lines coincide and would flatter the of-date"
                + " candidate; they are furthest apart a quarter turn"
                + " away, at the solstices. The equinox marks, of"
                + " course, are compared on the equinox page.");
        p("");
        List<OfDate> candidates = ofDateCandidates();
        SkyPosition j2000Equinox = sofaEquinoxJ2000();
        SkyPosition j2000Pole = sofaPoleJ2000();
        SkyPosition equinoxPage = new SkyPosition(0.0, 0.0);
        SkyPosition solsticePage = new SkyPosition(90.0, EPS0);

        p("| date | " + fieldHeadings("circle, June solstice page")
                + " | " + fieldHeadings("March equinox mark") + " |");
        p("|---|---:|---:|---:|---:|---:|---:|");
        for (OfDate row : candidates) {
            StringBuilder line = new StringBuilder();
            line.append("| ").append(row.iso(), 0, 10).append(" |");
            for (double field : FIELDS) {
                line.append(String.format(Locale.ROOT, " %.1f px |",
                        circlePixels(solsticePage, field, j2000Pole,
                                row.pole())));
            }
            for (double field : FIELDS) {
                line.append(String.format(Locale.ROOT, " %.0f px |",
                        pixelsApart(equinoxPage, field, j2000Equinox,
                                row.equinox())));
            }
            p(line.toString());
        }
        p("");
        p(String.format(Locale.ROOT,
                "For contrast, on the **equinox** page — where the"
                        + " circles cross — the 2100 circle offset is"
                        + " %.1f px at the 8° field, effectively"
                        + " nothing.",
                circlePixels(equinoxPage, 8.0, j2000Pole,
                        candidates.get(candidates.size() - 1).pole())));
        p("");
        p("**The circle is not identical, and the earlier draft"
                + " overstated it as \"under a pixel at every field\"**"
                + " (PR #276 review). Even at its worst page and"
                + " narrowest field the two circles are only a pixel or"
                + " so apart — small, but visible ink rather than"
                + " nothing. The equinox mark is two orders of"
                + " magnitude worse.");
        p("");
        p("That ratio, not either number alone, is the decision: a"
                + " reader could not tell the two *lines* apart, and"
                + " could not miss the two *marks* being apart. A"
                + " chart that fixed its circle to J2000 and its"
                + " landmarks to the date would look right and read"
                + " wrong.");
    }

    private static String fieldHeadings(String what) {
        StringBuilder heading = new StringBuilder();
        for (int i = 0; i < FIELDS.length; i++) {
            heading.append(String.format(Locale.ROOT, "%s %.0f°",
                    i == 0 ? what + ":" : "", FIELDS[i]));
            if (i < FIELDS.length - 1) {
                heading.append(" | ");
            }
        }
        return heading.toString();
    }

    /** Two sky positions, in pixels apart on a page of this field. */
    private static double pixelsApart(SkyPosition centre, double field,
                                      SkyPosition a, SkyPosition b) {
        ChartViewport viewport = new ChartViewport(centre, field,
                PAGE_WIDTH, PAGE_HEIGHT);
        GnomonicProjection projection = new GnomonicProjection(centre);
        ViewportMapping mapping = new ViewportMapping(viewport);
        PixelPoint first = projection.project(a).map(mapping::toPixel)
                .orElseThrow();
        PixelPoint second = projection.project(b).map(mapping::toPixel)
                .orElseThrow();
        return Math.hypot(first.x() - second.x(), first.y() - second.y());
    }

    /**
     * How far apart the two circles are on the paper, at the page
     * centre: the nearest point of each circle to the centre,
     * projected, and measured.
     */
    private static double circlePixels(SkyPosition centre, double field,
                                       SkyPosition poleA,
                                       SkyPosition poleB) {
        return pixelsApart(centre, field, nearestOnCircle(centre, poleA),
                nearestOnCircle(centre, poleB));
    }

    /** The point of the circle about {@code pole} nearest {@code to}. */
    private static SkyPosition nearestOnCircle(SkyPosition to,
                                               SkyPosition pole) {
        double[] c = SkyFrame.toVector(to);
        double[] p = SkyFrame.toVector(pole);
        double dot = c[0] * p[0] + c[1] * p[1] + c[2] * p[2];
        double[] n = {c[0] - dot * p[0], c[1] - dot * p[1],
                c[2] - dot * p[2]};
        double norm = Math.sqrt(n[0] * n[0] + n[1] * n[1] + n[2] * n[2]);
        return SkyFrame.toPosition(new double[] {n[0] / norm,
                n[1] / norm, n[2] / norm});
    }

    // ---- the oracle, read rather than recomputed --------------------

    private static final Path ORACLE =
            Path.of("docs/studies/ecliptic/reference-vectors.txt");

    /** The rival candidate at each date, as SOFA expressed it. */
    private static List<OfDate> ofDateCandidates() throws Exception {
        List<OfDate> rows = new ArrayList<>();
        for (String line : Files.readAllLines(ORACLE)) {
            if (!line.startsWith("ofdate ")) {
                continue;
            }
            String[] f = line.trim().split("\\s+");
            rows.add(new OfDate(f[1], Double.parseDouble(f[2]),
                    new SkyPosition(Double.parseDouble(f[3]),
                            Double.parseDouble(f[4])),
                    new SkyPosition(Double.parseDouble(f[5]),
                            Double.parseDouble(f[6]))));
        }
        return rows;
    }

    /** Today's TT-UTC, and an allowance over 1900-2100. */
    private static final double SHIFT_TODAY = 69.184;
    private static final double SHIFT_ALLOWANCE = 300.0;

    /** How far a date shift of this many seconds moves the axes. */
    private static double shiftCost(double seconds) throws Exception {
        for (String line : Files.readAllLines(ORACLE)) {
            if (line.startsWith("timescale_shift_arcsec")) {
                String[] f = line.trim().split("\\s+");
                if (Math.abs(Double.parseDouble(f[1]) - seconds) < 1e-6) {
                    return Double.parseDouble(f[2]);
                }
            }
        }
        throw new IllegalStateException(
                "the oracle records no shift of " + seconds + " s");
    }

    /** SOFA's own J2000 ecliptic pole, in ICRS. */
    private static SkyPosition sofaPoleJ2000() throws Exception {
        for (String line : Files.readAllLines(ORACLE)) {
            if (line.startsWith("eclpole ")) {
                String[] f = line.trim().split("\\s+");
                return new SkyPosition(Double.parseDouble(f[1]),
                        Double.parseDouble(f[2]));
            }
        }
        throw new IllegalStateException("the oracle records no pole");
    }

    /** SOFA's own J2000 equinox (λ=0), in ICRS. */
    private static SkyPosition sofaEquinoxJ2000() throws Exception {
        for (String line : Files.readAllLines(ORACLE)) {
            if (line.startsWith("ecl 0.0000 ")) {
                String[] f = line.trim().split("\\s+");
                return new SkyPosition(Double.parseDouble(f[3]),
                        Double.parseDouble(f[4]));
            }
        }
        throw new IllegalStateException("the oracle records no equinox");
    }

    private static void p(String line) {
        System.out.println(line);
    }
}
