package juranometria.tool;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Stream;

/**
 * Regenerates the generated evidence and holds every artifact to its
 * own contract (Sprint 26, issue #242).
 *
 * <p>The classes and their contracts are the gate's
 * ({@code docs/decisions/test-evidence.md}); this makes them
 * executable. A clean run reports, per artifact, one of four
 * verdicts and exits nonzero if any contract is breached:
 *
 * <ul>
 *   <li><strong>reproduced</strong> - deterministic reports and
 *       renderer-drawn images regenerated byte-for-byte;</li>
 *   <li><strong>structurally-verified</strong> - held by the
 *       in-suite structural checks rather than by bytes;</li>
 *   <li><strong>inspection-imagery</strong> - widget-rendered
 *       artifacts whose regenerated bytes drifted are <em>restored
 *       from the committed snapshot</em> and reported for a human
 *       eye, never silently churned and never claimed inspected by
 *       a command that has no eyes (review);</li>
 *   <li><strong>deliberately-unchanged</strong> - byte-exact
 *       fixtures (checksum-verified) and session photographs, whose
 *       generator needs a display and is not run here at all;</li>
 *   <li><strong>checksum-verified (captured evidence)</strong> -
 *       operating-system screenshots (issue #245), digest-pinned:
 *       no command regenerates a desktop's Finder or Dock, so a
 *       change or an unpinned newcomer is a breach by name.</li>
 * </ul>
 *
 * <p>The whole committed tree under docs/studies is snapshotted -
 * bytes and modification times - before anything runs, so
 * restoration needs no git, a generator that dies cannot leave
 * drift behind (the outer finally restores whatever happened), and
 * a file nothing rewrote can be told apart from one regenerated
 * identically.
 */
public final class EvidenceContractMain {

    private EvidenceContractMain() {
    }

    /**
     * Every study generator except the session photographer, which
     * needs a display and refuses to run without one - its artifacts
     * are the session-photograph class, deliberately not regenerated
     * here. Reports are captured from stdout and compared against
     * the committed file the Makefile writes them to.
     */
    private static final Map<String, String> REPORT_MAINS =
            new LinkedHashMap<>();
    static {
        REPORT_MAINS.put("juranometria.tool.FurnitureStudyMain",
                "docs/studies/chart-furniture/measurements.md");
        REPORT_MAINS.put("juranometria.tool.IdentifyStudyMain",
                "docs/studies/point-and-identify/measurements.md");
        REPORT_MAINS.put("juranometria.tool.DeepSkyOcclusionStudyMain",
                "docs/studies/deep-sky-occlusion/measurements.md");
        REPORT_MAINS.put("juranometria.tool.ApplicationMarkStudyMain",
                "docs/studies/application-mark/measurements.md");
        REPORT_MAINS.put("juranometria.tool.OnThisPageStudyMain",
                "docs/studies/on-this-page/measurements.md");
        REPORT_MAINS.put("juranometria.tool.TestEvidenceStudyMain",
                "docs/studies/test-evidence/measurements.md");
        REPORT_MAINS.put("juranometria.tool.PlaceAndTimeStudyMain",
                "docs/studies/place-and-time/measurements.md");
        // Writes its renderer-drawn pages beside the report as it
        // runs (issue #246), so capturing the report regenerates
        // them too - byte-reproducible per machine, like every
        // renderer study.
        REPORT_MAINS.put("juranometria.tool.BlackSkyStudyMain",
                "docs/studies/black-sky/measurements.md");
        // Writes its component-composed evidence images beside the
        // report (issue #258), the black-sky pattern.
        REPORT_MAINS.put("juranometria.tool.WorkingSelectionStudyMain",
                "docs/studies/working-selection/measurements.md");
        REPORT_MAINS.put("juranometria.tool.EclipticStudyMain",
                "docs/studies/ecliptic/measurements.md");
        REPORT_MAINS.put("juranometria.tool.PrintableChartStudyMain",
                "docs/studies/printable-chart/measurements.md");
        // Not prose but an oracle: the released pages' own pixels
        // (issue #284). Holding it to the same byte contract is what
        // makes "the 1-36 degree atlas is untouched" a standing
        // claim rather than a one-off check.
        // Writes the sheets beside the report as it runs (#285),
        // the black-sky pattern: capturing the report regenerates
        // the documents it describes.
        REPORT_MAINS.put("juranometria.tool.ChartSheetStudyMain",
                "docs/studies/chart-sheet/measurements.md");
        // Writes the pages it argues from beside the report (issue
        // #310), the black-sky pattern. Deliberately free of
        // wall-clock timings: the placement policies' cost is
        // reported as candidates examined so the file can reproduce
        // itself, and the runtime lives in the decision document.
        REPORT_MAINS.put("juranometria.tool.labels.LabelStudyMain",
                "docs/studies/label-placement/measurements.md");
        // The interaction gate for the chart's keyboard (#312), and
        // the map it was built from: the study reads the registry, so
        // a keystroke that changed without the document changing with
        // it fails here.
        REPORT_MAINS.put("juranometria.tool.ToggleShortcutStudyMain",
                "docs/studies/toggle-shortcuts/measurements.md");
        // The tooltip audit walks the surfaces the application
        // builds, so a control added without a decision about what it
        // says changes this document - and a document that did not
        // change with it fails here (#311).
        REPORT_MAINS.put("juranometria.tool.ControlExplanationStudyMain",
                "docs/studies/control-explanations/measurements.md");
        REPORT_MAINS.put("juranometria.tool.WiderFieldStudyMain",
                "docs/studies/wider-field/released-pages.txt");
        // Writes its 49 candidate pages beside the report as it runs
        // (issue #296), the black-sky pattern: capturing the report
        // regenerates the pages the gate was decided from.
        REPORT_MAINS.put("juranometria.tool.overview.OverviewStudyMain",
                "docs/studies/overview-projection/measurements.md");
        // The confirmation the gate above could not give and required
        // of #299: the same ink measure over pages the production
        // renderer drew, with labels and its own stroke policy.
        REPORT_MAINS.put("juranometria.tool.OverviewInkStudyMain",
                "docs/studies/overview-ink/measurements.md");
        // What that density was doing to the constellation figures,
        // found by looking at a page rather than by any test (#307).
        REPORT_MAINS.put("juranometria.tool.FigureAnchorStudyMain",
                "docs/studies/figure-anchors/measurements.md");
    }

    /**
     * The one report whose byte claim could not be made executable
     * here, recorded as the issue requires: the deep-sky-vocabulary
     * measurements embed widget-measured dialog geometry, so its
     * bytes depend on a display and a look-and-feel. It is
     * regenerated with a display on the maintainer's machine and
     * inspected; the verifier only requires that it exists and that
     * nothing has silently emptied it.
     */
    private static final String WIDGET_MEASURED_REPORT =
            "docs/studies/deep-sky-vocabulary/measurements.md";

    /**
     * The generators that write into docs/studies. The first draft
     * also ran the eight legacy study mains that write only under
     * build/ - one of which cannot run from a clean checkout at all,
     * because its constellation inputs are gitignored downloads
     * (review). Those mains verify nothing here, so they are not
     * run here; the docs directories their sprints hand-promoted are
     * legacy baselines, judged as such below rather than being
     * counted "reproduced" by the accident of nobody touching them.
     */
    /** The maps the provenance record reads to name a generator. */
    static Map<String, String> buildWriters() {
        return BUILD_WRITERS;
    }

    static Map<String, String> promotedDirectories() {
        return PROMOTED_DIRECTORIES;
    }

    static List<String> imageMains() {
        return IMAGE_MAINS;
    }

    /**
     * The studies that write a platform record beside their report.
     *
     * <p>Both of them measure two things at once: what the atlas is,
     * which is the same everywhere, and what this desktop calls a
     * key, which is not. The report is the first; this is the second.
     */
    private static final Map<String, String> PLATFORM_REPORTS =
            Map.of("juranometria.tool.ToggleShortcutStudyMain",
                    "docs/studies/toggle-shortcuts/platform.md",
                    "juranometria.tool.ControlExplanationStudyMain",
                    "docs/studies/control-explanations/platform.md",
                    "juranometria.tool.BlackSkyStudyMain",
                    "docs/studies/black-sky/platform.md",
                    "juranometria.tool.OverviewInkStudyMain",
                    "docs/studies/overview-ink/platform.md",
                    "juranometria.tool.FurnitureStudyMain",
                    "docs/studies/chart-furniture/platform.md",
                    "juranometria.tool.ChartSheetStudyMain",
                    "docs/studies/chart-sheet/platform.md",
                    "juranometria.tool.overview.OverviewStudyMain",
                    "docs/studies/overview-projection/platform.md",
                    "juranometria.tool.FigureAnchorStudyMain",
                    "docs/studies/figure-anchors/platform.md",
                    "juranometria.tool.WiderFieldStudyMain",
                    "docs/studies/wider-field/platform.md",
                    "juranometria.tool.labels.LabelStudyMain",
                    "docs/studies/label-placement/platform.md");

    /**
     * Every promoted rendering carries an account of itself, and the
     * bytes in the repository are the bytes it accounts for.
     *
     * <p>This is what replaces "the study has fallen behind the
     * atlas" on a machine that cannot know: a hash anybody can check,
     * against a record saying when and on what the picture was
     * agreed.
     */
    private static void provenanceBreaches(
            Map<String, Snapshot> committed, List<String> failures,
            Map<String, Integer> verdicts) throws Exception {
        Map<String, EvidenceProvenanceMain.Entry> recorded =
                new TreeMap<>();
        for (EvidenceProvenanceMain.Entry entry
                : EvidenceProvenanceMain.recorded()) {
            recorded.put(entry.path(), entry);
        }
        if (recorded.isEmpty()) {
            failures.add(EvidenceProvenanceMain.RECORD
                    + ": no promoted image says where it came from;"
                    + " run make evidence-provenance on the machine"
                    + " that promotes them");
            return;
        }
        int checked = 0;
        for (Map.Entry<String, Snapshot> entry : committed.entrySet()) {
            String path = entry.getKey();
            if (!"renderer-drawn".equals(TestEvidenceScan.artifactClass(
                    Path.of(path).getFileName().toString()))) {
                continue;
            }
            EvidenceProvenanceMain.Entry account = recorded.get(path);
            if (account == null) {
                failures.add(path + ": promoted without an account of"
                        + " itself - nothing records when or on what"
                        + " it was agreed");
            } else if (!account.sha256().equals(
                    EvidenceProvenanceMain.sha256(
                            entry.getValue().bytes()))) {
                failures.add(path + ": the bytes in the repository are"
                        + " not the bytes its provenance records, so"
                        + " one of them is wrong");
            } else {
                checked++;
            }
        }
        tally(verdicts, "provenance-verified (" + checked
                + " promoted renderings)");
    }

    private static final List<String> IMAGE_MAINS = List.of(
            "juranometria.tool.IdentifyMockupMain",
            "juranometria.tool.OnThisPageMockupMain",
            "juranometria.tool.DeepSkyVocabularyMockupMain",
            "juranometria.tool.PlaceAndTimeInkStudyMain",
            "juranometria.tool.PlaceAndTimeControlsMockupMain",
            // The gallery's module slides (issue #252): composed by
            // the production component, renderer-drawn contract.
            "juranometria.tool.GalleryPageMain",
            // The working-selection surface mock-ups (issue #258):
            // widget-rendered inspection, the selection- prefix.
            "juranometria.tool.WorkingSelectionMockupMain");

    /**
     * The legacy generators: they write under build/, and their
     * docs/studies directories were hand-promoted at their sprints.
     * The review refused to leave those ninety images unchecked, so
     * the verifier runs these too and compares each promoted file
     * against the generator's build output by name - the studies'
     * own rule is that chosen pages are production output, so a
     * mismatch is a study fallen behind the atlas. The constellation
     * generator is input-gated: its raw sources are gitignored
     * downloads, so a checkout without them skips it with a stated
     * verdict rather than failing clean-worktree runs.
     */
    private static final Map<String, String> BUILD_WRITERS =
            new LinkedHashMap<>();
    static {
        BUILD_WRITERS.put("juranometria.tool.RegionalStudyMain",
                "build/regional-study");
        BUILD_WRITERS.put("juranometria.tool.ConstellationStudyMain",
                "build/constellation-study");
        BUILD_WRITERS.put("juranometria.tool.ChartOptionsStudyMain",
                "build/chart-options-study");
        BUILD_WRITERS.put("juranometria.tool.StarIdentityStudyMain",
                "build/star-identity-study");
        BUILD_WRITERS.put("juranometria.tool.GridStudyMain",
                "build/grid-study");
        BUILD_WRITERS.put("juranometria.tool.BayerStudyMain",
                "build/bayer-study");
    }

    /** Each promoted docs directory and the build output it mirrors. */
    private static final Map<String, String> PROMOTED_DIRECTORIES =
            new LinkedHashMap<>();
    static {
        PROMOTED_DIRECTORIES.put("docs/studies/regional-detail/",
                "build/regional-study");
        PROMOTED_DIRECTORIES.put("docs/studies/regional-zoom/",
                "build/regional-study");
        PROMOTED_DIRECTORIES.put(
                "docs/studies/constellation-geography/",
                "build/constellation-study");
        PROMOTED_DIRECTORIES.put(
                "docs/studies/constellation-rendering/",
                "build/constellation-study");
        PROMOTED_DIRECTORIES.put("docs/studies/coordinate-grid/",
                "build/grid-study");
        PROMOTED_DIRECTORIES.put("docs/studies/bayer-notation/",
                "build/bayer-study");
        PROMOTED_DIRECTORIES.put("docs/studies/chart-options/",
                "build/chart-options-study");
        PROMOTED_DIRECTORIES.put("docs/studies/star-identity/",
                "build/star-identity-study");
    }

    /**
     * The generators whose raw sources are gitignored downloads.
     * Both discovered the same way: by the verifier failing on a
     * checkout without them - constellations at review, and the
     * star-identity study when the review's incomplete-fails-loudly
     * rule was rehearsed with imports/raw moved aside.
     */
    /** A gated generator's input directory and its exact fetch. */
    record Gate(Path input, String fetch) {
    }

    static final Map<String, Gate> GATED_GENERATORS = Map.of(
            "juranometria.tool.ConstellationStudyMain",
            new Gate(Path.of("imports/raw/constellations"),
                    "scripts/download-constellation-sources.sh"),
            "juranometria.tool.StarIdentityStudyMain",
            new Gate(Path.of("imports/raw/star-identities"),
                    "scripts/download-constellation-sources.sh and"
                            + " scripts/download-catalogue-sources.sh"));

    /**
     * The incomplete-run breach for a gated family, or null when its
     * inputs are present. Extracted so the branch has a committed
     * regression test, and so the message carries the exact command
     * that completes the run (review).
     */
    static String incompleteBreach(String buildDir, Gate gate,
                                   boolean inputPresent) {
        if (inputPresent) {
            return null;
        }
        return "VERIFICATION INCOMPLETE: " + buildDir + "'s evidence"
                + " family was not verified - its raw sources ("
                + gate.input() + ") are gitignored downloads; run "
                + gate.fetch() + " and rerun";
    }

    /**
     * How a promoted file is judged against its generator match and
     * the residue pin - every branch a breach or a silence, none an
     * accepted baseline by accident. Extracted for its regression
     * tests (review).
     */
    static List<String> promotedPinBreaches(String path,
                                            boolean matchedByName) {
        boolean pinned = PROMOTED_WITHOUT_GENERATOR.contains(path);
        if (!matchedByName && !pinned) {
            return List.of(path + ": promoted file matches no"
                    + " generator output and is not in the pinned"
                    + " residue");
        }
        if (matchedByName && pinned) {
            return List.of(path + ": pinned as having no generator"
                    + " output, but a build output matches it by name"
                    + " - the pin is stale");
        }
        return List.of();
    }

    /** Pinned entries missing from the tree: stale the other way. */
    static List<String> stalePinBreaches(
            java.util.Set<String> treePaths) {
        List<String> breaches = new ArrayList<>();
        for (String pinned : PROMOTED_WITHOUT_GENERATOR) {
            if (!treePaths.contains(pinned)) {
                breaches.add(pinned + ": pinned residue file is"
                        + " missing from the tree - the pin is stale");
            }
        }
        return breaches;
    }

    /**
     * The promoted files no generator output matches by name -
     * variants composed by hand at their sprints. Recorded, held as
     * committed, and pinned: an eighth arrives by decision.
     */
    static final List<String> PROMOTED_WITHOUT_GENERATOR =
            List.of("docs/studies/bayer-notation/crux-18-greek-wide.png",
                    "docs/studies/constellation-rendering/lmc-36deg.png",
                    "docs/studies/bayer-notation/m31-08-greek-wide.png",
                    "docs/studies/bayer-notation/orion-36-greek-wide.png",
                    "docs/studies/bayer-notation/orion-36-lettered-both.png",
                    "docs/studies/coordinate-grid/m31-08-absent.png",
                    "docs/studies/coordinate-grid/m31-08-labelled.png",
                    "docs/studies/coordinate-grid/m31-08-lines-only.png");

    /**
     * The captured evidence, pinned by digest: operating-system
     * screenshots (issue #245) that no command of ours can
     * regenerate - the desktop's own Finder, Dock and switcher
     * surfaces at a stated moment, with their provenance in the
     * decision document. A capture without a pin, a pin without its
     * capture, and changed bytes are each their own breach: a
     * re-capture arrives by commit and review, like a fixture's
     * provenance event, never by a file quietly swapped in.
     */
    static final Map<String, String> CAPTURES = new TreeMap<>();
    static {
        CAPTURES.put("docs/studies/mac-identity/"
                        + "screenshot-applications-folder.png",
                "c99125132638540ced866e1268ee0d870814a6ce"
                        + "cf7086db31385a8ce40b4b4a");
        CAPTURES.put("docs/studies/mac-identity/"
                        + "screenshot-desktop-alias.png",
                "961c4ddc311e0062713b37ec7e0c83666e0f2a6b"
                        + "a3982c2ccb85eda954507386");
        CAPTURES.put("docs/studies/mac-identity/"
                        + "screenshot-dock-app.png",
                "170ddb6dd475a0efb7c2f60fa693f4ef8b8f6ed9"
                        + "249e7d871f912d1385c38c0b");
        CAPTURES.put("docs/studies/mac-identity/"
                        + "screenshot-dock-candidate.png",
                "d7921af08fff6dffd493fa1942660fad75e1cd77"
                        + "51d9e1219759e3abd01fa424");
        CAPTURES.put("docs/studies/mac-identity/"
                        + "screenshot-dock-jar.png",
                "833eb38785ee88ba93949733e3607a8860b59040"
                        + "5ae7c4b56dae326f0b921767");
        CAPTURES.put("docs/studies/mac-identity/"
                        + "screenshot-finder-prelaunch.png",
                "d01ea316b407aef5b19faef8b7facda51e6beedd"
                        + "cc7457283299da8db2e66b71");
        CAPTURES.put("docs/studies/mac-identity/"
                        + "screenshot-switcher.png",
                "f23e58127b49789f8371ba6c41d5b6ccdf59c67f"
                        + "4bff1ea5b2f3450b14579fad");
        // The gallery's responsive contact captures (issue #252):
        // the index and one slide, desktop and narrow, in a real
        // browser; provenance in docs/decisions/gallery.md.
        CAPTURES.put("docs/studies/gallery/"
                        + "screenshot-gallery-index-desktop.png",
                "ad16b3ed006ada7a36a88a242c72993cf4c7156d"
                        + "c8bb86b70989ad644f581cbb");
        CAPTURES.put("docs/studies/gallery/"
                        + "screenshot-gallery-index-narrow.png",
                "47fd872a95f4939b1b3fc0c6b35be484a37dcbda"
                        + "db7b78307ad26bd50a77456b");
        CAPTURES.put("docs/studies/gallery/"
                        + "screenshot-gallery-slide-desktop.png",
                "17174c76c08c7e07c843125927213f44b19e9c42"
                        + "609169e807cb3b5ca6455167");
        CAPTURES.put("docs/studies/gallery/"
                        + "screenshot-gallery-slide-narrow.png",
                "3bd83d7f25620af85f7e98d8e9be02ac9a0cdeba"
                        + "7d2059bc3a6f0a11a7e96b90");
        // The published site itself (issue #253): the public
        // github.io URL in a fresh browser session, desktop and
        // narrow, after the Pages deploy.
        CAPTURES.put("docs/studies/gallery/"
                        + "screenshot-gallery-public-desktop.png",
                "ad16b3ed006ada7a36a88a242c72993cf4c7156d"
                        + "c8bb86b70989ad644f581cbb");
        CAPTURES.put("docs/studies/gallery/"
                        + "screenshot-gallery-public-narrow.png",
                "117670b356cbe8218b26fcd93b149b109ea344da"
                        + "045ec27c5e99bde5b3a088c1");
    }

    /**
     * The breaches for one captured-evidence artifact: unpinned,
     * vanished mid-run, or no longer the pinned bytes. Extracted so
     * each branch has a regression test rather than a rehearsal.
     */
    static List<String> captureBreaches(String path, byte[] now) {
        String pin = CAPTURES.get(path);
        if (pin == null) {
            return List.of(path + ": captured evidence without a"
                    + " pinned digest - a capture arrives with its"
                    + " provenance pinned, not by a file copied in");
        }
        if (now == null) {
            return List.of(path + ": captured evidence vanished"
                    + " during generation");
        }
        String digest = juranometria.catalog.Sha256.hex(now);
        if (!digest.equals(pin)) {
            return List.of(path + ": captured evidence changed - a"
                    + " re-capture is a provenance event, not a"
                    + " regeneration: " + digest);
        }
        return List.of();
    }

    /** Pinned captures the committed tree no longer holds. */
    static List<String> vanishedCapturePins(
            java.util.Set<String> committed) {
        List<String> breaches = new ArrayList<>();
        for (String pinned : CAPTURES.keySet()) {
            if (!committed.contains(pinned)) {
                breaches.add(pinned + ": pinned captured evidence is"
                        + " missing from the tree - removing one is a"
                        + " reviewed decision, pin and file together");
            }
        }
        return breaches;
    }

    /** The byte-exact fixtures, pinned by digest. */
    public static final Map<String, String> FIXTURES = Map.of(
            "docs/studies/place-and-time/reference-vectors.txt",
            "f785c8a2015d9dfc930165484c05ed6fcd12b6de"
                    + "238cf3147fec335489336b4b",
            "scripts/reference-vectors.c",
            "baf6f526f4f22997a0e2fc73d5574b9566f491df"
                    + "b8a675c55ba56ca1300f1b3e");

    /** One committed file: its bytes and when it was last written. */
    record Snapshot(byte[] bytes,
                            java.nio.file.attribute.FileTime written) {
    }

    /**
     * Whether this run may compare a rendering with another
     * machine's.
     *
     * <p><strong>portable</strong> is what CI runs: it holds the
     * deterministic reports to their committed bytes, holds every
     * rendering to reproducing <em>within this environment</em>, and
     * checks a promoted image against the account it carries of
     * itself. It never compares pixels drawn here with pixels
     * recorded elsewhere, because the project's own 1.0 contract
     * records pixel equality per environment and does not require it
     * across environments - and asking anyway turns "a different
     * machine" into "stale evidence" (#315).
     *
     * <p><strong>canonical</strong> is what the machine that promotes
     * reference images runs. It may compare a fresh rendering with
     * the committed one and say the study has fallen behind, because
     * there the comparison means what it says.
     */
    public enum Mode { PORTABLE, CANONICAL }

    public static void main(String[] args) throws Exception {
        Mode mode = args.length > 0 && "ci".equals(args[0])
                ? Mode.PORTABLE : Mode.CANONICAL;
        Map<String, Snapshot> committed = snapshot();
        List<String> failures = new ArrayList<>();
        Map<String, Integer> verdicts = new TreeMap<>();
        System.out.println(mode == Mode.PORTABLE
                ? "portable contract: renderings are held to"
                        + " reproducing here, never to another"
                        + " machine's pixels"
                : "canonical contract: renderings are compared with"
                        + " the committed references");
        generateUnderRestoration(Path.of("docs/studies"), committed,
                () -> run(committed, failures, verdicts, mode));
    }

    /**
     * The first few lines that differ, for a breach to be acted on.
     *
     * <p>"Did not reproduce" names the file and nothing else, which
     * is enough to know something is wrong and not enough to know
     * what kind of wrong. A number that moved with a font is a
     * different finding from a number that moved with the atlas, and
     * telling them apart is the whole of the work (#315).
     */
    private static String differingLines(byte[] expected,
                                         byte[] found) {
        List<String> was = new java.io.BufferedReader(
                new java.io.StringReader(new String(expected,
                        java.nio.charset.StandardCharsets.UTF_8)))
                .lines().toList();
        List<String> now = new java.io.BufferedReader(
                new java.io.StringReader(new String(found,
                        java.nio.charset.StandardCharsets.UTF_8)))
                .lines().toList();
        StringBuilder out = new StringBuilder();
        int shown = 0;
        int differing = 0;
        for (int line = 0; line < Math.max(was.size(), now.size());
                line++) {
            String before = line < was.size() ? was.get(line) : null;
            String after = line < now.size() ? now.get(line) : null;
            if (java.util.Objects.equals(before, after)) {
                continue;
            }
            differing++;
            if (shown++ < DIFFERENCES_SHOWN) {
                out.append(System.lineSeparator())
                        .append("    line ").append(line + 1)
                        .append(System.lineSeparator())
                        .append("      committed: ").append(before)
                        .append(System.lineSeparator())
                        .append("      here     : ").append(after);
            }
        }
        if (differing > DIFFERENCES_SHOWN) {
            out.append(System.lineSeparator())
                    .append("    and ")
                    .append(differing - DIFFERENCES_SHOWN)
                    .append(" more differing lines of ")
                    .append(Math.max(was.size(), now.size()));
        }
        return out.toString();
    }

    /**
     * How many differing lines a breach prints before summarising.
     *
     * <p>Generous on purpose. Six of forty differing lines is nearly
     * as unhelpful as none: what a reader of this output has to do
     * is decide whether the differences are one kind or two, and a
     * sample cannot answer that.
     */
    private static final int DIFFERENCES_SHOWN = 40;

    /**
     * A platform observation, held to reproducing on this machine.
     *
     * <p>Run again, into a second buffer, and required to say the
     * same thing. That catches the failure a byte contract catches -
     * a generator that has stopped being deterministic - without
     * claiming anything about a font it has never seen.
     */
    private static List<String> observedBreaches(
            Map.Entry<String, String> report,
            ByteArrayOutputStream first) throws Exception {
        ByteArrayOutputStream again = new ByteArrayOutputStream();
        PrintStream was = System.out;
        System.setOut(new PrintStream(again, true, "UTF-8"));
        try {
            Class.forName(report.getKey())
                    .getMethod("main", String[].class)
                    .invoke(null, (Object) new String[0]);
        } finally {
            System.setOut(was);
        }
        if (java.util.Arrays.equals(first.toByteArray(),
                again.toByteArray())) {
            return List.of();
        }
        return List.of(report.getValue() + ": a platform observation"
                + " has to reproduce within its own environment"
                + differingLines(first.toByteArray(),
                        again.toByteArray()));
    }

    /**
     * What two runs of every rendering generator produced.
     *
     * @param first what each path held after the first run
     * @param claimed the paths a generator actually wrote in both
     *     runs - a file nothing touched has not been drawn twice and
     *     may not be reported as though it had
     * @param differing the paths whose two drawings disagree
     */
    record DrawnTwice(Map<String, byte[]> first,
                      java.util.Set<String> claimed,
                      List<String> differing) {
    }

    /**
     * Runs every generator twice and says which renderings moved.
     *
     * <p>Package-visible and taking its generators as an argument so
     * that a test can hand it one that draws something different each
     * time, and require this to say so (review, #322).
     */
    static DrawnTwice drawTwice(List<String> generators,
                                List<String> paths) throws Exception {
        return drawTwice(generators, paths, List.of());
    }

    /**
     * The same, also watching whatever appears in these directories.
     *
     * <p>The promoted study pages are not written where they are
     * committed: their generators draw into {@code build/}, and the
     * canonical run compares the two. A portable run may not make
     * that comparison - the committed page was agreed on another
     * machine - but the generator's own determinism is still a fair
     * question, and asking it of the build output is how it gets
     * asked. Without this, a build writer could draw a different page
     * every time and a portable run would notice nothing, because it
     * only ever looks at what is committed (review, #322).
     */
    static DrawnTwice drawTwice(List<String> generators,
                                List<String> paths,
                                List<String> directories)
            throws Exception {
        // Whether a generator wrote a file is asked by dating every
        // candidate to the epoch first and seeing which dates moved.
        // Comparing timestamps before and after does not answer it:
        // two runs of a quick generator land in the same millisecond,
        // and the file then looks untouched when it was written twice
        // - which this test caught before CI did.
        Map<String, Long> original = stamps(paths);
        java.util.Set<String> writtenOnce = wroteWhileDatedOld(
                generators, paths);
        Map<String, byte[]> first = new TreeMap<>();
        for (String path : paths) {
            if (Files.exists(Path.of(path))) {
                first.put(path, Files.readAllBytes(Path.of(path)));
            }
        }
        Map<String, byte[]> firstBuilt = drawnIn(directories);
        java.util.Set<String> writtenAgain = wroteWhileDatedOld(
                generators, paths);
        Map<String, byte[]> builtAgain = drawnIn(directories);

        java.util.Set<String> claimed = new java.util.TreeSet<>();
        List<String> differing = new ArrayList<>();
        for (String path : paths) {
            if (!writtenOnce.contains(path)
                    || !writtenAgain.contains(path)) {
                // Nothing drew it, so nothing here may say it was
                // drawn twice. Its own class decides what happens to
                // it further down.
                restore(path, original.get(path));
                continue;
            }
            claimed.add(path);
            if (!java.util.Arrays.equals(first.get(path),
                    Files.readAllBytes(Path.of(path)))) {
                differing.add(path);
            }
        }
        // And whatever the generators drew where they draw it.
        for (Map.Entry<String, byte[]> built : firstBuilt.entrySet()) {
            byte[] now = builtAgain.get(built.getKey());
            if (now == null) {
                continue;
            }
            claimed.add(built.getKey());
            if (!java.util.Arrays.equals(built.getValue(), now)) {
                differing.add(built.getKey());
            }
        }
        return new DrawnTwice(first, claimed, differing);
    }

    /** Every image a generator has left in these directories. */
    private static Map<String, byte[]> drawnIn(List<String> directories)
            throws IOException {
        Map<String, byte[]> found = new TreeMap<>();
        for (String directory : directories) {
            Path root = Path.of(directory);
            if (!Files.isDirectory(root)) {
                continue;
            }
            try (Stream<Path> tree = Files.walk(root)) {
                for (Path file : tree.filter(Files::isRegularFile)
                        .filter(f -> f.toString().endsWith(".png"))
                        .toList()) {
                    found.put(file.toString(),
                            Files.readAllBytes(file));
                }
            }
        }
        return found;
    }

    /** Dates every candidate old, runs the generators, says what moved. */
    private static java.util.Set<String> wroteWhileDatedOld(
            List<String> generators, List<String> paths)
            throws Exception {
        for (String path : paths) {
            restore(path, 0L);
        }
        runAll(generators);
        java.util.Set<String> written = new java.util.TreeSet<>();
        for (String path : paths) {
            Path file = Path.of(path);
            if (Files.exists(file)
                    && Files.getLastModifiedTime(file).toMillis() != 0L) {
                written.add(path);
            }
        }
        return written;
    }

    /** Puts a file's date back, where there is one to put back. */
    private static void restore(String path, Long when)
            throws IOException {
        Path file = Path.of(path);
        if (when != null && Files.exists(file)) {
            Files.setLastModifiedTime(file,
                    java.nio.file.attribute.FileTime.fromMillis(when));
        }
    }

    /** Every generator that owns a renderer-drawn artifact. */
    private static List<String> renderingGenerators() {
        List<String> generators = new ArrayList<>(REPORT_MAINS.keySet());
        for (String main : PLATFORM_REPORTS.keySet()) {
            if (!generators.contains(main)) {
                generators.add(main);
            }
        }
        generators.addAll(IMAGE_MAINS);
        for (Map.Entry<String, String> writer : BUILD_WRITERS.entrySet()) {
            Gate gate = GATED_GENERATORS.get(writer.getKey());
            if (gate == null || Files.isDirectory(gate.input())) {
                generators.add(writer.getKey());
            }
        }
        return generators;
    }

    /** Every committed artifact a renderer drew. */
    private static List<String> rendererDrawn(
            Map<String, Snapshot> committed) {
        List<String> paths = new ArrayList<>();
        for (String path : committed.keySet()) {
            if ("renderer-drawn".equals(TestEvidenceScan.artifactClass(
                    Path.of(path).getFileName().toString()))) {
                paths.add(path);
            }
        }
        return paths;
    }

    private static void runAll(List<String> generators)
            throws Exception {
        PrintStream was = System.out;
        System.setOut(new PrintStream(new ByteArrayOutputStream(),
                true, "UTF-8"));
        try {
            for (String main : generators) {
                Class.forName(main).getMethod("main", String[].class)
                        .invoke(null, (Object) new String[0]);
            }
        } finally {
            System.setOut(was);
        }
    }

    /** When each of these files was last written, or null. */
    private static Map<String, Long> stamps(List<String> paths)
            throws IOException {
        Map<String, Long> when = new TreeMap<>();
        for (String path : paths) {
            Path file = Path.of(path);
            if (Files.exists(file)) {
                when.put(path, Files.getLastModifiedTime(file)
                        .toMillis());
            }
        }
        return when;
    }

    /** A generation step that may fail. */
    interface Generation {
        void run() throws Exception;
    }

    /**
     * The outer restoration path itself, extracted so a regression
     * test can throw a generator through the real finally rather
     * than calling the cleanup by hand (review): whatever the body
     * does - dying mid-run included - the inspection imagery goes
     * back to its committed bytes and inspection-class newcomers
     * are removed before the failure continues on its way.
     */
    static void generateUnderRestoration(Path root,
            Map<String, Snapshot> committed, Generation body)
            throws Exception {
        // The project's standing suppression rule (review): if the
        // generation and the restoration both fail, the evidence
        // failure is the one thrown and the cleanup's trouble rides
        // as suppressed - never the other way round.
        Throwable primary = null;
        try {
            body.run();
        } catch (Throwable failure) {
            primary = failure;
        }
        try {
            restoreInspectionImagery(root, committed);
        } catch (Throwable trouble) {
            if (primary == null) {
                primary = trouble;
            } else {
                primary.addSuppressed(trouble);
            }
        }
        if (primary instanceof Exception failure) {
            throw failure;
        }
        if (primary instanceof Error failure) {
            throw failure;
        }
    }

    /**
     * Puts every inspection-class file back to its snapshotted bytes
     * and removes inspection-class newcomers. Extracted so the
     * guarantee has regression tests of its own rather than a
     * rehearsal in a pull-request narrative (review).
     */
    static void restoreInspectionImagery(Path root,
            Map<String, Snapshot> committed) throws IOException {
        for (Map.Entry<String, Snapshot> entry : committed.entrySet()) {
            if (!inspectionClass(entry.getKey())) {
                continue;
            }
            Path path = Path.of(entry.getKey());
            if (!Files.exists(path)
                    || !java.util.Arrays.equals(
                            entry.getValue().bytes(),
                            Files.readAllBytes(path))) {
                Files.write(path, entry.getValue().bytes());
            }
        }
        try (Stream<Path> tree = Files.walk(root)) {
            for (Path file : tree.filter(Files::isRegularFile)
                    .sorted().toList()) {
                String key = file.toString().replace(
                        java.io.File.separatorChar, '/');
                if (!committed.containsKey(key)
                        && inspectionClass(key)) {
                    Files.delete(file);
                }
            }
        }
    }

    /** The newcomer breaches under a root, against a snapshot. */
    static List<String> newcomerBreaches(Path root,
            Map<String, Snapshot> committed) throws IOException {
        List<String> breaches = new ArrayList<>();
        try (Stream<Path> tree = Files.walk(root)) {
            for (Path file : tree.filter(Files::isRegularFile)
                    .sorted().toList()) {
                String key = file.toString().replace(
                        java.io.File.separatorChar, '/');
                if (!committed.containsKey(key)) {
                    breaches.add(key + ": generated but not committed"
                            + " - a new artifact arrives by commit and"
                            + " review, not by regeneration");
                }
            }
        }
        return breaches;
    }

    private static boolean inspectionClass(String path) {
        String cls = TestEvidenceScan.artifactClass(
                Path.of(path).getFileName().toString());
        return cls.equals("widget-rendered-inspection")
                || cls.equals("session-photograph");
    }

    private static void run(Map<String, Snapshot> committed,
                            List<String> failures,
                            Map<String, Integer> verdicts,
                            Mode mode)
            throws Exception {

        // ---- every rendering, drawn twice, before anything else --
        // What a portable contract can honestly ask of a rendering is
        // that this machine draws it the same way twice. That has to
        // mean *every* generator that owns renderer output, not only
        // the ones in IMAGE_MAINS: the report generators draw pages
        // too, and a first version of this captured them before the
        // second pass and then compared each with itself, so a
        // nondeterministic report image would have passed while the
        // run claimed every rendering reproduced (review, #322).
        DrawnTwice twice = null;
        if (mode == Mode.PORTABLE) {
            twice = drawTwice(renderingGenerators(),
                    rendererDrawn(committed),
                    new ArrayList<>(BUILD_WRITERS.values()));
            for (String path : twice.differing()) {
                failures.add(path + ": renderer-drawn image did not"
                        + " reproduce byte-for-byte between two"
                        + " renderings on this machine - the generator"
                        + " is not deterministic");
            }
            tally(verdicts, "drawn twice here and identical ("
                    + (twice.claimed().size() - twice.differing().size())
                    + " renderings)");
            // And the residue, named rather than implied: a committed
            // rendering that no generator wrote in either pass has
            // not been checked by this run, and saying how many there
            // are and which they are is the difference between a
            // contract and a comfortable number (review, #322).
            List<String> unclaimed = new ArrayList<>();
            for (String path : rendererDrawn(committed)) {
                if (!twice.claimed().contains(path)) {
                    unclaimed.add(path);
                }
            }
            // The promoted pages are the bulk of that residue, and
            // they are not unchecked: their generators drew into
            // build/ twice above, and the committed page is held to
            // the account it carries of itself.
            tally(verdicts, "drawn twice where the generator draws"
                    + " ("
                    + twice.claimed().stream()
                            .filter(path -> path.startsWith("build/"))
                            .count()
                    + " build outputs)");
            tally(verdicts, "not drawn here (" + unclaimed.size()
                    + " renderings; held by their own class)");
            if (!unclaimed.isEmpty()) {
                System.out.println("Renderings nothing drew on this"
                        + " run, held as committed by their own"
                        + " class:");
                for (String path : unclaimed) {
                    System.out.println("  " + path
                            + (PROMOTED_WITHOUT_GENERATOR.contains(path)
                                    ? " (pinned: no generator)" : ""));
                }
                System.out.println();
            }
        }

        // ---- deterministic reports, from stdout: no churn --------
        PrintStream realOut = System.out;
        for (Map.Entry<String, String> report : REPORT_MAINS.entrySet()) {
            ByteArrayOutputStream captured = new ByteArrayOutputStream();
            System.setOut(new PrintStream(captured, true, "UTF-8"));
            try {
                Class.forName(report.getKey())
                        .getMethod("main", String[].class)
                        .invoke(null, (Object) new String[0]);
            } finally {
                System.setOut(realOut);
            }
            String said = captured.toString("UTF-8");
            if (said.contains(PlatformEvidence.OBSERVED_MARK)) {
                // The report says of itself that its numbers are this
                // machine's. Held to what that allows: it names the
                // machine, and running the study again here writes
                // the same thing. Comparing it with a recording made
                // on another desktop would be asking a question the
                // project's own contract refuses to ask (#315).
                failures.addAll(observedBreaches(report, captured));
                if (!said.contains("Recorded on: `")) {
                    failures.add(report.getValue() + ": a platform"
                            + " observation has to name the machine"
                            + " it was taken on");
                } else {
                    tally(verdicts, "platform-observed (reproduces"
                            + " here; not held across machines)");
                }
                continue;
            }
            Snapshot expectedSnapshot = committed.get(report.getValue());
            byte[] expected = expectedSnapshot == null ? null
                    : expectedSnapshot.bytes();
            if (expected == null) {
                failures.add(report.getValue() + ": committed report"
                        + " is missing");
            } else if (!java.util.Arrays.equals(expected,
                    captured.toByteArray())) {
                failures.add(report.getValue() + ": deterministic"
                        + " report did not reproduce byte-for-byte"
                        + differingLines(expected,
                                captured.toByteArray()));
            } else {
                tally(verdicts, "reproduced");
            }
        }

        // ---- the platform half of the split reports --------------
        // Held to what it can honestly be held to: it exists, it
        // says which machine it is from, and running the study again
        // writes the same bytes here. What it may not be held to is
        // another machine's copy, which is the whole reason it was
        // taken out of the report beside it (#315).
        for (Map.Entry<String, String> record
                : PLATFORM_REPORTS.entrySet()) {
            Path file = Path.of(record.getValue());
            if (!Files.exists(file)) {
                failures.add(record.getValue() + ": the platform"
                        + " record its study writes is missing");
                continue;
            }
            byte[] first = Files.readAllBytes(file);
            String said = new String(first,
                    java.nio.charset.StandardCharsets.UTF_8);
            if (!said.contains("| operating system |")
                    && !said.contains("Recorded on: `")) {
                failures.add(record.getValue() + ": a platform record"
                        + " has to name the machine it is from");
                continue;
            }
            PrintStream was = System.out;
            System.setOut(new PrintStream(
                    new ByteArrayOutputStream(), true, "UTF-8"));
            try {
                Class.forName(record.getKey())
                        .getMethod("main", String[].class)
                        .invoke(null, (Object) new String[0]);
            } finally {
                System.setOut(was);
            }
            if (!java.util.Arrays.equals(first,
                    Files.readAllBytes(file))) {
                failures.add(record.getValue() + ": a platform record"
                        + " has to reproduce within its own"
                        + " environment"
                        + differingLines(first,
                                Files.readAllBytes(file)));
            } else {
                tally(verdicts, "platform-recorded (reproduces here;"
                        + " not held across machines)");
            }
        }

        // ---- what a promoted image says about itself --------------
        provenanceBreaches(committed, failures, verdicts);

        // ---- image generators, then judge every touched file ------
        for (String main : IMAGE_MAINS) {
            Class.forName(main).getMethod("main", String[].class)
                    .invoke(null, (Object) new String[0]);
        }
        Snapshot widgetMeasuredSnap = committed.get(WIDGET_MEASURED_REPORT);
        byte[] widgetMeasured = widgetMeasuredSnap == null ? null
                : widgetMeasuredSnap.bytes();
        if (widgetMeasured == null || widgetMeasured.length < 1000) {
            failures.add(WIDGET_MEASURED_REPORT + ": the widget-"
                    + "measured report is missing or empty");
        } else {
            tally(verdicts,
                    "widget-measured (display required; held to substance)");
        }
        // The legacy generators, compared against their promoted
        // docs directories. Paired per directory, never by a global
        // name map: two studies both promoted an
        // orion-36-everything.png, and the first draft compared one
        // of them against the other study's page of the same name.
        java.util.Set<String> judgedViaBuild = new java.util.TreeSet<>();
        java.util.Set<String> skippedBuildDirs = new java.util.TreeSet<>();
        for (Map.Entry<String, String> writer : BUILD_WRITERS.entrySet()) {
            Gate gate = GATED_GENERATORS.get(writer.getKey());
            String incomplete = gate == null ? null
                    : incompleteBreach(writer.getValue(), gate,
                            Files.isDirectory(gate.input()));
            if (incomplete != null) {
                skippedBuildDirs.add(writer.getValue());
                // A download nobody has is a fact about the machine,
                // not about the evidence. The canonical run says so
                // as a breach because that machine is the one that
                // promotes these families; a portable run reports it
                // as what it is (#315).
                if (mode == Mode.PORTABLE) {
                    tally(verdicts, "unavailable here (raw sources are"
                            + " gitignored downloads)");
                } else {
                    failures.add(incomplete);
                }
                continue;
            }
            Class.forName(writer.getKey())
                    .getMethod("main", String[].class)
                    .invoke(null, (Object) new String[0]);
        }
        for (Map.Entry<String, String> pair
                : PROMOTED_DIRECTORIES.entrySet()) {
            if (skippedBuildDirs.contains(pair.getValue())) {
                continue;
            }
            Map<String, Path> outputs = new TreeMap<>();
            try (Stream<Path> tree =
                    Files.walk(Path.of(pair.getValue()))) {
                tree.filter(f -> f.toString().endsWith(".png"))
                        .forEach(f -> outputs.put(
                                f.getFileName().toString(), f));
            }
            for (String path : committed.keySet()) {
                if (!path.startsWith(pair.getKey())
                        || !path.endsWith(".png")) {
                    continue;
                }
                Path match = outputs.get(
                        Path.of(path).getFileName().toString());
                failures.addAll(promotedPinBreaches(path,
                        match != null));
                if (match == null) {
                    continue;
                }
                judgedViaBuild.add(path);
                if (mode == Mode.PORTABLE) {
                    // Whether the study has fallen behind the atlas
                    // is a question about cartography, and a machine
                    // whose fonts are not the fonts the page was
                    // agreed on cannot ask it: every page would
                    // answer yes, and mean nothing by it. What this
                    // run holds instead is the account the page
                    // carries of itself, checked above (#315).
                    tally(verdicts, "promoted (provenance held; not"
                            + " re-rendered against another machine)");
                } else if (java.util.Arrays.equals(
                        committed.get(path).bytes(),
                        Files.readAllBytes(match))) {
                    tally(verdicts, "reproduced (via generator build"
                            + " output)");
                } else {
                    failures.add(path + ": the promoted study page no"
                            + " longer matches its generator's output"
                            + " - the study has fallen behind the"
                            + " atlas");
                }
            }
        }

        failures.addAll(stalePinBreaches(committed.keySet()));

        // Newcomers first: a file the generation created that the
        // snapshot never held is an artifact nobody committed - a
        // breach whatever its class, and never silent (review). The
        // inspection-class ones are removed by the outer restoration.
        failures.addAll(newcomerBreaches(Path.of("docs/studies"),
                committed));
        for (Map.Entry<String, Snapshot> entry : committed.entrySet()) {
            String path = entry.getKey();
            if (path.endsWith(".md")) {
                continue; // judged above, from stdout
            }
            String cls = TestEvidenceScan.artifactClass(
                    Path.of(path).getFileName().toString());
            Path file = Path.of(path);
            byte[] now = Files.exists(file)
                    ? Files.readAllBytes(file) : null;
            // What "the same" means depends on what this run is
            // allowed to compare with. A portable run compares a
            // rendering with the one it drew a moment ago on this
            // machine; only the canonical run compares it with the
            // pixels somebody agreed to elsewhere.
            byte[] reference = mode == Mode.PORTABLE
                    && twice != null && twice.first().containsKey(path)
                    ? twice.first().get(path) : entry.getValue().bytes();
            boolean same = java.util.Arrays.equals(reference, now);
            boolean rewritten = Files.exists(file)
                    && !Files.getLastModifiedTime(file)
                            .equals(entry.getValue().written());
            switch (cls) {
                case "renderer-drawn" -> {
                    if (judgedViaBuild.contains(path)) {
                        // Compared against its generator's build
                        // output above.
                    } else if (!rewritten) {
                        tally(verdicts, same
                                ? (PROMOTED_WITHOUT_GENERATOR
                                        .contains(path)
                                        ? "promoted-without-generator"
                                                + " (pinned residue;"
                                                + " held as committed)"
                                        : "legacy-baseline (held as"
                                                + " committed)")
                                : failuresAdd(failures, path
                                        + ": legacy baseline changed"
                                        + " though nothing generates"
                                        + " it"));
                    } else if (same) {
                        tally(verdicts, "reproduced");
                    } else {
                        failures.add(path + ": renderer-drawn image"
                                + " did not reproduce byte-for-byte"
                                + (mode == Mode.PORTABLE
                                        ? " between two renderings on"
                                                + " this machine - the"
                                                + " generator is not"
                                                + " deterministic"
                                        : " on this machine"));
                    }
                }
                case "widget-rendered-inspection" -> {
                    if (!same) {
                        // Drift is the class's nature, not a defect;
                        // no inspection happened here, and the
                        // verdict must not claim one (review). The
                        // outer path restores the committed bytes.
                        tally(verdicts, "inspection-imagery drift"
                                + " restored - inspect before any"
                                + " recommit");
                    } else {
                        tally(verdicts, rewritten
                                ? "inspection-imagery regenerated"
                                        + " identical"
                                : "inspection-imagery unchanged");
                    }
                }
                case "session-photograph" -> {
                    if (!same) {
                        failures.add(path + ": session photograph"
                                + " changed though its generator was"
                                + " never run");
                    } else {
                        tally(verdicts, "deliberately-unchanged"
                                + " (session photograph)");
                    }
                }
                case "byte-exact-fixture" ->
                        tally(verdicts, "deliberately-unchanged"
                                + " (fixture)");
                case "captured-evidence" -> {
                    List<String> breaches = captureBreaches(path, now);
                    if (breaches.isEmpty()) {
                        tally(verdicts, "checksum-verified"
                                + " (captured evidence)");
                    } else {
                        failures.addAll(breaches);
                    }
                }
                default -> tally(verdicts, cls);
            }
        }

        failures.addAll(vanishedCapturePins(committed.keySet()));

        // ---- fixtures, by digest -----------------------------------
        for (Map.Entry<String, String> fixture : FIXTURES.entrySet()) {
            String digest = juranometria.catalog.Sha256.hex(
                    Files.readAllBytes(Path.of(fixture.getKey())));
            if (!digest.equals(fixture.getValue())) {
                failures.add(fixture.getKey() + ": byte-exact fixture"
                        + " changed - a provenance event, not a"
                        + " regeneration: " + digest);
            } else {
                tally(verdicts, "checksum-verified");
            }
        }

        // ---- the canonical reference: named, not touched -----------
        realOut.println("docs/reference/*: canonical - compared"
                + " byte-for-byte against the packaged render in the"
                + " app-image job, its proper environment; never"
                + " regenerated here.");
        realOut.println("dialog-real*: session photographs - packed"
                + " geometry asserted by the lifecycle test; bytes are"
                + " illustrations and their generator needs a"
                + " display.");
        realOut.println();
        for (Map.Entry<String, Integer> verdict : verdicts.entrySet()) {
            realOut.printf("%5d  %s%n", verdict.getValue(),
                    verdict.getKey());
        }
        if (!failures.isEmpty()) {
            realOut.println();
            failures.forEach(f -> realOut.println("CONTRACT BREACH: " + f));
            System.exit(1);
        }
        realOut.println();
        realOut.println("EVIDENCE CONTRACTS OK");
    }

    private static Map<String, Snapshot> snapshot() throws IOException {
        return snapshot(Path.of("docs/studies"));
    }

    static Map<String, Snapshot> snapshot(Path root) throws IOException {
        Map<String, Snapshot> files = new TreeMap<>();
        try (Stream<Path> tree = Files.walk(root)) {
            for (Path file : tree.filter(Files::isRegularFile)
                    .sorted().toList()) {
                files.put(file.toString()
                                .replace(java.io.File.separatorChar, '/'),
                        new Snapshot(Files.readAllBytes(file),
                                Files.getLastModifiedTime(file)));
            }
        }
        return files;
    }

    /** Adds the failure and hands back a verdict label for tally. */
    private static String failuresAdd(List<String> failures,
                                      String failure) {
        failures.add(failure);
        return "contract-breach";
    }

    private static void tally(Map<String, Integer> verdicts,
                              String verdict) {
        verdicts.merge(verdict, 1, Integer::sum);
    }
}
