package juranometria.tool;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Stream;

/**
 * Regenerates the generated evidence and holds every artifact to its
 * own contract (Sprint 26, issue #242).
 *
 * <p>The classes and their contracts are the gate's
 * ({@code docs/decisions/test-evidence.md}); this makes them
 * executable. A clean run reports, per artifact, one of four
 * verdicts and exits nonzero if any contract is breached:
 *
 * <ul>
 *   <li><strong>reproduced</strong> - deterministic reports and
 *       renderer-drawn images regenerated byte-for-byte;</li>
 *   <li><strong>structurally-verified</strong> - held by the
 *       in-suite structural checks rather than by bytes;</li>
 *   <li><strong>inspection-imagery</strong> - widget-rendered
 *       artifacts whose regenerated bytes drifted are <em>restored
 *       from the committed snapshot</em> and reported for a human
 *       eye, never silently churned and never claimed inspected by
 *       a command that has no eyes (review);</li>
 *   <li><strong>deliberately-unchanged</strong> - byte-exact
 *       fixtures (checksum-verified) and session photographs, whose
 *       generator needs a display and is not run here at all.</li>
 * </ul>
 *
 * <p>The whole committed tree under docs/studies is snapshotted -
 * bytes and modification times - before anything runs, so
 * restoration needs no git, a generator that dies cannot leave
 * drift behind (the outer finally restores whatever happened), and
 * a file nothing rewrote can be told apart from one regenerated
 * identically.
 */
public final class EvidenceContractMain {

    private EvidenceContractMain() {
    }

    /**
     * Every study generator except the session photographer, which
     * needs a display and refuses to run without one - its artifacts
     * are the session-photograph class, deliberately not regenerated
     * here. Reports are captured from stdout and compared against
     * the committed file the Makefile writes them to.
     */
    private static final Map<String, String> REPORT_MAINS =
            new LinkedHashMap<>();
    static {
        REPORT_MAINS.put("juranometria.tool.FurnitureStudyMain",
                "docs/studies/chart-furniture/measurements.md");
        REPORT_MAINS.put("juranometria.tool.IdentifyStudyMain",
                "docs/studies/point-and-identify/measurements.md");
        REPORT_MAINS.put("juranometria.tool.DeepSkyOcclusionStudyMain",
                "docs/studies/deep-sky-occlusion/measurements.md");
        REPORT_MAINS.put("juranometria.tool.ApplicationMarkStudyMain",
                "docs/studies/application-mark/measurements.md");
        REPORT_MAINS.put("juranometria.tool.OnThisPageStudyMain",
                "docs/studies/on-this-page/measurements.md");
        REPORT_MAINS.put("juranometria.tool.TestEvidenceStudyMain",
                "docs/studies/test-evidence/measurements.md");
        REPORT_MAINS.put("juranometria.tool.PlaceAndTimeStudyMain",
                "docs/studies/place-and-time/measurements.md");
    }

    /**
     * The one report whose byte claim could not be made executable
     * here, recorded as the issue requires: the deep-sky-vocabulary
     * measurements embed widget-measured dialog geometry, so its
     * bytes depend on a display and a look-and-feel. It is
     * regenerated with a display on the maintainer's machine and
     * inspected; the verifier only requires that it exists and that
     * nothing has silently emptied it.
     */
    private static final String WIDGET_MEASURED_REPORT =
            "docs/studies/deep-sky-vocabulary/measurements.md";

    /**
     * The generators that write into docs/studies. The first draft
     * also ran the eight legacy study mains that write only under
     * build/ - one of which cannot run from a clean checkout at all,
     * because its constellation inputs are gitignored downloads
     * (review). Those mains verify nothing here, so they are not
     * run here; the docs directories their sprints hand-promoted are
     * legacy baselines, judged as such below rather than being
     * counted "reproduced" by the accident of nobody touching them.
     */
    private static final List<String> IMAGE_MAINS = List.of(
            "juranometria.tool.IdentifyMockupMain",
            "juranometria.tool.OnThisPageMockupMain",
            "juranometria.tool.DeepSkyVocabularyMockupMain",
            "juranometria.tool.PlaceAndTimeInkStudyMain",
            "juranometria.tool.PlaceAndTimeControlsMockupMain");

    /**
     * The legacy generators: they write under build/, and their
     * docs/studies directories were hand-promoted at their sprints.
     * The review refused to leave those ninety images unchecked, so
     * the verifier runs these too and compares each promoted file
     * against the generator's build output by name - the studies'
     * own rule is that chosen pages are production output, so a
     * mismatch is a study fallen behind the atlas. The constellation
     * generator is input-gated: its raw sources are gitignored
     * downloads, so a checkout without them skips it with a stated
     * verdict rather than failing clean-worktree runs.
     */
    private static final Map<String, String> BUILD_WRITERS =
            new LinkedHashMap<>();
    static {
        BUILD_WRITERS.put("juranometria.tool.RegionalStudyMain",
                "build/regional-study");
        BUILD_WRITERS.put("juranometria.tool.ConstellationStudyMain",
                "build/constellation-study");
        BUILD_WRITERS.put("juranometria.tool.ChartOptionsStudyMain",
                "build/chart-options-study");
        BUILD_WRITERS.put("juranometria.tool.StarIdentityStudyMain",
                "build/star-identity-study");
        BUILD_WRITERS.put("juranometria.tool.GridStudyMain",
                "build/grid-study");
        BUILD_WRITERS.put("juranometria.tool.BayerStudyMain",
                "build/bayer-study");
    }

    /** Each promoted docs directory and the build output it mirrors. */
    private static final Map<String, String> PROMOTED_DIRECTORIES =
            new LinkedHashMap<>();
    static {
        PROMOTED_DIRECTORIES.put("docs/studies/regional-detail/",
                "build/regional-study");
        PROMOTED_DIRECTORIES.put("docs/studies/regional-zoom/",
                "build/regional-study");
        PROMOTED_DIRECTORIES.put(
                "docs/studies/constellation-geography/",
                "build/constellation-study");
        PROMOTED_DIRECTORIES.put(
                "docs/studies/constellation-rendering/",
                "build/constellation-study");
        PROMOTED_DIRECTORIES.put("docs/studies/coordinate-grid/",
                "build/grid-study");
        PROMOTED_DIRECTORIES.put("docs/studies/bayer-notation/",
                "build/bayer-study");
        PROMOTED_DIRECTORIES.put("docs/studies/chart-options/",
                "build/chart-options-study");
        PROMOTED_DIRECTORIES.put("docs/studies/star-identity/",
                "build/star-identity-study");
    }

    /**
     * The generators whose raw sources are gitignored downloads.
     * Both discovered the same way: by the verifier failing on a
     * checkout without them - constellations at review, and the
     * star-identity study when the review's incomplete-fails-loudly
     * rule was rehearsed with imports/raw moved aside.
     */
    /** A gated generator's input directory and its exact fetch. */
    record Gate(Path input, String fetch) {
    }

    private static final Map<String, Gate> GATED_GENERATORS = Map.of(
            "juranometria.tool.ConstellationStudyMain",
            new Gate(Path.of("imports/raw/constellations"),
                    "scripts/download-constellation-sources.sh"),
            "juranometria.tool.StarIdentityStudyMain",
            new Gate(Path.of("imports/raw/star-identities"),
                    "scripts/download-constellation-sources.sh and"
                            + " scripts/download-catalogue-sources.sh"));

    /**
     * The incomplete-run breach for a gated family, or null when its
     * inputs are present. Extracted so the branch has a committed
     * regression test, and so the message carries the exact command
     * that completes the run (review).
     */
    static String incompleteBreach(String buildDir, Gate gate,
                                   boolean inputPresent) {
        if (inputPresent) {
            return null;
        }
        return "VERIFICATION INCOMPLETE: " + buildDir + "'s evidence"
                + " family was not verified - its raw sources ("
                + gate.input() + ") are gitignored downloads; run "
                + gate.fetch() + " and rerun";
    }

    /**
     * How a promoted file is judged against its generator match and
     * the residue pin - every branch a breach or a silence, none an
     * accepted baseline by accident. Extracted for its regression
     * tests (review).
     */
    static List<String> promotedPinBreaches(String path,
                                            boolean matchedByName) {
        boolean pinned = PROMOTED_WITHOUT_GENERATOR.contains(path);
        if (!matchedByName && !pinned) {
            return List.of(path + ": promoted file matches no"
                    + " generator output and is not in the pinned"
                    + " residue");
        }
        if (matchedByName && pinned) {
            return List.of(path + ": pinned as having no generator"
                    + " output, but a build output matches it by name"
                    + " - the pin is stale");
        }
        return List.of();
    }

    /** Pinned entries missing from the tree: stale the other way. */
    static List<String> stalePinBreaches(
            java.util.Set<String> treePaths) {
        List<String> breaches = new ArrayList<>();
        for (String pinned : PROMOTED_WITHOUT_GENERATOR) {
            if (!treePaths.contains(pinned)) {
                breaches.add(pinned + ": pinned residue file is"
                        + " missing from the tree - the pin is stale");
            }
        }
        return breaches;
    }

    /**
     * The promoted files no generator output matches by name -
     * variants composed by hand at their sprints. Recorded, held as
     * committed, and pinned: an eighth arrives by decision.
     */
    static final List<String> PROMOTED_WITHOUT_GENERATOR =
            List.of("docs/studies/bayer-notation/crux-18-greek-wide.png",
                    "docs/studies/constellation-rendering/lmc-36deg.png",
                    "docs/studies/bayer-notation/m31-08-greek-wide.png",
                    "docs/studies/bayer-notation/orion-36-greek-wide.png",
                    "docs/studies/bayer-notation/orion-36-lettered-both.png",
                    "docs/studies/coordinate-grid/m31-08-absent.png",
                    "docs/studies/coordinate-grid/m31-08-labelled.png",
                    "docs/studies/coordinate-grid/m31-08-lines-only.png");

    /** The byte-exact fixtures, pinned by digest. */
    public static final Map<String, String> FIXTURES = Map.of(
            "docs/studies/place-and-time/reference-vectors.txt",
            "f785c8a2015d9dfc930165484c05ed6fcd12b6de"
                    + "238cf3147fec335489336b4b",
            "scripts/reference-vectors.c",
            "baf6f526f4f22997a0e2fc73d5574b9566f491df"
                    + "b8a675c55ba56ca1300f1b3e");

    /** One committed file: its bytes and when it was last written. */
    record Snapshot(byte[] bytes,
                            java.nio.file.attribute.FileTime written) {
    }

    public static void main(String[] args) throws Exception {
        Map<String, Snapshot> committed = snapshot();
        List<String> failures = new ArrayList<>();
        Map<String, Integer> verdicts = new TreeMap<>();
        generateUnderRestoration(Path.of("docs/studies"), committed,
                () -> run(committed, failures, verdicts));
    }

    /** A generation step that may fail. */
    interface Generation {
        void run() throws Exception;
    }

    /**
     * The outer restoration path itself, extracted so a regression
     * test can throw a generator through the real finally rather
     * than calling the cleanup by hand (review): whatever the body
     * does - dying mid-run included - the inspection imagery goes
     * back to its committed bytes and inspection-class newcomers
     * are removed before the failure continues on its way.
     */
    static void generateUnderRestoration(Path root,
            Map<String, Snapshot> committed, Generation body)
            throws Exception {
        // The project's standing suppression rule (review): if the
        // generation and the restoration both fail, the evidence
        // failure is the one thrown and the cleanup's trouble rides
        // as suppressed - never the other way round.
        Throwable primary = null;
        try {
            body.run();
        } catch (Throwable failure) {
            primary = failure;
        }
        try {
            restoreInspectionImagery(root, committed);
        } catch (Throwable trouble) {
            if (primary == null) {
                primary = trouble;
            } else {
                primary.addSuppressed(trouble);
            }
        }
        if (primary instanceof Exception failure) {
            throw failure;
        }
        if (primary instanceof Error failure) {
            throw failure;
        }
    }

    /**
     * Puts every inspection-class file back to its snapshotted bytes
     * and removes inspection-class newcomers. Extracted so the
     * guarantee has regression tests of its own rather than a
     * rehearsal in a pull-request narrative (review).
     */
    static void restoreInspectionImagery(Path root,
            Map<String, Snapshot> committed) throws IOException {
        for (Map.Entry<String, Snapshot> entry : committed.entrySet()) {
            if (!inspectionClass(entry.getKey())) {
                continue;
            }
            Path path = Path.of(entry.getKey());
            if (!Files.exists(path)
                    || !java.util.Arrays.equals(
                            entry.getValue().bytes(),
                            Files.readAllBytes(path))) {
                Files.write(path, entry.getValue().bytes());
            }
        }
        try (Stream<Path> tree = Files.walk(root)) {
            for (Path file : tree.filter(Files::isRegularFile)
                    .sorted().toList()) {
                String key = file.toString().replace(
                        java.io.File.separatorChar, '/');
                if (!committed.containsKey(key)
                        && inspectionClass(key)) {
                    Files.delete(file);
                }
            }
        }
    }

    /** The newcomer breaches under a root, against a snapshot. */
    static List<String> newcomerBreaches(Path root,
            Map<String, Snapshot> committed) throws IOException {
        List<String> breaches = new ArrayList<>();
        try (Stream<Path> tree = Files.walk(root)) {
            for (Path file : tree.filter(Files::isRegularFile)
                    .sorted().toList()) {
                String key = file.toString().replace(
                        java.io.File.separatorChar, '/');
                if (!committed.containsKey(key)) {
                    breaches.add(key + ": generated but not committed"
                            + " - a new artifact arrives by commit and"
                            + " review, not by regeneration");
                }
            }
        }
        return breaches;
    }

    private static boolean inspectionClass(String path) {
        String cls = TestEvidenceScan.artifactClass(
                Path.of(path).getFileName().toString());
        return cls.equals("widget-rendered-inspection")
                || cls.equals("session-photograph");
    }

    private static void run(Map<String, Snapshot> committed,
                            List<String> failures,
                            Map<String, Integer> verdicts)
            throws Exception {

        // ---- deterministic reports, from stdout: no churn --------
        PrintStream realOut = System.out;
        for (Map.Entry<String, String> report : REPORT_MAINS.entrySet()) {
            ByteArrayOutputStream captured = new ByteArrayOutputStream();
            System.setOut(new PrintStream(captured, true, "UTF-8"));
            try {
                Class.forName(report.getKey())
                        .getMethod("main", String[].class)
                        .invoke(null, (Object) new String[0]);
            } finally {
                System.setOut(realOut);
            }
            Snapshot expectedSnapshot = committed.get(report.getValue());
            byte[] expected = expectedSnapshot == null ? null
                    : expectedSnapshot.bytes();
            if (expected == null) {
                failures.add(report.getValue() + ": committed report"
                        + " is missing");
            } else if (!java.util.Arrays.equals(expected,
                    captured.toByteArray())) {
                failures.add(report.getValue() + ": deterministic"
                        + " report did not reproduce byte-for-byte");
            } else {
                tally(verdicts, "reproduced");
            }
        }

        // ---- image generators, then judge every touched file ------
        for (String main : IMAGE_MAINS) {
            Class.forName(main).getMethod("main", String[].class)
                    .invoke(null, (Object) new String[0]);
        }
        Snapshot widgetMeasuredSnap = committed.get(WIDGET_MEASURED_REPORT);
        byte[] widgetMeasured = widgetMeasuredSnap == null ? null
                : widgetMeasuredSnap.bytes();
        if (widgetMeasured == null || widgetMeasured.length < 1000) {
            failures.add(WIDGET_MEASURED_REPORT + ": the widget-"
                    + "measured report is missing or empty");
        } else {
            tally(verdicts,
                    "widget-measured (display required; held to substance)");
        }
        // The legacy generators, compared against their promoted
        // docs directories. Paired per directory, never by a global
        // name map: two studies both promoted an
        // orion-36-everything.png, and the first draft compared one
        // of them against the other study's page of the same name.
        java.util.Set<String> judgedViaBuild = new java.util.TreeSet<>();
        java.util.Set<String> skippedBuildDirs = new java.util.TreeSet<>();
        for (Map.Entry<String, String> writer : BUILD_WRITERS.entrySet()) {
            Gate gate = GATED_GENERATORS.get(writer.getKey());
            String incomplete = gate == null ? null
                    : incompleteBreach(writer.getValue(), gate,
                            Files.isDirectory(gate.input()));
            if (incomplete != null) {
                skippedBuildDirs.add(writer.getValue());
                failures.add(incomplete);
                continue;
            }
            Class.forName(writer.getKey())
                    .getMethod("main", String[].class)
                    .invoke(null, (Object) new String[0]);
        }
        for (Map.Entry<String, String> pair
                : PROMOTED_DIRECTORIES.entrySet()) {
            if (skippedBuildDirs.contains(pair.getValue())) {
                continue;
            }
            Map<String, Path> outputs = new TreeMap<>();
            try (Stream<Path> tree =
                    Files.walk(Path.of(pair.getValue()))) {
                tree.filter(f -> f.toString().endsWith(".png"))
                        .forEach(f -> outputs.put(
                                f.getFileName().toString(), f));
            }
            for (String path : committed.keySet()) {
                if (!path.startsWith(pair.getKey())
                        || !path.endsWith(".png")) {
                    continue;
                }
                Path match = outputs.get(
                        Path.of(path).getFileName().toString());
                failures.addAll(promotedPinBreaches(path,
                        match != null));
                if (match == null) {
                    continue;
                }
                judgedViaBuild.add(path);
                if (java.util.Arrays.equals(
                        committed.get(path).bytes(),
                        Files.readAllBytes(match))) {
                    tally(verdicts, "reproduced (via generator build"
                            + " output)");
                } else {
                    failures.add(path + ": the promoted study page no"
                            + " longer matches its generator's output"
                            + " - the study has fallen behind the"
                            + " atlas");
                }
            }
        }

        failures.addAll(stalePinBreaches(committed.keySet()));

        // Newcomers first: a file the generation created that the
        // snapshot never held is an artifact nobody committed - a
        // breach whatever its class, and never silent (review). The
        // inspection-class ones are removed by the outer restoration.
        failures.addAll(newcomerBreaches(Path.of("docs/studies"),
                committed));
        for (Map.Entry<String, Snapshot> entry : committed.entrySet()) {
            String path = entry.getKey();
            if (path.endsWith(".md")) {
                continue; // judged above, from stdout
            }
            String cls = TestEvidenceScan.artifactClass(
                    Path.of(path).getFileName().toString());
            Path file = Path.of(path);
            byte[] now = Files.exists(file)
                    ? Files.readAllBytes(file) : null;
            boolean same = java.util.Arrays.equals(
                    entry.getValue().bytes(), now);
            boolean rewritten = Files.exists(file)
                    && !Files.getLastModifiedTime(file)
                            .equals(entry.getValue().written());
            switch (cls) {
                case "renderer-drawn" -> {
                    if (judgedViaBuild.contains(path)) {
                        // Compared against its generator's build
                        // output above.
                    } else if (!rewritten) {
                        tally(verdicts, same
                                ? (PROMOTED_WITHOUT_GENERATOR
                                        .contains(path)
                                        ? "promoted-without-generator"
                                                + " (pinned residue;"
                                                + " held as committed)"
                                        : "legacy-baseline (held as"
                                                + " committed)")
                                : failuresAdd(failures, path
                                        + ": legacy baseline changed"
                                        + " though nothing generates"
                                        + " it"));
                    } else if (same) {
                        tally(verdicts, "reproduced");
                    } else {
                        failures.add(path + ": renderer-drawn image"
                                + " did not reproduce byte-for-byte"
                                + " on this machine");
                    }
                }
                case "widget-rendered-inspection" -> {
                    if (!same) {
                        // Drift is the class's nature, not a defect;
                        // no inspection happened here, and the
                        // verdict must not claim one (review). The
                        // outer path restores the committed bytes.
                        tally(verdicts, "inspection-imagery drift"
                                + " restored - inspect before any"
                                + " recommit");
                    } else {
                        tally(verdicts, rewritten
                                ? "inspection-imagery regenerated"
                                        + " identical"
                                : "inspection-imagery unchanged");
                    }
                }
                case "session-photograph" -> {
                    if (!same) {
                        failures.add(path + ": session photograph"
                                + " changed though its generator was"
                                + " never run");
                    } else {
                        tally(verdicts, "deliberately-unchanged"
                                + " (session photograph)");
                    }
                }
                case "byte-exact-fixture" ->
                        tally(verdicts, "deliberately-unchanged"
                                + " (fixture)");
                default -> tally(verdicts, cls);
            }
        }

        // ---- fixtures, by digest -----------------------------------
        for (Map.Entry<String, String> fixture : FIXTURES.entrySet()) {
            String digest = juranometria.catalog.Sha256.hex(
                    Files.readAllBytes(Path.of(fixture.getKey())));
            if (!digest.equals(fixture.getValue())) {
                failures.add(fixture.getKey() + ": byte-exact fixture"
                        + " changed - a provenance event, not a"
                        + " regeneration: " + digest);
            } else {
                tally(verdicts, "checksum-verified");
            }
        }

        // ---- the canonical reference: named, not touched -----------
        realOut.println("docs/reference/*: canonical - compared"
                + " byte-for-byte against the packaged render in the"
                + " app-image job, its proper environment; never"
                + " regenerated here.");
        realOut.println("dialog-real*: session photographs - packed"
                + " geometry asserted by the lifecycle test; bytes are"
                + " illustrations and their generator needs a"
                + " display.");
        realOut.println();
        for (Map.Entry<String, Integer> verdict : verdicts.entrySet()) {
            realOut.printf("%5d  %s%n", verdict.getValue(),
                    verdict.getKey());
        }
        if (!failures.isEmpty()) {
            realOut.println();
            failures.forEach(f -> realOut.println("CONTRACT BREACH: " + f));
            System.exit(1);
        }
        realOut.println();
        realOut.println("EVIDENCE CONTRACTS OK");
    }

    private static Map<String, Snapshot> snapshot() throws IOException {
        return snapshot(Path.of("docs/studies"));
    }

    static Map<String, Snapshot> snapshot(Path root) throws IOException {
        Map<String, Snapshot> files = new TreeMap<>();
        try (Stream<Path> tree = Files.walk(root)) {
            for (Path file : tree.filter(Files::isRegularFile)
                    .sorted().toList()) {
                files.put(file.toString()
                                .replace(java.io.File.separatorChar, '/'),
                        new Snapshot(Files.readAllBytes(file),
                                Files.getLastModifiedTime(file)));
            }
        }
        return files;
    }

    /** Adds the failure and hands back a verdict label for tally. */
    private static String failuresAdd(List<String> failures,
                                      String failure) {
        failures.add(failure);
        return "contract-breach";
    }

    private static void tally(Map<String, Integer> verdicts,
                              String verdict) {
        verdicts.merge(verdict, 1, Integer::sum);
    }
}
