package juranometria.tool;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Stream;

/**
 * Regenerates the generated evidence and holds every artifact to its
 * own contract (Sprint 26, issue #242).
 *
 * <p>The classes and their contracts are the gate's
 * ({@code docs/decisions/test-evidence.md}); this makes them
 * executable. A clean run reports, per artifact, one of four
 * verdicts and exits nonzero if any contract is breached:
 *
 * <ul>
 *   <li><strong>reproduced</strong> - deterministic reports and
 *       renderer-drawn images regenerated byte-for-byte;</li>
 *   <li><strong>structurally-verified</strong> - held by the
 *       in-suite structural checks rather than by bytes;</li>
 *   <li><strong>visually-inspected</strong> - widget-rendered
 *       inspection artifacts whose regenerated bytes drifted are
 *       <em>restored from the committed snapshot</em> and reported,
 *       never silently churned: font rasterisation drift is not a
 *       product defect and must not look like one in git;</li>
 *   <li><strong>deliberately-unchanged</strong> - byte-exact
 *       fixtures (checksum-verified) and session photographs, whose
 *       generator needs a display and is not run here at all.</li>
 * </ul>
 *
 * <p>The whole committed tree under docs/studies is snapshotted into
 * memory before anything runs, so restoration needs no git and a
 * breach cannot destroy the evidence it failed against.
 */
public final class EvidenceContractMain {

    private EvidenceContractMain() {
    }

    /**
     * Every study generator except the session photographer, which
     * needs a display and refuses to run without one - its artifacts
     * are the session-photograph class, deliberately not regenerated
     * here. Reports are captured from stdout and compared against
     * the committed file the Makefile writes them to.
     */
    private static final Map<String, String> REPORT_MAINS =
            new LinkedHashMap<>();
    static {
        REPORT_MAINS.put("juranometria.tool.FurnitureStudyMain",
                "docs/studies/chart-furniture/measurements.md");
        REPORT_MAINS.put("juranometria.tool.IdentifyStudyMain",
                "docs/studies/point-and-identify/measurements.md");
        REPORT_MAINS.put("juranometria.tool.DeepSkyOcclusionStudyMain",
                "docs/studies/deep-sky-occlusion/measurements.md");
        REPORT_MAINS.put("juranometria.tool.ApplicationMarkStudyMain",
                "docs/studies/application-mark/measurements.md");
        REPORT_MAINS.put("juranometria.tool.OnThisPageStudyMain",
                "docs/studies/on-this-page/measurements.md");
        REPORT_MAINS.put("juranometria.tool.TestEvidenceStudyMain",
                "docs/studies/test-evidence/measurements.md");
        REPORT_MAINS.put("juranometria.tool.PlaceAndTimeStudyMain",
                "docs/studies/place-and-time/measurements.md");
    }

    /**
     * The one report whose byte claim could not be made executable
     * here, recorded as the issue requires: the deep-sky-vocabulary
     * measurements embed widget-measured dialog geometry, so its
     * bytes depend on a display and a look-and-feel. It is
     * regenerated with a display on the maintainer's machine and
     * inspected; the verifier only requires that it exists and that
     * nothing has silently emptied it.
     */
    private static final String WIDGET_MEASURED_REPORT =
            "docs/studies/deep-sky-vocabulary/measurements.md";

    private static final List<String> IMAGE_MAINS = List.of(
            "juranometria.tool.RegionalStudyMain",
            "juranometria.tool.ConstellationStudyMain",
            "juranometria.tool.PanStudyMain",
            "juranometria.tool.ChartOptionsStudyMain",
            "juranometria.tool.StarIdentityStudyMain",
            "juranometria.tool.ZoomStudyMain",
            "juranometria.tool.GridStudyMain",
            "juranometria.tool.BayerStudyMain",
            "juranometria.tool.IdentifyMockupMain",
            "juranometria.tool.OnThisPageMockupMain",
            "juranometria.tool.DeepSkyVocabularyMockupMain",
            "juranometria.tool.PlaceAndTimeInkStudyMain",
            "juranometria.tool.PlaceAndTimeControlsMockupMain");

    /** The byte-exact fixtures, pinned by digest. */
    public static final Map<String, String> FIXTURES = Map.of(
            "docs/studies/place-and-time/reference-vectors.txt",
            "f785c8a2015d9dfc930165484c05ed6fcd12b6de"
                    + "238cf3147fec335489336b4b",
            "scripts/reference-vectors.c",
            "baf6f526f4f22997a0e2fc73d5574b9566f491df"
                    + "b8a675c55ba56ca1300f1b3e");

    public static void main(String[] args) throws Exception {
        Map<String, byte[]> committed = snapshot();
        List<String> failures = new ArrayList<>();
        Map<String, Integer> verdicts = new TreeMap<>();

        // ---- deterministic reports, from stdout: no churn --------
        PrintStream realOut = System.out;
        for (Map.Entry<String, String> report : REPORT_MAINS.entrySet()) {
            ByteArrayOutputStream captured = new ByteArrayOutputStream();
            System.setOut(new PrintStream(captured, true, "UTF-8"));
            try {
                Class.forName(report.getKey())
                        .getMethod("main", String[].class)
                        .invoke(null, (Object) new String[0]);
            } finally {
                System.setOut(realOut);
            }
            byte[] expected = committed.get(report.getValue());
            if (expected == null) {
                failures.add(report.getValue() + ": committed report"
                        + " is missing");
            } else if (!java.util.Arrays.equals(expected,
                    captured.toByteArray())) {
                failures.add(report.getValue() + ": deterministic"
                        + " report did not reproduce byte-for-byte");
            } else {
                tally(verdicts, "reproduced");
            }
        }

        // ---- image generators, then judge every touched file ------
        for (String main : IMAGE_MAINS) {
            Class.forName(main).getMethod("main", String[].class)
                    .invoke(null, (Object) new String[0]);
        }
        byte[] widgetMeasured = committed.get(WIDGET_MEASURED_REPORT);
        if (widgetMeasured == null || widgetMeasured.length < 1000) {
            failures.add(WIDGET_MEASURED_REPORT + ": the widget-"
                    + "measured report is missing or empty");
        } else {
            tally(verdicts,
                    "widget-measured (display required; inspected)");
        }
        for (Map.Entry<String, byte[]> entry : committed.entrySet()) {
            String path = entry.getKey();
            if (path.endsWith(".md")) {
                continue; // judged above, from stdout
            }
            String cls = TestEvidenceScan.artifactClass(
                    Path.of(path).getFileName().toString());
            byte[] now = Files.exists(Path.of(path))
                    ? Files.readAllBytes(Path.of(path)) : null;
            boolean same = java.util.Arrays.equals(entry.getValue(), now);
            switch (cls) {
                case "renderer-drawn" -> {
                    if (same) {
                        tally(verdicts, "reproduced");
                    } else {
                        failures.add(path + ": renderer-drawn image"
                                + " did not reproduce byte-for-byte"
                                + " on this machine");
                    }
                }
                case "widget-rendered-inspection" -> {
                    if (!same) {
                        // Drift is the class's nature, not a defect:
                        // restore, and say so.
                        Files.write(Path.of(path), entry.getValue());
                        tally(verdicts,
                                "visually-inspected (drift restored)");
                    } else {
                        tally(verdicts, "visually-inspected");
                    }
                }
                case "session-photograph" -> {
                    if (!same) {
                        failures.add(path + ": session photograph"
                                + " changed though its generator was"
                                + " never run");
                    } else {
                        tally(verdicts, "deliberately-unchanged"
                                + " (session photograph)");
                    }
                }
                case "byte-exact-fixture" ->
                        tally(verdicts, "deliberately-unchanged"
                                + " (fixture)");
                default -> tally(verdicts, cls);
            }
        }

        // ---- fixtures, by digest -----------------------------------
        for (Map.Entry<String, String> fixture : FIXTURES.entrySet()) {
            String digest = juranometria.catalog.Sha256.hex(
                    Files.readAllBytes(Path.of(fixture.getKey())));
            if (!digest.equals(fixture.getValue())) {
                failures.add(fixture.getKey() + ": byte-exact fixture"
                        + " changed - a provenance event, not a"
                        + " regeneration: " + digest);
            } else {
                tally(verdicts, "checksum-verified");
            }
        }

        // ---- the canonical reference: named, not touched -----------
        realOut.println("docs/reference/*: canonical - compared"
                + " byte-for-byte against the packaged render in the"
                + " app-image job, its proper environment; never"
                + " regenerated here.");
        realOut.println("dialog-real*: session photographs - packed"
                + " geometry asserted by the lifecycle test; bytes are"
                + " illustrations and their generator needs a"
                + " display.");
        realOut.println();
        for (Map.Entry<String, Integer> verdict : verdicts.entrySet()) {
            realOut.printf("%5d  %s%n", verdict.getValue(),
                    verdict.getKey());
        }
        if (!failures.isEmpty()) {
            realOut.println();
            failures.forEach(f -> realOut.println("CONTRACT BREACH: " + f));
            System.exit(1);
        }
        realOut.println();
        realOut.println("EVIDENCE CONTRACTS OK");
    }

    private static Map<String, byte[]> snapshot() throws IOException {
        Map<String, byte[]> bytes = new TreeMap<>();
        try (Stream<Path> tree = Files.walk(Path.of("docs/studies"))) {
            for (Path file : tree.filter(Files::isRegularFile)
                    .sorted().toList()) {
                bytes.put(file.toString()
                                .replace(java.io.File.separatorChar, '/'),
                        Files.readAllBytes(file));
            }
        }
        return bytes;
    }

    private static void tally(Map<String, Integer> verdicts,
                              String verdict) {
        verdicts.merge(verdict, 1, Integer::sum);
    }
}
