package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.SwingUtilities;

import juranometria.app.Atlas;
import juranometria.app.ExportSheet;
import juranometria.app.ExportSheetDialog;
import juranometria.sheet.PaperSize;
import juranometria.sheet.SheetFormat;
import juranometria.ui.language.InterfaceText;

/**
 * The export dialog and the journey after it, in both languages
 * (Sprint 33, issue #350).
 *
 * <p>It installs its own look and feel before any component exists
 * (#362), and it draws the dialog in a real packed window because the
 * explanation beneath the format control wraps against font metrics.
 *
 * <p>The companion separates what was <strong>observed</strong> from
 * what is only <strong>supported</strong>. Three application-owned
 * forms cannot be reached at runtime without architecture added
 * solely to make them fail; they are held by whole patterns and by a
 * source contract, and they are listed apart so nobody reads them as
 * pictures of states anyone has seen.
 */
public final class ExportSheetDialogSheetMain {

    private ExportSheetDialogSheetMain() {
    }

    private static final Path OUT =
            Path.of("docs/studies/interface-language");

    private record State(String name, String title, SheetFormat format,
                         PaperSize paper, boolean marks) {
    }

    private static final List<State> STATES = List.of(
            new State("svg-a4", "SVG on A4, marks off", SheetFormat.SVG,
                    PaperSize.A4, false),
            new State("pdf-letter", "PDF on US Letter, marks on",
                    SheetFormat.PDF, PaperSize.LETTER, true),
            new State("png-a4", "PNG on A4, resolution in use",
                    SheetFormat.PNG, PaperSize.A4, false));

    public static void main(String[] args) throws Exception {
        Files.createDirectories(OUT);
        StringBuilder said = new StringBuilder();
        said.append("""
                # Every word exporting a chart sheet says

                Issue #350. Generated by
                `juranometria.tool.ExportSheetDialogSheetMain` from
                compiled application classes and their classpath
                resources. Packaged acceptance separately verifies
                that the interface language resources ship in the
                application image.

                Norwegian is **draft**.

                ## What is translated, and what is not

                `SVG`, `PDF`, `PNG`, `A4` and `US Letter` are format
                and paper identities: the same to every reader, handed
                to sentences as arguments, and written into no
                translated value. File names, folders and resolutions
                are data. The byte count goes in as a NUMBER, so each
                language groups it its own way.

                """);

        int sheet = 1;
        for (String language : List.of("en", "nb-NO")) {
            InterfaceText text = InterfaceText.forLanguage(language);
            said.append("## ").append(language.equals("en") ? "English"
                    : "Norsk bokmål").append(" (`").append(language)
                    .append("`)\n\n");
            for (State state : STATES) {
                said.append("### ").append(state.title()).append("\n\n")
                        .append(draw(text, state,
                                OUT.resolve("export-" + language + "-"
                                        + (sheet++) + "-" + state.name()
                                        + ".png")))
                        .append('\n');
            }
            said.append(journey(text));
        }
        said.append(supportedButUnobserved());
        Files.writeString(OUT.resolve("export-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("export sheets: 6 images and "
                + OUT.resolve("export-strings.md"));
    }

    /** The rest of the journey, which has no window of its own here. */
    private static String journey(InterfaceText said) throws Exception {
        Path folder = Files.createTempDirectory("export-sheet");
        StringBuilder out = new StringBuilder(
                "#### After Export is pressed\n\n| what | words |\n|---|---|\n");
        row(out, "chooser title", said.say("export.chooser.title"));
        row(out, "replace title", said.say("export.replace.title"));
        row(out, "replace question", said.say("export.replace.question",
                "orion.svg", folder.toString()));
        row(out, "written title", said.say("export.written.title"));

        ExportSheet.Outcome written = write(folder.resolve("orion.svg").toFile(),
                ExportSheet.ReplaceDecision.REFUSE, said);
        if (written instanceof ExportSheet.Outcome.Written ok) {
            row(out, "written message", ok.message(said));
        }
        row(out, "refused title", said.say("export.refused.title"));
        row(out, "refusal: no file", reasonOf(write(null,
                ExportSheet.ReplaceDecision.REFUSE, said)));
        Path directory = Files.createDirectory(folder.resolve("a.svg"));
        row(out, "refusal: a folder", reasonOf(write(directory.toFile(),
                ExportSheet.ReplaceDecision.REFUSE, said)));
        row(out, "refusal: kept", reasonOf(write(
                folder.resolve("orion.svg").toFile(),
                ExportSheet.ReplaceDecision.REFUSE, said)));
        // The two write-failure forms need the package-private
        // ByteSink seam, which lives in juranometria.app and is not
        // widened for a photograph. They ARE reached at runtime, by
        // ExportLanguageTest through that seam; what is shown here is
        // the same pattern with the same argument.
        row(out, "refusal: write failed, new file (reached in test)",
                said.say("export.refused.notwritten", "fresh.svg"));
        row(out, "refusal: write failed, existing file (reached in test)",
                said.say("export.refused.notreplaced", "orion.svg"));
        return out.append('\n').toString();
    }

    /** Held by contract, not observed - and said so. */
    private static String supportedButUnobserved() {
        StringBuilder out = new StringBuilder(
                "## Supported, but not observed here\n\n"
                + "These are whole patterns held by `ExportLanguageTest` and by"
                + " a source contract. They are **not** pictures of states"
                + " anyone has seen: reaching them would need architecture"
                + " added solely to make the application fail on command, or"
                + " filesystem permissions that are not portable.\n\n"
                + "| form | English | Norsk bokmål | why unobserved |\n"
                + "|---|---|---|---|\n");
        InterfaceText en = InterfaceText.forLanguage("en");
        InterfaceText nb = InterfaceText.forLanguage("nb-NO");
        String[][] rows = {
                {"export.refused.notmade", "the recorder and writers offer no"
                        + " deterministic failure input"},
                {"export.refused.unwritable", "needs a non-portable permission"
                        + " change"},
                {"export.refused.foldernotwritable", "needs a non-portable"
                        + " permission change"}};
        for (String[] r : rows) {
            out.append("| `").append(r[0]).append("` | ")
                    .append(en.say(r[0], "orion.svg")).append(" | ")
                    .append(nb.say(r[0], "orion.svg")).append(" | ")
                    .append(r[1]).append(" |\n");
        }
        return out.toString();
    }

    private static ExportSheet.Outcome write(File destination,
                                             ExportSheet.ReplaceDecision replace,
                                             InterfaceText said) {
        return ExportSheet.write(
                (state, wide, high) -> Atlas.assembler()
                        .assemble(state, wide, high),
                juranometria.chart.ChartViewState.DEFAULT,
                juranometria.render.ChartOptions.DEFAULTS,
                juranometria.render.ChartRenderer.ReferenceLayer.NONE,
                new ExportSheet.Request(SheetFormat.SVG, PaperSize.A4,
                        150, false),
                destination, replace, said);
    }

    private static String reasonOf(ExportSheet.Outcome outcome) {
        return outcome instanceof ExportSheet.Outcome.Refused refused
                ? refused.reason() : "(not refused: " + outcome + ")";
    }

    private static void row(StringBuilder out, String what, String words) {
        out.append("| ").append(what).append(" | ")
                .append(words.replace("|", "\\|").replace("\n", " / "))
                .append(" |\n");
    }

    /** Draws one state in one language and returns its strings. */
    private static String draw(InterfaceText said, State state, Path to)
            throws Exception {
        JFrame[] owner = new JFrame[1];
        JComponent[] content = new JComponent[1];
        try {
            SwingUtilities.invokeAndWait(() -> {
                juranometria.app.UiTheme.apply(false);
                content[0] = ExportSheetDialog.contentForStudy(said);
                owner[0] = new JFrame("study");
                owner[0].setContentPane(content[0]);
                owner[0].pack();
                choose(content[0], "export.format", state.format());
                choose(content[0], "export.paper", state.paper());
                Component marks = find(content[0], "export.working");
                if (marks instanceof JCheckBox box) {
                    box.setSelected(state.marks());
                }
                owner[0].pack();
            });
            SwingUtilities.invokeAndWait(() -> { });
            return capture(content[0], to);
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (owner[0] != null) {
                    owner[0].dispose();
                }
            });
        }
    }

    private static String capture(JComponent content, Path to)
            throws Exception {
        Set<String> said = new LinkedHashSet<>();
        BufferedImage[] image = new BufferedImage[1];
        SwingUtilities.invokeAndWait(() -> {
            BufferedImage drawn = new BufferedImage(
                    Math.max(1, content.getWidth()),
                    Math.max(1, content.getHeight()),
                    BufferedImage.TYPE_INT_RGB);
            Graphics2D g = drawn.createGraphics();
            try {
                g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                        RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, drawn.getWidth(), drawn.getHeight());
                content.paint(g);
            } finally {
                g.dispose();
            }
            image[0] = drawn;
            collect(content, said);
        });
        ImageIO.write(image[0], "png", to.toFile());
        StringBuilder out = new StringBuilder();
        out.append("![](").append(to.getFileName()).append(")\n\n")
                .append("Packed ").append(image[0].getWidth()).append(" × ")
                .append(image[0].getHeight()).append(" px.\n\n")
                .append("| shown, hovered or spoken |\n|---|\n");
        for (String one : said) {
            out.append("| ").append(one.replace("|", "\\|")).append(" |\n");
        }
        return out.toString();
    }

    @SuppressWarnings("unchecked")
    private static void collect(Container from, Set<String> said) {
        if (from instanceof JComponent self) {
            record(self, said);
        }
        for (Component child : from.getComponents()) {
            if (child instanceof JComponent widget) {
                record(widget, said);
            }
            if (child instanceof Container nested) {
                collect(nested, said);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static void record(JComponent widget, Set<String> said) {
        String off = widget.isEnabled() ? "" : " [unavailable]";
        if (widget instanceof AbstractButton button) {
            add(said, button.getText(), off);
        }
        if (widget instanceof JLabel label) {
            add(said, label.getText(), off);
        }
        if (widget instanceof JComboBox) {
            JComboBox<Object> box = (JComboBox<Object>) widget;
            ListCellRenderer<Object> renderer =
                    (ListCellRenderer<Object>) box.getRenderer();
            JList<Object> list = new JList<>();
            for (int i = 0; i < box.getItemCount(); i++) {
                Component cell = renderer.getListCellRendererComponent(
                        list, box.getItemAt(i), i, false, false);
                if (cell instanceof JLabel label) {
                    add(said, label.getText(), off);
                }
            }
        }
        add(said, widget.getToolTipText(), off);
        if (widget.getAccessibleContext() != null) {
            add(said, widget.getAccessibleContext().getAccessibleName(), off);
            add(said, widget.getAccessibleContext()
                    .getAccessibleDescription(), off);
        }
    }

    private static void add(Set<String> said, String text, String off) {
        if (text == null || text.isBlank()) {
            return;
        }
        said.add(text.replaceAll("<[^>]*>", " ")
                .replaceAll("\\s+", " ").trim() + off);
    }

    @SuppressWarnings("unchecked")
    private static void choose(Container root, String name, Object value) {
        Component found = find(root, name);
        if (found instanceof JComboBox) {
            ((JComboBox<Object>) found).setSelectedItem(value);
        }
    }

    private static Component find(Container root, String name) {
        for (Component child : root.getComponents()) {
            if (name.equals(child.getName())) {
                return child;
            }
            if (child instanceof Container nested) {
                Component found = find(nested, name);
                if (found != null) {
                    return found;
                }
            }
        }
        return null;
    }
}
