package juranometria.tool;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * The public gallery's pages, generated from its one manifest
 * (Sprint 27, issue #252).
 *
 * <p>The manifest is the single record the issue asks for - title,
 * caption, region and field, ink attribution, source artifact and
 * provenance, alt text - and the HTML is derived from it, so the
 * pages and the record cannot drift apart: a curation change is a
 * manifest change, regenerated by {@code make gallery} and held
 * byte-identical by the gallery test. Plain static HTML; the one
 * small script and the stylesheet are committed assets this
 * generator does not touch. Every slide is a page of its own with
 * a direct URL, readable with no script at all.
 */
public final class GalleryMain {

    private GalleryMain() {
    }

    private static final Path DIR = Path.of("docs/gallery");

    public static void main(String[] args) throws IOException {
        if (args.length == 2 && args[0].equals("site")) {
            generateSite(DIR, Path.of(args[1]));
            System.out.println("gallery site assembled in " + args[1]);
            return;
        }
        generate(DIR, DIR);
        System.out.println("gallery: pages written to " + DIR);
    }

    /**
     * Assembles the publishable site (issue #253): the same pages,
     * derived from the same manifest, with the slide images copied
     * in byte-identically beside them - self-contained, so Pages
     * uploads one directory and the evidence artifacts under
     * docs/studies stay exactly where and what they are. The copies
     * are not re-encoded: every page is already a compact
     * monochrome PNG, and an "optimized" lossy copy would weaken
     * the evidence it shows.
     */
    static void generateSite(Path manifestDir, Path out)
            throws IOException {
        generate(manifestDir, out, true);
        Files.createDirectories(out.resolve("images"));
        Map<String, Object> manifest = MiniJson.object(MiniJson.parse(
                Files.readString(manifestDir.resolve("manifest.json"),
                        StandardCharsets.UTF_8)));
        java.util.Set<String> basenames = new java.util.HashSet<>();
        for (Object entry : MiniJson.array(manifest.get("slides"))) {
            Map<String, Object> slide = MiniJson.object(entry);
            Path source = Path.of(text(slide, "source"));
            String basename = source.getFileName().toString();
            if (!basenames.add(basename)) {
                throw new IllegalStateException("two slides share the"
                        + " image basename " + basename
                        + " - the site's flat images/ needs distinct"
                        + " names");
            }
            Files.copy(source, out.resolve("images").resolve(basename),
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        }
        for (String asset : new String[] {"gallery.css", "gallery.js"}) {
            Files.copy(manifestDir.resolve(asset), out.resolve(asset),
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        }
    }

    /**
     * Generates every page from the manifest beside it - into the
     * gallery itself in production, into a scratch directory in the
     * regression test that holds the committed pages byte-identical
     * to what the manifest derives.
     */
    static void generate(Path manifestDir, Path out) throws IOException {
        generate(manifestDir, out, false);
    }

    private static void generate(Path manifestDir, Path out,
                                 boolean site) throws IOException {
        Map<String, Object> manifest = MiniJson.object(MiniJson.parse(
                Files.readString(manifestDir.resolve("manifest.json"),
                        StandardCharsets.UTF_8)));
        List<Map<String, Object>> rooms = new ArrayList<>();
        for (Object room : MiniJson.array(manifest.get("rooms"))) {
            rooms.add(MiniJson.object(room));
        }
        List<Map<String, Object>> slides = new ArrayList<>();
        for (Object slide : MiniJson.array(manifest.get("slides"))) {
            slides.add(MiniJson.object(slide));
        }

        Files.createDirectories(out.resolve("slides"));
        write(out.resolve("index.html"),
                index(manifest, rooms, slides, site));
        for (int i = 0; i < slides.size(); i++) {
            Map<String, Object> slide = slides.get(i);
            write(out.resolve("slides")
                            .resolve(text(slide, "slug") + ".html"),
                    slidePage(manifest, rooms, slides, i, site));
        }
    }

    // ---- the index -------------------------------------------------

    private static String index(Map<String, Object> manifest,
                                List<Map<String, Object>> rooms,
                                List<Map<String, Object>> slides,
                                boolean site) {
        StringBuilder html = new StringBuilder();
        html.append(head(text(manifest, "title"), "gallery.css"));
        html.append("<body>\n<header>\n");
        html.append("<h1>").append(esc(text(manifest, "title")))
                .append("</h1>\n");
        html.append("<p class=\"strapline\">")
                .append(esc(text(manifest, "strapline")))
                .append("</p>\n</header>\n<main>\n");
        for (Map<String, Object> room : rooms) {
            String id = text(room, "id");
            html.append("<section id=\"").append(esc(id))
                    .append("\" aria-labelledby=\"").append(esc(id))
                    .append("-name\">\n");
            html.append("<h2 id=\"").append(esc(id)).append("-name\">")
                    .append(esc(text(room, "name"))).append("</h2>\n");
            html.append("<p>").append(esc(text(room, "lead")))
                    .append("</p>\n<ul class=\"slides\">\n");
            for (Map<String, Object> slide : slides) {
                if (!id.equals(text(slide, "room"))) {
                    continue;
                }
                html.append("<li><a href=\"slides/")
                        .append(esc(text(slide, "slug")))
                        .append(".html\">");
                html.append("<img src=\"")
                        .append(esc(site ? "images/" + basenameOf(slide)
                                : "../" + sourceFromGallery(slide)))
                        .append("\" alt=\"").append(esc(text(slide, "alt")))
                        .append("\" loading=\"lazy\">");
                html.append("<span>").append(esc(text(slide, "title")));
                if ("ui".equals(text(slide, "kind"))) {
                    html.append(" <em class=\"ui-badge\">UI</em>");
                }
                html.append("</span></a></li>\n");
            }
            html.append("</ul>\n</section>\n");
        }
        html.append(footer(manifest, ""));
        html.append("</main>\n</body>\n</html>\n");
        return html.toString();
    }

    // ---- one slide -------------------------------------------------

    private static String slidePage(Map<String, Object> manifest,
                                    List<Map<String, Object>> rooms,
                                    List<Map<String, Object>> slides,
                                    int at, boolean site) {
        Map<String, Object> slide = slides.get(at);
        Map<String, Object> previous = at > 0 ? slides.get(at - 1) : null;
        Map<String, Object> next =
                at + 1 < slides.size() ? slides.get(at + 1) : null;

        StringBuilder html = new StringBuilder();
        html.append(head(text(slide, "title") + " — "
                + text(manifest, "title"), "../gallery.css"));
        html.append("<body class=\"slide\">\n<nav aria-label=\"Gallery\">\n");
        html.append("<a href=\"../index.html\">Index</a>\n");
        if (previous != null) {
            html.append("<a rel=\"prev\" href=\"")
                    .append(esc(text(previous, "slug")))
                    .append(".html\">&#8592; ")
                    .append(esc(text(previous, "title")))
                    .append("</a>\n");
        }
        if (next != null) {
            html.append("<a rel=\"next\" href=\"")
                    .append(esc(text(next, "slug")))
                    .append(".html\">").append(esc(text(next, "title")))
                    .append(" &#8594;</a>\n");
        }
        html.append("</nav>\n<main>\n");
        html.append("<p class=\"room\">").append(esc(roomName(rooms,
                text(slide, "room"))));
        if ("ui".equals(text(slide, "kind"))) {
            html.append(" &middot; <em class=\"ui-badge\">Application"
                    + " UI</em>");
        }
        html.append("</p>\n");
        html.append("<h1>").append(esc(text(slide, "title")))
                .append("</h1>\n");
        html.append("<figure>\n<img src=\"")
                .append(esc(site ? "../images/" + basenameOf(slide)
                        : "../../" + sourceFromGallery(slide)))
                .append("\" alt=\"").append(esc(text(slide, "alt")))
                .append("\">\n");
        html.append("<figcaption>").append(esc(text(slide, "caption")))
                .append("</figcaption>\n</figure>\n");
        html.append("<dl class=\"provenance\">\n");
        detail(html, "Region", text(slide, "region"));
        detail(html, "Field", text(slide, "field"));
        detail(html, "Ink", text(slide, "ink"));
        detail(html, "Source", text(slide, "source"));
        detail(html, "Produced", text(slide, "produced"));
        html.append("</dl>\n");
        html.append(footer(manifest, "../"));
        html.append("</main>\n<script src=\"../gallery.js\"></script>\n");
        html.append("</body>\n</html>\n");
        return html.toString();
    }

    // ---- shared pieces ---------------------------------------------

    private static String head(String title, String css) {
        return "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
                + "<meta charset=\"utf-8\">\n"
                + "<meta name=\"viewport\" content=\"width=device-width,"
                + " initial-scale=1\">\n"
                + "<title>" + esc(title) + "</title>\n"
                + "<link rel=\"stylesheet\" href=\"" + esc(css) + "\">\n"
                + "</head>\n";
    }

    private static String footer(Map<String, Object> manifest,
                                 String toRoot) {
        return "<footer>\n<p>Downloads: <a href=\""
                + esc(text(manifest, "downloads"))
                + "\">the GitHub release</a> (release "
                + esc(text(manifest, "release"))
                + "). Source and documentation: <a href=\""
                + esc(text(manifest, "repository"))
                + "\">the repository</a>.</p>\n</footer>\n";
    }

    private static void detail(StringBuilder html, String name,
                               String value) {
        if (value == null || value.isBlank()) {
            return;
        }
        html.append("<dt>").append(esc(name)).append("</dt><dd>")
                .append(esc(value)).append("</dd>\n");
    }

    private static String roomName(List<Map<String, Object>> rooms,
                                   String id) {
        for (Map<String, Object> room : rooms) {
            if (id.equals(text(room, "id"))) {
                return text(room, "name");
            }
        }
        throw new IllegalStateException("a slide names a room the"
                + " manifest does not define: " + id);
    }

    private static String basenameOf(Map<String, Object> slide) {
        return Path.of(text(slide, "source")).getFileName().toString();
    }

    /** The source path relative to docs/, for ../-prefixed links. */
    private static String sourceFromGallery(Map<String, Object> slide) {
        String source = text(slide, "source");
        if (!source.startsWith("docs/")) {
            throw new IllegalStateException("a slide's source lives"
                    + " under docs/, stated repo-relative: " + source);
        }
        return source.substring("docs/".length());
    }

    static String text(Map<String, Object> map, String key) {
        Object value = map.get(key);
        return value == null ? "" : value.toString();
    }

    static String esc(String text) {
        return text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;");
    }

    private static void write(Path path, String content)
            throws IOException {
        Files.writeString(path, content, StandardCharsets.UTF_8);
    }
}
