package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

import juranometria.app.Atlas;
import juranometria.app.InspectorPanel;
import juranometria.chart.ChartScene;
import juranometria.chart.ChartViewState;
import juranometria.chart.Selection;
import juranometria.chart.SelectionModel;
import juranometria.chart.SkyPosition;
import juranometria.chart.Star;
import juranometria.render.ChartOptions;
import juranometria.ui.language.InterfaceText;

/**
 * The Inspector, in both languages, for owner review
 * (Sprint 33, issue #350).
 *
 * <p>One surface with several kinds of subject, so one screenshot
 * would review almost none of it. Each representative state is drawn
 * separately, in a real window at the width the panel prefers.
 *
 * <p>The companion carries what the pictures cannot: tooltips,
 * accessible names and spoken descriptions, and the one size form
 * that <strong>no catalogue object can produce</strong> - a single
 * recorded axis with a position angle. That shape is supported and
 * synthetic-only; it is recorded there rather than fabricated into a
 * picture, because a checkpoint image of a catalogue state that does
 * not exist would be a lie about the data.
 */
public final class InspectorSheetMain {

    private InspectorSheetMain() {
    }

    private static final Path OUT = Path.of("docs/studies/interface-language");

    public static void main(String[] args) throws Exception {
        Files.createDirectories(OUT);
        SwingUtilities.invokeAndWait(() -> juranometria.app.UiTheme.apply(false));

        StringBuilder said = new StringBuilder("""
                # Every word the Inspector says

                Issue #350. Generated by
                `juranometria.tool.InspectorSheetMain` from compiled
                application classes and their classpath resources.
                Packaged acceptance separately verifies that the
                interface language resources ship in the application
                image.

                One surface, several kinds of subject. Each state is
                drawn separately because a reader meets one at a time
                and a single screenshot would review almost none of
                it.

                %s

                ## A shape no picture here can show

                `inspector.size.across.pa` states an extent measured on
                one axis together with its orientation. The data model
                permits it and the atlas supports it, but the shipped
                catalogue contains **zero** such records out of 13,371,
                so no page can be photographed showing it. It is held
                by a constructed object in `InspectorPanelTest`, in
                both languages:

                | | |
                |---|---|
                | English | `3.4′ across at PA 17°` |
                | Norsk bokmål | `3.4′ tvers over ved PA 17°` |

                It is recorded here rather than fabricated into an
                image, because a checkpoint picture of catalogue data
                that does not exist would be a lie about the data.

                ## Why one sentence is on two lines

                The empty-sky explanation wraps. English says it in
                297 px and the panel's width was settled around that;
                Norwegian needs 400 and lost its ending. Owner ruling,
                2026-09-18: there is ample vertical room, so the
                sentence breaks rather than the translation being cut
                to fit an English measurement. Where a line falls
                belongs to a width, so the rows below report each
                fact as the whole sentence it is.

                The general hint on the no-selection state still
                truncates. It behaves as a hint, and it truncates in
                both languages rather than in one.

                """.formatted(juranometria.tool.InterfaceLanguageStatus
                        .statement("nb-NO")));

        ChartViewState where = new ChartViewState(new SkyPosition(83.8, 0.0),
                42.0, ChartViewState.defaultMagnitudeFor(42.0));
        for (String language : List.of("en", "nb-NO")) {
            ChartScene scene = Atlas.assemblerNamedIn("latin")
                    .assemble(where, 900, 700);
            said.append("## ").append(language.equals("en") ? "English"
                    : "Norsk bokmål").append(" (`").append(language)
                    .append("`)\n\n");
            int sheet = 1;
            for (String state : List.of("none", "emptysky", "star",
                    "deepsky", "ambiguous", "workingset")) {
                said.append("### ").append(title(state)).append("\n\n")
                        .append("| shown | hovered | spoken as | read out |\n")
                        .append("|---|---|---|---|\n")
                        .append(draw(language, state, scene,
                                OUT.resolve("inspector-" + language + "-"
                                        + (sheet++) + "-" + state + ".png")))
                        .append('\n');
            }
        }
        Files.writeString(OUT.resolve("inspector-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("inspector sheets: 12 images and "
                + OUT.resolve("inspector-strings.md"));
    }

    private static String title(String state) {
        return switch (state) {
            case "none" -> "Nothing selected";
            case "emptysky" -> "A point with no catalogued object";
            case "star" -> "A named star";
            case "deepsky" -> "A deep-sky object";
            case "ambiguous" -> "Several objects at one point";
            default -> "The working set";
        };
    }

    /** Draws one state and returns its strings as table rows. */
    private static String draw(String language, String state,
                               ChartScene scene, Path to) throws Exception {
        java.util.prefs.Preferences node = java.util.prefs.Preferences
                .userRoot().node("juranometria-study-inspector-"
                        + System.nanoTime());
        JFrame[] owner = new JFrame[1];
        InspectorPanel[] panel = new InspectorPanel[1];
        try {
            SelectionModel selection = new SelectionModel();
            juranometria.chart.WorkingSelection working =
                    new juranometria.chart.WorkingSelection();
            SwingUtilities.invokeAndWait(() -> {
                owner[0] = new JFrame("study");
                panel[0] = new InspectorPanel(selection, () -> scene,
                        () -> ChartOptions.DEFAULTS, chosen -> { },
                        InterfaceText.forLanguage(language));
                owner[0].setContentPane(panel[0]);
                arrange(state, scene, selection, working, panel[0]);
                owner[0].pack();
            });
            SwingUtilities.invokeAndWait(() -> { });
            JComponent content = panel[0];
            BufferedImage image = new BufferedImage(
                    Math.max(1, content.getWidth()),
                    Math.max(1, content.getHeight()),
                    BufferedImage.TYPE_INT_RGB);
            Graphics2D g = image.createGraphics();
            try {
                g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                        RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, image.getWidth(), image.getHeight());
                content.paint(g);
            } finally {
                g.dispose();
            }
            ImageIO.write(image, "png", to.toFile());
            return describe(content);
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (owner[0] != null) {
                    owner[0].dispose();
                }
            });
            node.removeNode();
        }
    }

    private static void arrange(String state, ChartScene scene,
                                SelectionModel selection,
                                juranometria.chart.WorkingSelection working,
                                InspectorPanel panel) {
        switch (state) {
            case "emptysky" -> selection.selectEmptySky(
                    new SkyPosition(84.0, -1.5));
            case "star" -> star(scene).ifPresent(s -> selection.select(
                    new Selection.Object(Selection.Object.Kind.STAR,
                            s.id(), s.position())));
            case "deepsky" -> {
                if (!scene.deepSkyObjects().isEmpty()) {
                    var dso = scene.deepSkyObjects().get(0);
                    selection.select(new Selection.Object(
                            Selection.Object.Kind.DEEP_SKY, dso.id(),
                            dso.position()));
                }
            }
            case "ambiguous" -> star(scene).ifPresent(s -> {
                if (!scene.deepSkyObjects().isEmpty()) {
                    var dso = scene.deepSkyObjects().get(0);
                    selection.selectAmong(List.of(
                            new Selection.Object(Selection.Object.Kind.STAR,
                                    s.id(), s.position()),
                            new Selection.Object(
                                    Selection.Object.Kind.DEEP_SKY,
                                    dso.id(), dso.position())));
                }
            });
            case "workingset" -> {
                juranometria.page.PageContents page =
                        juranometria.page.PageInventory.of(scene,
                                ChartOptions.DEFAULTS);
                if (!page.entries().isEmpty()) {
                    working.add(page.entries().get(0).identity());
                }
                working.add("NGC 7000");
                panel.showWorkingSet(working, () -> page);
                working.lead(page.entries().isEmpty() ? "NGC 7000"
                        : page.entries().get(0).identity());
            }
            default -> { }
        }
    }

    private static java.util.Optional<Star> star(ChartScene scene) {
        return scene.stars().stream()
                .filter(s -> s.identity() != null
                        && s.identity().name() != null)
                .findFirst();
    }

    private static String describe(Component from) {
        StringBuilder rows = new StringBuilder();
        for (Component control : reading(from)) {
            if (!(control instanceof JComponent said)) {
                continue;
            }
            String shown = control instanceof AbstractButton button
                    ? button.getText()
                    : control instanceof JLabel label ? label.getText() : null;
            String hovered = said.getToolTipText();
            String name = said.getAccessibleContext() == null ? null
                    : said.getAccessibleContext().getAccessibleName();
            String read = said.getAccessibleContext() == null ? null
                    : said.getAccessibleContext().getAccessibleDescription();
            if (blank(shown) && blank(hovered) && blank(name) && blank(read)) {
                continue;
            }
            rows.append("| ").append(cell(shown))
                    .append(" | ").append(cell(hovered))
                    .append(" | ").append(cell(name))
                    .append(" | ").append(cell(read)).append(" |\n");
        }
        return rows.toString();
    }

    private static boolean blank(String text) {
        return text == null || text.isBlank();
    }

    /** Tags become boundaries, never deletions: a wrap is a space. */
    private static String cell(String text) {
        if (blank(text)) {
            return "—";
        }
        return text.replaceAll("<[^>]*>", " ")
                .replace("&nbsp;", " ")
                .replaceAll("\\s+", " ").trim().replace("|", "\\|");
    }

    private static List<Component> reading(Component from) {
        List<Component> found = new ArrayList<>();
        if (!(from instanceof Container container)) {
            return found;
        }
        for (Component child : container.getComponents()) {
            found.add(child);
            found.addAll(reading(child));
        }
        return found;
    }
}
