package juranometria.tool;

import java.io.IOException;

import juranometria.solar.JovianSystemService;

/**
 * The Jovian service's accuracy against JPL Horizons, as a kept
 * report (issue #473): every quantity's worst difference by body and
 * era over the committed fixtures, every state disagreement and every
 * oblate-against-sphere boundary row named, and the named evening's
 * ingress and egress minutes under each definition. Deterministic:
 * the service and the fixtures are fixed, the numbers are rounded.
 * Written to {@code docs/studies/jovian-system/service-accuracy.md}
 * by {@code make jovian-accuracy-report}; the tests hold the same
 * engine's results to the ruled targets.
 */
public final class JovianAccuracyReportMain {

    private JovianAccuracyReportMain() {
    }

    public static void main(String[] args) throws IOException {
        JovianSystemService service = JovianSystemService.load();
        JovianComparison.Result result = new JovianComparison(service).run();
        StringBuilder out = new StringBuilder();
        out.append("# The Jovian service against Horizons (#473)\n\n")
                .append("Generated by `juranometria.tool.JovianAccuracyReportMain`")
                .append(" (`make jovian-accuracy-report`) from the service over the")
                .append(" bundled packs and the Horizons responses kept under")
                .append(" `horizons/`; `JovianReferenceVectorTest` holds these numbers")
                .append(" to the targets ruled on #472. Observers at sea level, UT1 = UTC,")
                .append(" the Sun's gravitational deflection in every apparent place,")
                .append(" the oblate IAU 2015 figure for the reader's disc test and")
                .append(" Horizons' equatorial sphere for the comparison's. The moons")
                .append(" answer from ").append(service.pack().moonsFirstDay())
                .append("; Jupiter from ").append(service.pack().jupiterFirstDay())
                .append("; the exact-time interval ends ")
                .append(service.timeScales().exactUntil()).append(".\n\n")
                .append(JovianComparison.report(result));
        System.out.print(out);
    }
}
