package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.prefs.Preferences;

import javax.imageio.ImageIO;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;

import juranometria.app.AppMenuBar;
import juranometria.app.Atlas;
import juranometria.app.AtlasChrome;
import juranometria.chart.SelectionMode;
import juranometria.chart.SkyPosition;
import juranometria.ui.ChartViewController;
import juranometria.ui.InspectorToggle;
import juranometria.ui.Shortcuts;
import juranometria.ui.language.SkyLanguageSession;
import juranometria.ui.language.SkyLanguageStore;

/**
 * The menu bar in both languages, composed the way the application
 * composes it (Sprint 33, issue #350).
 *
 * <p>Through {@link AtlasChrome}, from a language written to a
 * preference node and read once - not by asking {@code AppMenuBar}
 * for a language directly. A sheet that asked would have photographed
 * a correct menu during the whole period the application was handing
 * it English, which is the defect this sprint keeps finding.
 *
 * <p>It installs its own look and feel before any component exists
 * (#362), and it draws each menu's popup, because a menu keeps its
 * items in a popup rather than as children: a bar painted alone is a
 * picture of three words.
 *
 * <p>The companion reports <strong>mnemonics as their own
 * channel</strong>. They are language data - a mnemonic marks a letter
 * in the item's own translated word - and an inventory that listed
 * only labels, hovers and spoken text missed all five.
 */
public final class MenuSheetMain {

    private MenuSheetMain() {
    }

    private static final Path OUT =
            Path.of("docs/studies/interface-language");

    /** One arrangement of the bar, and what to call it. */
    private record State(String name, String title, double field,
                         boolean checked) {
    }

    private static final List<State> STATES = List.of(
            new State("menus", "All three menus, nothing checked", 42.0, false),
            new State("checked", "View with Inspector and Ecliptic on",
                    42.0, true),
            new State("widest", "View at the widest field", 180.0, false),
            new State("narrowest", "View at the narrowest field", 1.0, false));

    public static void main(String[] args) throws Exception {
        Files.createDirectories(OUT);
        StringBuilder said = new StringBuilder();
        said.append("""
                # Every word the menu bar says

                Issue #350. Generated by
                `juranometria.tool.MenuSheetMain` from compiled
                application classes and their classpath resources,
                composed through `AtlasChrome` from a stored language
                choice. Packaged acceptance separately verifies that
                the interface language resources ship in the
                application image.

                Norwegian is **draft**.

                ## Four channels, not three

                Labels, accessible names and accessible descriptions
                are interface language. **Accelerators** are platform
                notation, spelled by the desktop, and appear in no
                translated value. **Mnemonics** are language data: a
                mnemonic marks a letter inside the item's own
                displayed word, so `C` belongs to *Chart Options* and
                `K` to *Kartvalg*. They are listed separately below
                because an inventory that read only the first three
                missed all five of them.

                The access letters below are read from each live
                menu item and validated against the label it actually
                displays. They are **listed rather than underlined**
                in these macOS captures, because this look and feel
                does not paint mnemonic underlines: the live component
                value is the evidence, and an underline drawn into the
                image would be a marking the platform never shows.

                There are **no tooltips** anywhere on this surface, in
                either language. That is deliberate: a tooltip over an
                open menu would cover the thing it explains.

                """);

        int sheet = 1;
        for (String language : List.of("en", "nb-NO")) {
            said.append("## ").append(language.equals("en") ? "English"
                    : "Norsk bokmål").append(" (`").append(language)
                    .append("`)\n\n");
            for (State state : STATES) {
                said.append("### ").append(state.title()).append("\n\n")
                        .append(draw(language, state,
                                OUT.resolve("menu-" + language + "-"
                                        + (sheet++) + "-" + state.name()
                                        + ".png")))
                        .append('\n');
            }
        }
        Files.writeString(OUT.resolve("menu-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("menu sheets: 8 images and "
                + OUT.resolve("menu-strings.md"));
    }

    private static String draw(String language, State state, Path to)
            throws Exception {
        Preferences node = Preferences.userRoot()
                .node("juranometria-study-menu-" + System.nanoTime());
        JFrame[] owner = new JFrame[1];
        JMenuBar[] bar = new JMenuBar[1];
        try {
            SwingUtilities.invokeAndWait(() -> {
                juranometria.app.UiTheme.apply(false);
                SkyLanguageStore store = SkyLanguageStore.forNode(node);
                store.save(store.choice(Atlas.languages())
                        .withInterface(language));
                SkyLanguageSession session = SkyLanguageSession.begin(
                        store, Atlas.languages());

                ChartViewController navigation = new ChartViewController(
                        Atlas.assembler()::fits);
                navigation.recenter(new SkyPosition(83.8, 0.0),
                        state.field());
                InspectorToggle toggle = new InspectorToggle();
                toggle.bind(() -> { }, () -> true);

                AtlasChrome chrome = AtlasChrome.of(session, navigation,
                        Atlas.search(), Atlas.assembler(), toggle, "2.0.0",
                        () -> { }, new SelectionMode());
                bar[0] = chrome.menuBar(navigation, () -> { }, () -> { },
                        () -> { }, () -> { }, () -> { }, () -> { },
                        () -> { });

                JCheckBoxMenuItem inspector = AppMenuBar.inspectorItem(bar[0]);
                if (inspector != null) {
                    inspector.setSelected(state.checked());
                }
                JCheckBoxMenuItem ecliptic = AppMenuBar.eclipticItem(bar[0]);
                if (ecliptic != null) {
                    ecliptic.setSelected(state.checked());
                }
                owner[0] = new JFrame("study");
                owner[0].setJMenuBar(bar[0]);
                owner[0].pack();
            });
            SwingUtilities.invokeAndWait(() -> { });
            return capture(bar[0], to);
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (owner[0] != null) {
                    owner[0].dispose();
                }
            });
            node.removeNode();
        }
    }

    /**
     * The bar with every menu's items drawn beneath it.
     *
     * <p>A menu keeps its items in a popup, so each popup is laid out
     * and painted under its own menu rather than shown - a shown
     * popup is a window the capture cannot reach, and only one can be
     * open at a time anyway.
     */
    private static String capture(JMenuBar bar, Path to) throws Exception {
        Set<String> said = new LinkedHashSet<>();
        BufferedImage[] image = new BufferedImage[1];
        int[] widest = {0};
        SwingUtilities.invokeAndWait(() -> {
            // Each popup gets its own column. Drawn at its menu's x
            // they overlapped, because a popup is wider than the
            // word that opens it - the first picture showed three
            // menus on top of each other.
            int height = bar.getHeight() + 8;
            int width = bar.getWidth();
            int at = 0;
            for (int m = 0; m < bar.getMenuCount(); m++) {
                JMenu menu = bar.getMenu(m);
                if (menu == null) {
                    continue;
                }
                Component popup = menu.getPopupMenu();
                popup.setSize(popup.getPreferredSize());
                popup.doLayout();
                height = Math.max(height,
                        bar.getHeight() + 8 + popup.getHeight());
                at += popup.getWidth() + 12;
                width = Math.max(width, at);
                widest[0] = Math.max(widest[0], popup.getWidth());
            }
            BufferedImage drawn = new BufferedImage(Math.max(1, width + 8),
                    Math.max(1, height + 8), BufferedImage.TYPE_INT_RGB);
            Graphics2D g = drawn.createGraphics();
            try {
                g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                        RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, drawn.getWidth(), drawn.getHeight());
                bar.paint(g);
                int column = 0;
                for (int m = 0; m < bar.getMenuCount(); m++) {
                    JMenu menu = bar.getMenu(m);
                    if (menu == null) {
                        continue;
                    }
                    Graphics2D popupInk = (Graphics2D) g.create(
                            column, bar.getHeight() + 8,
                            menu.getPopupMenu().getWidth(),
                            menu.getPopupMenu().getHeight());
                    menu.getPopupMenu().paint(popupInk);
                    popupInk.dispose();
                    column += menu.getPopupMenu().getWidth() + 12;
                }
            } finally {
                g.dispose();
            }
            image[0] = drawn;
            collect(bar, said);
        });
        ImageIO.write(image[0], "png", to.toFile());

        StringBuilder out = new StringBuilder();
        out.append("![](").append(to.getFileName()).append(")\n\n")
                .append("Bar packed ").append(image[0].getWidth())
                .append(" × ").append(image[0].getHeight())
                .append(" px; widest popup ").append(widest[0])
                .append(" px.\n\n")
                .append("| channel | words |\n|---|---|\n");
        for (String one : said) {
            out.append("| ").append(one.replace("|", "\\|")).append(" |\n");
        }
        return out.toString();
    }

    private static void collect(JMenuBar bar, Set<String> said) {
        for (int m = 0; m < bar.getMenuCount(); m++) {
            JMenu menu = bar.getMenu(m);
            if (menu == null) {
                continue;
            }
            record(menu, said, "menu");
            for (int i = 0; i < menu.getItemCount(); i++) {
                JMenuItem item = menu.getItem(i);
                if (item != null) {
                    record(item, said, "item");
                }
            }
        }
    }

    private static void record(JMenuItem item, Set<String> said, String what) {
        String off = item.isEnabled() ? "" : " [unavailable]";
        String on = item instanceof JCheckBoxMenuItem box && box.isSelected()
                ? " [checked]" : "";
        add(said, what + " label" + off + on, item.getText());
        add(said, what + " hover" + off, item.getToolTipText());
        if (item.getAccessibleContext() != null) {
            add(said, what + " spoken name" + off,
                    item.getAccessibleContext().getAccessibleName());
            add(said, what + " spoken description" + off,
                    item.getAccessibleContext().getAccessibleDescription());
        }
        KeyStroke stroke = item.getAccelerator();
        if (stroke != null) {
            add(said, what + " accelerator (platform notation)",
                    Shortcuts.text(stroke));
        }
        if (item.getMnemonic() != 0) {
            add(said, what + " access letter (language)",
                    String.valueOf((char) item.getMnemonic()));
        }
    }

    private static void add(Set<String> said, String kind, String text) {
        if (text == null || text.isBlank()) {
            return;
        }
        said.add(kind + " | " + text.replaceAll("<[^>]*>", " ")
                .replaceAll("\\s+", " ").trim());
    }
}
