package juranometria.tool;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Locale;

import javax.imageio.ImageIO;

import juranometria.app.Atlas;
import juranometria.chart.ChartScene;
import juranometria.chart.ChartViewState;
import juranometria.chart.StarSizePolicy;
import juranometria.render.ChartOptions;
import juranometria.render.ChartRenderer;

/**
 * The Milky Way gate's evidence (Sprint 22, issue #189): what the
 * candidate source contains, how its topology behaves, and what the
 * layer would cost the page.
 *
 * <p>Study code only. Production packs, options, scenes and rendering
 * are untouched by this issue; the geometry is read from a gitignored
 * import and projected through the production seams so that what is
 * measured is what the atlas would draw.
 */
public final class MilkyWayStudyMain {

    private MilkyWayStudyMain() {
    }

    public static void main(String[] args) throws IOException {
        System.out.println("# Milky Way study (issue #189)");
        System.out.println();
        System.out.println("Generated by `make milky-way-study` from the"
                + " pinned candidate, whose bytes are verified before"
                + " anything is read.");
        System.out.println();
        List<MilkyWayGeometry.Level> levels = MilkyWayGeometry.load();
        source(levels);
        topology(levels);
        palette();
        onThePage(levels);
    }

    /**
     * The palette, chosen by measurement rather than by taste, in
     * lightness (CIE L*) because these are near-white washes: a
     * contrast ratio compares badly at this end of the scale, where
     * every pair sits near 1:1 and says nothing useful.
     *
     * <p>Three questions, and the third is the one that constrains
     * everything: can the chart's own marks still be read over the
     * darkest wash?
     */
    private static void palette() {
        System.out.println("## The palette");
        System.out.println();
        System.out.println("Near-white washes are compared by lightness"
                + " (CIE L*), not by contrast ratio: at this end of"
                + " the scale every ratio sits near 1:1 and separates"
                + " nothing. A difference of about 1 L* is the least"
                + " the eye finds in two large flat areas; below that"
                + " a level is decorative.");
        System.out.println();
        System.out.println("### What the chart already draws");
        System.out.println();
        System.out.println("| chart ink | grey | L* | below paper |");
        System.out.println("|---|---:|---:|---:|");
        int[] inks = {232, 216, 190, 150, 132, 120, 102, 34, 0};
        String[] names = {"galaxy fill", "grid lines", "boundaries",
                "grid labels", "nebula outline", "figures",
                "galaxy outline", "text", "stars"};
        for (int i = 0; i < inks.length; i++) {
            System.out.printf(Locale.ROOT, "| %s | %d | %.2f | %.2f |%n",
                    names[i], inks[i], lightness(inks[i]),
                    lightness(255) - lightness(inks[i]));
        }
        System.out.println();
        System.out.printf(Locale.ROOT,
                "**The whole budget is %.2f L***: paper down to the"
                        + " galaxy fill, the palest mark the chart"
                        + " draws. A wash darker than that would sink"
                        + " a galaxy into its own background.%n%n",
                lightness(255) - lightness(232));

        System.out.println("### The ladders measured");
        System.out.println();
        System.out.println("| ladder | first step from paper |"
                + " step to step | clear of the galaxy fill |");
        System.out.println("|---|---:|---:|---:|");
        int[][] ladders = {
                {250, 245, 240, 235, 230},
                {248, 245, 242, 239, 236},
                {251, 248, 245, 242, 239},
                {249, 244, 239}};
        String[] ladderNames = {
                "five levels, visibly spaced (the first attempt)",
                "five levels, squeezed above the galaxy fill",
                "five levels, quietest possible",
                "**three washes (chosen)**"};
        for (int i = 0; i < ladders.length; i++) {
            int[] ladder = ladders[i];
            double first = lightness(255) - lightness(ladder[0]);
            double step = lightness(ladder[0])
                    - lightness(ladder[ladder.length - 1]);
            step /= (ladder.length - 1);
            double clear = lightness(ladder[ladder.length - 1])
                    - lightness(232);
            System.out.printf(Locale.ROOT,
                    "| %s | %.2f | %.2f | %+.2f |%n", ladderNames[i],
                    first, step, clear);
        }
        System.out.println();
        System.out.println("The first attempt ends **darker than a"
                + " galaxy**. Squeezing five levels above the galaxy"
                + " fill steps by about 1 L*, which is where two"
                + " washes stop being two. Three washes clear every"
                + " test with room left.");
        System.out.println();

        System.out.println("### Colour separation between the marks and"
                + " the darkest wash");
        System.out.println();
        System.out.println("**A calculation on the palette, not a"
                + " measurement of rendered pages.** These are the"
                + " lightness distances between each ink's own colour"
                + " and the darkest wash, which is what a wash costs a"
                + " mark at its solid core. It is not a legibility"
                + " verdict: a mark meets its background through"
                + " antialiased edge pixels, and this study cannot"
                + " render those over a wash without changing"
                + " production. **Whether the marks stay legible over"
                + " the layer is settled in #191**, on composited"
                + " pixels.");
        System.out.println();
        System.out.println("| chart ink | over paper | over the darkest"
                + " wash |");
        System.out.println("|---|---:|---:|");
        for (int i = 0; i < inks.length; i++) {
            System.out.printf(Locale.ROOT, "| %s | %.2f | %.2f |%n",
                    names[i], lightness(255) - lightness(inks[i]),
                    lightness(239) - lightness(inks[i]));
        }
        System.out.println();
        System.out.println("The thinnest is the **galaxy fill at 2.45"
                + " L***, whose grey-132 outline carries the symbol"
                + " regardless - the named regression case #191"
                + " inherits. What this table establishes is that the"
                + " palette **leaves each mark a separation to be"
                + " measured**, and none of it collapses to nothing;"
                + " what it does not establish is how each mark then"
                + " reads.");
        System.out.println();
    }

    /** CIE L* for a grey, which is how near-white washes compare. */
    private static double lightness(int grey) {
        double c = grey / 255.0;
        double linear = c <= 0.04045 ? c / 12.92
                : Math.pow((c + 0.055) / 1.055, 2.4);
        return linear > 0.008856
                ? 116.0 * Math.cbrt(linear) - 16.0 : 903.3 * linear;
    }

    private static final File DIR = new File("docs/studies/milky-way");
    private static final ChartRenderer RENDERER =
            new ChartRenderer(StarSizePolicy.DEFAULT);
    private static final int WIDTH = 900;
    private static final int HEIGHT = 700;

    /**
     * The layer on real pages, at the fields the gate names, drawn
     * through the production projection and laid under the chart's
     * own ink.
     */
    private static void onThePage(List<MilkyWayGeometry.Level> levels)
            throws IOException {
        DIR.mkdirs();
        System.out.println("## On the page");
        System.out.println();
        System.out.println("Every page is the production renderer's own"
                + " output with the candidate layer beneath it. The"
                + " coverage figures are exact - they are measured on"
                + " the layer itself, before any page is laid over"
                + " it.");
        System.out.println();
        System.out.println("**The images are a preview, not the"
                + " production drawing order.** The renderer fills its"
                + " paper before drawing, so a study cannot paint"
                + " underneath it without changing production, which"
                + " this issue forbids. The page is therefore laid"
                + " over the wash and the wash shows through wherever"
                + " the page left pure paper - which leaves the"
                + " antialiased edge of every mark white, where"
                + " production would tint it. That is a faint halo"
                + " around chart ink, and it is why **how a mark reads"
                + " over a wash is not settled here** but in #191,"
                + " through the real background seam.");
        System.out.println();
        System.out.println("| page | field | washes seen | layer covers"
                + " | brightest wash | chart ink over layer |");
        System.out.println("|---|---:|---:|---:|---:|---:|");
        MilkyWaySky sky = new MilkyWaySky(levels);
        long slowest = 0;
        long quickest = Long.MAX_VALUE;
        double halo = 0.0;
        java.util.Set<Integer> layerColours = new java.util.TreeSet<>();
        for (MilkyWayPages.Page page : MilkyWayPages.pages()) {
            for (double field : new double[] {8.0, 18.0, 36.0}) {
                ChartScene scene = Atlas.assembler().assemble(
                        new ChartViewState(page.centre(), field, 8.0,
                                null, null), WIDTH, HEIGHT);
                BufferedImage layer = new BufferedImage(WIDTH, HEIGHT,
                        BufferedImage.TYPE_INT_RGB);
                MilkyWayPages.Measured measured =
                        MilkyWayPages.paint(layer, scene, sky);
                BufferedImage chart = RENDERER.renderToImage(scene,
                        ChartOptions.DEFAULTS);
                double inkOver =
                        MilkyWayPages.inkOverLayer(layer, chart);
                halo = Math.max(halo, MilkyWayPages.haloPercent(chart));
                MilkyWayPages.collectColours(layer, layerColours);
                ImageIO.write(MilkyWayPages.previewOver(layer, chart), "png",
                        new File(DIR, String.format(Locale.ROOT,
                                "%s-%02.0f-preview.png", page.name(), field)));
                System.out.printf(Locale.ROOT,
                        "| %s | %.0f° | %d | %.1f%% | %.1f%% | %.1f%% |%n",
                        page.name(), field, measured.levelsSeen(),
                        measured.coveragePercent(),
                        measured.brightestPercent(), inkOver);
                slowest = Math.max(slowest, measured.buildMillis());
                quickest = Math.min(quickest, measured.buildMillis());
            }
        }
        StringBuilder colours = new StringBuilder();
        for (int rgb : layerColours) {
            colours.append(colours.isEmpty() ? "" : ", ")
                    .append(String.format(Locale.ROOT, "`#%06x`", rgb));
        }
        System.out.printf(Locale.ROOT,
                "Across every page above, the layer canvases contain"
                        + " **%d colours in total**: %s. Paper and the"
                        + " three washes, and nothing between them -"
                        + " no translucency, no cumulative alpha, no"
                        + " intermediate greys. The lightness figures"
                        + " in the palette section therefore describe"
                        + " colours the layer really has.%n%n",
                layerColours.size(), colours);
        System.out.printf(Locale.ROOT,
                "At most **%.1f%% of a page's inked pixels** are the"
                        + " antialiased edges the preview leaves white."
                        + " In production they would carry the wash;"
                        + " here they do not, and no claim in this"
                        + " report rests on them.%n%n", halo);
        System.out.println("The oracle's cost is **not in this report**."
                + " Wall-clock timing is not reproducible evidence: it"
                + " differs between machines and between two runs on"
                + " one machine, and a study whose output moves cannot"
                + " be reproduced. What this run observed is written"
                + " to standard error instead, with the machine that"
                + " produced it named, and"
                + " [the decision](../../decisions/milky-way-layer.md)"
                + " records an observation rather than a bound.");
        System.out.println();
        System.out.println("Pages written to `" + DIR.getPath() + "`.");
        System.out.println();
        // Observed, named, and kept out of the reproducible report.
        // No threshold is enforced here: a faster machine must never
        // fail a study, and a slower one is not a defect in the data.
        // #191 is where an interaction budget is enforced, on the
        // supported CI path.
        System.err.printf(Locale.ROOT,
                "performance note (observed, NOT reproducible"
                        + " evidence): %d pages sampled in %d-%d ms"
                        + " each on %s %s, %s %s%n",
                MilkyWayPages.pages().size() * 3, quickest, slowest,
                System.getProperty("os.name"),
                System.getProperty("os.arch"),
                System.getProperty("java.vm.name"),
                System.getProperty("java.version"));
    }

    /** What the file is, before any opinion about it. */
    private static void source(List<MilkyWayGeometry.Level> levels) {
        System.out.println("## What the candidate contains");
        System.out.println();
        System.out.println("`" + MilkyWayGeometry.SOURCE + "`, SHA-256 `"
                + MilkyWayGeometry.SHA256 + "`.");
        System.out.println();
        System.out.println("| level | rings | filled | holes | points |");
        System.out.println("|---|---:|---:|---:|---:|");
        int rings = 0;
        int points = 0;
        for (MilkyWayGeometry.Level level : levels) {
            System.out.printf(Locale.ROOT, "| `%s` | %d | %d | %d | %,d |%n",
                    level.id(), level.rings().size(), level.filled(),
                    level.holes(), level.points());
            rings += level.rings().size();
            points += level.points();
        }
        System.out.printf(Locale.ROOT,
                "| **all five** | **%d** | | | **%,d** |%n", rings, points);
        System.out.println();
    }

    /** The topology questions the gate asks, answered from the data. */
    private static void topology(List<MilkyWayGeometry.Level> levels) {
        System.out.println("## Topology");
        System.out.println();
        System.out.println("Filling is decided by **containment depth**,"
                + " not by winding: a ring at even depth encloses ink,"
                + " a ring at odd depth cuts a hole in it. The source"
                + " mixes winding directions, so the GeoJSON"
                + " convention cannot be relied on here.");
        System.out.println();
        System.out.println("| level | max depth | rings at depth 1+ |"
                + " rings crossing RA 0 | widest ring | dec range |");
        System.out.println("|---|---:|---:|---:|---:|---|");
        for (MilkyWayGeometry.Level level : levels) {
            int maxDepth = 0;
            int nested = 0;
            int seam = 0;
            double widest = 0.0;
            double minDec = 90.0;
            double maxDec = -90.0;
            for (MilkyWayGeometry.Ring ring : level.rings()) {
                maxDepth = Math.max(maxDepth, ring.depth());
                if (ring.depth() > 0) {
                    nested++;
                }
                if (ring.seam()) {
                    seam++;
                } else {
                    widest = Math.max(widest, ring.spanRaDegrees());
                }
                minDec = Math.min(minDec, ring.minDec());
                maxDec = Math.max(maxDec, ring.maxDec());
            }
            System.out.printf(Locale.ROOT,
                    "| `%s` | %d | %d | %d | %.1f° | %+.1f° to %+.1f° |%n",
                    level.id(), maxDepth, nested, seam, widest,
                    minDec, maxDec);
        }
        System.out.println();
        seams(levels);
    }

    /**
     * Where the outlines wrap, and the proof that unwrapping heals
     * them.
     *
     * <p>Whichever frame a reader of this file chooses, some rings
     * wrap: four cross the source's own +/-180 meridian, and three
     * cross RA 0 once the coordinates are in the atlas's frame. An
     * importer cannot pick a frame in which nothing wraps - it can
     * only unwrap deliberately, which is what the study does before
     * anything is projected.
     */
    private static void seams(List<MilkyWayGeometry.Level> levels) {
        System.out.println("### The seam");
        System.out.println();
        int wrapping = 0;
        int healed = 0;
        int worstAfter = 0;
        for (MilkyWayGeometry.Level level : levels) {
            for (MilkyWayGeometry.Ring ring : level.rings()) {
                double[] xs = MilkyWayGeometry.unwrapped(ring.points());
                boolean wraps = false;
                for (int i = 1; i < xs.length; i++) {
                    double raw = ring.points().get(i).raDegrees()
                            - ring.points().get(i - 1).raDegrees();
                    if (Math.abs(raw) > 180.0) {
                        wraps = true;
                    }
                }
                if (wraps) {
                    wrapping++;
                }
                double worst = 0.0;
                for (int i = 1; i < xs.length; i++) {
                    worst = Math.max(worst, Math.abs(xs[i] - xs[i - 1]));
                }
                if (worst <= 180.0) {
                    healed++;
                } else {
                    worstAfter++;
                }
            }
        }
        int rings = levels.stream()
                .mapToInt(level -> level.rings().size()).sum();
        System.out.printf(Locale.ROOT,
                "- **%d of %d rings wrap** in the atlas's frame (a step"
                        + " of more than 180 degrees between"
                        + " neighbouring points).%n", wrapping, rings);
        System.out.printf(Locale.ROOT,
                "- After unwrapping, **%d of %d rings are continuous**"
                        + " and %d are not.%n", healed, rings, worstAfter);
        System.out.println("- The source's own frame is no safer: four"
                + " rings cross its ±180 meridian, with eight steps"
                + " between them. There is no frame in which nothing"
                + " wraps, so the importer must unwrap rather than"
                + " choose.");
        System.out.println();
    }
}
