package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

import juranometria.app.Atlas;
import juranometria.chart.ChartViewState;
import juranometria.chart.SelectionModel;
import juranometria.page.PageVisibility;
import juranometria.ui.ChartComponent;
import juranometria.ui.ChartModuleHost;
import juranometria.ui.language.InterfaceText;
import juranometria.ui.language.PageVisibilityText;
import juranometria.ui.onthispage.OnThisPageModule;
import juranometria.ui.onthispage.OnThisPageTable;

/**
 * On This Page, drawn in each interface language for a person to
 * judge the translation by (Sprint 33, issue #350).
 *
 * <p>The same instrument the Inspector had, and for the same reason:
 * a translation is judged by reading it in place, at the width it
 * actually gets, not by reading a properties file. It draws in a real
 * window because this surface measures its own columns against font
 * metrics - the Chart column from its five words and its header, the
 * Mag column from its silence - and a detached panel would report
 * widths nothing honours.
 *
 * <p>It also records the widths themselves. Norwegian's words are
 * longer than English's in the Chart column and shorter in the Mag
 * column, and the question a reviewer needs answered is not which is
 * longer but whether the whole table still fits.
 */
public final class OnThisPageSheetMain {

    /**
     * What this photographer holds still: production only packs this window, so its size is its
     * layout’s preference.
     *
     * <p>Read by the display evidence gate, which refuses a
     * generator that declares one kind and asks the capture
     * coordinator for another.
     */
    public static final SheetCapture.Kind CAPTURE_KIND =
            SheetCapture.Kind.PACKED;

    /** English, stated: a study says which language it renders (#350). */
    private static final juranometria.project.PageWords ENGLISH =
            juranometria.ui.language.PageText.in(juranometria.ui.language.InterfaceText.forLanguage("en"));

    private OnThisPageSheetMain() {
    }

    /**
     * Where the sheets go: the committed directory by default, or a
     * directory a caller names as {@code args[0]}.
     *
     * <p>`InterfaceEvidenceGateTest` runs every one of these into a
     * scratch directory and compares the result with what is
     * committed. It can only do that if a generator can be told
     * where to write; one that always writes over the evidence
     * cannot be used to check it.
     */
    private static Path out =
            Path.of("docs/studies/interface-language");

    public static void main(String[] args) throws Exception {
        if (args.length > 0 && !args[0].isBlank()) {
            out = Path.of(args[0]);
        }
        Files.createDirectories(out);
        StringBuilder said = new StringBuilder();
        said.append("""
                # Every word On This Page says

                Issue #350. Generated by
                `juranometria.tool.OnThisPageSheetMain`, in a real
                window, because this surface measures its own columns.

                %s

                ## What is translated here, and what is not

                Object designations, star proper names, magnitudes,
                photometric bands and separations are catalogue data
                and are untouched. `SkyNames` holds constellation
                names only; a star's proper name comes from
                `StarIdentity` and is canonical identity. A culturally
                localised star-name system would need its own data and
                its own provenance contract, and is not this issue.

                `not recorded` **is** translated. It sits among
                numbers and reads like data, which is how it stayed
                English through two earlier passes.

                ## The Chart column's five answers

                Each has two keys, written independently rather than
                one derived from the other: a compact word a reader
                scans down a column, and the whole answer on hover and
                in the spoken channel.

                """.formatted(juranometria.tool.InterfaceLanguageStatus
                        .statement("nb-NO")));

        appendWords(said);
        appendWidths(said);

        int sheet = 1;
        for (String language : List.of("en", "nb-NO")) {
            said.append("## ").append(language.equals("en") ? "English"
                    : "Norsk bokmål").append(" (`").append(language)
                    .append("`)\n\n");
            for (String state : List.of("populated", "empty")) {
                said.append("### ").append(title(state)).append("\n\n")
                        .append(draw(language, state,
                                out.resolve("onthispage-" + language + "-"
                                        + (sheet++) + "-" + state + ".png")))
                        .append('\n');
            }
        }
        Files.writeString(out.resolve("onthispage-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("on this page sheets: 4 images and "
                + out.resolve("onthispage-strings.md"));
    }

    /** The five answers side by side, both registers, both languages. */
    private static void appendWords(StringBuilder said) {
        said.append("| state | English word | English answer |")
                .append(" Norsk ord | Norsk svar |\n")
                .append("|---|---|---|---|---|\n");
        PageVisibilityText en = PageVisibilityText.in(
                InterfaceText.forLanguage("en"));
        PageVisibilityText nb = PageVisibilityText.in(
                InterfaceText.forLanguage("nb-NO"));
        for (PageVisibility state : PageVisibility.values()) {
            said.append("| `").append(state.name()).append("` | ")
                    .append(en.label(state)).append(" | ")
                    .append(en.explanation(state)).append(" | ")
                    .append(nb.label(state)).append(" | ")
                    .append(nb.explanation(state)).append(" |\n");
        }
        said.append("\nThe rows are sorted by this identity, not by"
                + " translated spelling: the order runs from drawn to"
                + " least drawn, and it would differ in every language"
                + " if the words decided it.\n\n");
    }

    /** What the translation costs the layout, measured. */
    private static void appendWidths(StringBuilder said) {
        said.append("## What it costs the layout\n\n")
                .append("| language | Object | Mag | From | Chart |")
                .append(" total | 320 px | 240 px |\n")
                .append("|---|---|---|---|---|---|---|---|\n");
        java.util.Map<String, Integer> totals =
                new java.util.LinkedHashMap<>();
        JTable probe = new JTable();
        java.awt.FontMetrics cells = probe.getFontMetrics(probe.getFont());
        java.awt.FontMetrics header = probe.getFontMetrics(
                probe.getFont().deriveFont(java.awt.Font.BOLD));
        for (String language : List.of("en", "nb-NO")) {
            InterfaceText text = InterfaceText.forLanguage(language);
            int object = cells.stringWidth("● NGC 317A") + 12;
            int magnitude = cells.stringWidth(
                    text.say("onthispage.magnitude.none")) + 12;
            int from = cells.stringWidth("00.00°") + 12;
            int chart = OnThisPageTable.stateColumnWidth(cells, header, text);
            int total = object + magnitude + from + chart;
            totals.put(language, total);
            said.append("| `").append(language).append("` | ")
                    .append(object).append(" | ").append(magnitude)
                    .append(" | ").append(from).append(" | ")
                    .append(chart).append(" | **").append(total)
                    .append("** | ").append(total <= 320 ? "fits" : "scrolls")
                    .append(" | ").append(total <= 240 ? "fits" : "scrolls")
                    .append(" |\n");
        }
        // Stated from the measurement, not written down beside it.
        // A revision to the Norwegian words moved these numbers
        // while the sentence went on claiming the old ones (#350).
        int english = totals.get("en");
        int norsk = totals.get("nb-NO");
        said.append("\nNorwegian's Chart column is wider and its Mag"
                + " column narrower, so the table costs ")
                .append(Math.abs(norsk - english))
                .append(" px in all (")
                .append(english).append(" px against ").append(norsk)
                .append("). Both languages scroll in a 240 px sidebar,"
                + " as English already did before any translation: the"
                + " pane scrolls rather than squeezing four columns"
                + " into ellipses (#217).\n\n");
    }

    private static String title(String state) {
        return switch (state) {
            case "populated" -> "A page with objects on it";
            case "empty" -> "A page with nothing catalogued on it";
            default -> state;
        };
    }

    /** Draws one state in one language and returns its strings. */
    private static String draw(String language, String state, Path to)
            throws Exception {
        JFrame[] owner = new JFrame[1];
        OnThisPageTable[] panel = new OnThisPageTable[1];
        try {
            SwingUtilities.invokeAndWait(() -> {
                juranometria.app.UiTheme.apply(false);
                ChartComponent chart = new ChartComponent(Atlas.assembler(), ENGLISH);
                chart.setSize(900, 700);
                // An empty page is reached by pointing the chart at
                // sky the catalogue is silent about, not by handing
                // the panel a fabricated emptiness.
                // Found by sweeping the catalogue for a field it is
                // silent about, not guessed: the first choice here
                // still held 23 objects, and a sheet captioned "a
                // page with nothing on it" showed a full table.
                chart.setViewState(state.equals("empty")
                        ? new ChartViewState(
                                new juranometria.chart.SkyPosition(
                                        0.0, -54.0), 1.0, 4.0)
                        : ChartViewState.DEFAULT);
                ChartModuleHost host = new ChartModuleHost(chart,
                        new SelectionModel(), request -> { });
                panel[0] = host.attach(new OnThisPageModule(
                        InterfaceText.forLanguage(language))).panel();
                owner[0] = new JFrame("study");
                owner[0].setContentPane(panel[0]);
                panel[0].setPreferredSize(new java.awt.Dimension(320, 420));
                owner[0].pack();
            });
            SwingUtilities.invokeAndWait(() -> { });
                JComponent content = panel[0];
            // The shared rule: nothing is photographed until the
            // queue is empty, the window has packed to a fixed
            // point, the layout has stopped moving and focus is
            // owned by nobody.
            SheetCapture.settle(content, SheetCapture.packed());
            BufferedImage image = new BufferedImage(
                    Math.max(1, content.getWidth()),
                    Math.max(1, content.getHeight()),
                    BufferedImage.TYPE_INT_RGB);
            Graphics2D g = image.createGraphics();
            try {
                g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                        RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, image.getWidth(), image.getHeight());
                content.paint(g);
            } finally {
                g.dispose();
            }
            ImageIO.write(image, "png", to.toFile());
            return describe(content, to);
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (owner[0] != null) {
                    owner[0].dispose();
                }
            });
        }
    }

    /** The chrome the sheet shows, without the catalogue data. */
    private static String describe(Container content, Path image) {
        Set<String> chrome = new LinkedHashSet<>();
        collect(content, chrome);
        StringBuilder said = new StringBuilder();
        said.append("![](").append(image.getFileName()).append(")\n\n")
                .append("| shown or spoken |\n|---|\n");
        for (String one : chrome) {
            said.append("| ").append(one.replace("|", "\\|")).append(" |\n");
        }
        return said.toString();
    }

    private static void collect(Container from, Set<String> said) {
        if (from instanceof JComponent self) {
            record(self, said);
        }
        for (Component child : from.getComponents()) {
            if (child instanceof JComponent widget) {
                record(widget, said);
            }
            if (child instanceof Container nested) {
                collect(nested, said);
            }
        }
    }

    private static void record(JComponent widget, Set<String> said) {
        if (widget instanceof AbstractButton button) {
            add(said, button.getText());
        }
        if (widget instanceof JLabel label) {
            add(said, label.getText());
        }
        if (widget instanceof JTable table) {
            for (int column = 0; column < table.getColumnCount(); column++) {
                add(said, table.getColumnName(column));
            }
        }
        add(said, widget.getToolTipText());
        if (widget.getAccessibleContext() != null) {
            add(said, widget.getAccessibleContext().getAccessibleName());
            add(said, widget.getAccessibleContext()
                    .getAccessibleDescription());
        }
    }

    private static void add(Set<String> said, String text) {
        if (text == null || text.isBlank()) {
            return;
        }
        // A wrap is replaced by a space, never deleted: Chart Options
        // published "angitt ikatalogen" by deleting one.
        said.add(text.replaceAll("<[^>]*>", " ")
                .replaceAll("\\s+", " ").trim());
    }
}
