package juranometria.tool;

import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import javax.imageio.ImageIO;

import juranometria.app.AppInfo;
import juranometria.app.Atlas;
import juranometria.chart.ChartScene;
import juranometria.chart.ChartViewState;
import juranometria.chart.SkyPosition;
import juranometria.chart.StarSizePolicy;
import juranometria.project.DrawnPage;
import juranometria.project.PageWords;
import juranometria.render.ChartOptions;
import juranometria.render.ChartRenderer;
import juranometria.sheet.ChartSheet;
import juranometria.sheet.PaperSize;
import juranometria.ui.SceneAssembler;
import juranometria.ui.language.InterfaceText;
import juranometria.ui.language.PageText;

/**
 * One page, four ways: interface language against chart language
 * (Sprint 33, issue #350).
 *
 * <p>The two choices are not the same choice, and this is the picture
 * that shows it. Along one axis the <strong>chart</strong> language
 * renames the constellations; along the other the
 * <strong>interface</strong> language rewrites everything the atlas
 * says <em>about</em> the page - the title block, the magnitude key,
 * the spoken description, and the metadata written inside every
 * exported file. Neither axis moves the other's words, and neither
 * moves a single number.
 *
 * <p>A sixty-degree page, because the reviewed default is eight
 * degrees across and <strong>names no constellations at all</strong>:
 * a matrix drawn there would have compared two empty skies and
 * proved nothing. The generator asserts that both chart languages
 * actually place names before it writes anything.
 */
public final class PageLanguageSheetMain {

    private PageLanguageSheetMain() {
    }

    /**
     * Where the sheets go: the committed directory by default, or a
     * directory a caller names as {@code args[0]}.
     *
     * <p>`InterfaceEvidenceGateTest` runs every one of these into a
     * scratch directory and compares the result with what is
     * committed. It can only do that if a generator can be told
     * where to write; one that always writes over the evidence
     * cannot be used to check it.
     */
    private static Path out =
            Path.of("docs/studies/interface-language");

    /** Wide enough that the sky has names to rename. */
    private static final ChartViewState PAGE = new ChartViewState(
            new SkyPosition(10.684708, 41.268750), 60.0, 6.0);

    private static final int WIDE = 900;
    private static final int HIGH = 700;

    /** One cell: an interface language and a chart language. */
    private record Cell(String interfaceTag, String chartTag,
                        String name) {
    }

    private static final List<Cell> CELLS = List.of(
            new Cell("en", "latin", "en-latin"),
            new Cell("en", "nb-NO", "en-nbsky"),
            new Cell("nb-NO", "latin", "nb-latin"),
            new Cell("nb-NO", "nb-NO", "nb-nbsky"));

    public static void main(String[] args) throws Exception {
        if (args.length > 0 && !args[0].isBlank()) {
            out = Path.of(args[0]);
        }
        Files.createDirectories(out);

        // The premise, before anything is written: both chart
        // languages must actually place names on this page, or the
        // whole matrix is two empty skies compared with each other.
        for (String chart : List.of("latin", "nb-NO")) {
            int named = names(sceneFor(chart)).size();
            if (named == 0) {
                throw new IllegalStateException("the " + chart
                        + " sky places no names on this page, so a"
                        + " matrix drawn here would prove nothing");
            }
            System.out.println("premise: the " + chart + " sky names "
                    + named + " constellations on this page");
        }

        StringBuilder said = new StringBuilder();
        said.append("""
                # One page, four ways: interface language × chart language

                Issue #350. Generated by
                `juranometria.tool.PageLanguageSheetMain` from compiled
                application classes and their classpath resources.

                %s

                A sixty-degree page, because the reviewed default is
                eight degrees across and names no constellations at
                all - a matrix drawn there would compare two empty
                skies. The generator refuses to write anything unless
                both chart languages place names here.

                ## The two axes

                | | chart: Latin/IAU | chart: `nb-NO` |
                |---|---|---|
                | **interface `en`** | baseline | sky renamed, chrome identical |
                | **interface `nb-NO`** | chrome rewritten, sky identical | both |

                Every image is drawn by the real `ChartRenderer` from
                the same view and the same options; only the two
                language choices differ.

                """.formatted(juranometria.tool.InterfaceLanguageStatus
                        .statement("nb-NO")));

        for (Cell cell : CELLS) {
            said.append(draw(cell));
        }
        said.append(comparisons()).append(palettePhrases())
                .append(refusals());

        Files.writeString(out.resolve("page-language-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("page language sheets: " + CELLS.size()
                + " images and "
                + out.resolve("page-language-strings.md"));
    }

    /** One cell drawn, with every channel it produces written down. */
    private static String draw(Cell cell) throws Exception {
        ChartScene scene = sceneFor(cell.chartTag());
        PageWords words = PageText.in(
                InterfaceText.forLanguage(cell.interfaceTag()));
        ChartRenderer renderer =
                new ChartRenderer(StarSizePolicy.DEFAULT, words);

        BufferedImage image = new BufferedImage(WIDE, HIGH,
                BufferedImage.TYPE_INT_RGB);
        Graphics2D g = image.createGraphics();
        try {
            g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                    RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            renderer.render(g, scene, ChartOptions.DEFAULTS);
        } finally {
            g.dispose();
        }
        Path to = out.resolve("page-" + cell.name() + ".png");
        ImageIO.write(image, "png", to.toFile());

        // The exported file's own words, from the same resolved
        // instance the renderer just drew with.
        var sheet = ChartSheet.record(
                assembler(cell.chartTag())::assemble, PAGE,
                ChartOptions.DEFAULTS,
                ChartRenderer.ReferenceLayer.NONE, PaperSize.A4, words);

        StringBuilder out = new StringBuilder();
        out.append("### interface `").append(cell.interfaceTag())
                .append("`, chart ").append(cell.chartTag()
                        .equals("latin") ? "Latin/IAU" : "`nb-NO`")
                .append("\n\n![](").append(to.getFileName())
                .append(")\n\n| channel | words |\n|---|---|\n");

        String[] title = titleLines(renderer, scene);
        row(out, "title line 1 — the page's own title", title[0]);
        row(out, "title line 2 — centre", title[1]);
        row(out, "title line 3 — facts", title[2]);
        row(out, "magnitude-key heading", words.magnitudeKeyHeading());
        row(out, "chart, spoken name", words.chartName());
        row(out, "chart, spoken instructions", words.chartInstructions());
        row(out, "page, spoken in full",
                DrawnPage.of(scene).describe(words));
        row(out, "exported file: title", sheet.metadata().title());
        row(out, "exported file: description",
                sheet.metadata().description());
        row(out, "exported file: producer",
                sheet.metadata().producedBy());
        row(out, "constellations named", String.join(", ",
                names(scene)));
        return out.append('\n').toString();
    }

    /** What must and must not have moved, measured rather than claimed. */
    private static String comparisons() {
        ChartScene latin = sceneFor("latin");
        ChartScene norsk = sceneFor("nb-NO");
        PageWords english = PageText.in(InterfaceText.forLanguage("en"));
        PageWords bokmal = PageText.in(
                InterfaceText.forLanguage("nb-NO"));

        StringBuilder out = new StringBuilder(
                "## What moved, and what did not\n\n"
                        + "| comparison | result |\n|---|---|\n");

        row(out, "interface changed, marks and positions",
                marks(latin, english).equals(marks(latin, bokmal))
                        ? "identical (" + marks(latin, english).size()
                                + " marks)" : "**CHANGED**");
        row(out, "interface changed, non-text ink",
                ink(latin, english) == ink(latin, bokmal)
                        ? "identical (" + ink(latin, english)
                                + " lit pixels)" : "**CHANGED**");
        row(out, "interface changed, constellation names",
                names(latin).equals(names(latin))
                        ? "identical (the chart language did not move)"
                        : "**CHANGED**");
        row(out, "chart language changed, title line 2",
                titleLines(renderer(english), latin)[1].equals(
                        titleLines(renderer(english), norsk)[1])
                        ? "identical" : "**CHANGED**");
        row(out, "chart language changed, title line 3",
                titleLines(renderer(english), latin)[2].equals(
                        titleLines(renderer(english), norsk)[2])
                        ? "identical" : "**CHANGED**");
        row(out, "chart language changed, constellation names",
                names(latin).equals(names(norsk)) ? "**UNCHANGED**"
                        : "renamed: " + names(latin).size() + " names");
        row(out, "chart values under a Norwegian interface",
                titleLines(renderer(bokmal), latin)[2].contains("6.0")
                        && !titleLines(renderer(bokmal), latin)[2]
                                .contains("6,0")
                        ? "dot-decimal, unchanged" : "**COMMA**");
        return out.append('\n').toString();
    }

    /** Both grounds, even though only white paper is photographed. */
    private static String palettePhrases() {
        StringBuilder out = new StringBuilder(
                "## The two grounds\n\nOnly white paper is exported"
                + " above; a reader who chooses a black sky exports"
                + " the other, so both phrases are recorded.\n\n"
                + "| stored token | `en` | `nb-NO` |\n|---|---|---|\n");
        PageWords english = PageText.in(InterfaceText.forLanguage("en"));
        PageWords bokmal = PageText.in(
                InterfaceText.forLanguage("nb-NO"));
        for (String token : List.of("white-paper", "black-sky")) {
            out.append("| `").append(token).append("` | ")
                    .append(english.ground(token)).append(" | ")
                    .append(bokmal.ground(token)).append(" |\n");
        }
        out.append("\nThe English phrase for `white-paper` is"
                + " `white-paper` on purpose: every exported file the"
                + " atlas has written says `Ground: white-paper.`, and"
                + " the seam was not an output change.\n\n");
        return out.toString();
    }

    /** An identity is refused, not printed - in both languages. */
    private static String refusals() {
        StringBuilder out = new StringBuilder(
                "## What is refused\n\n| asked for | `en` | `nb-NO` |\n"
                        + "|---|---|---|\n");
        PageWords english = PageText.in(InterfaceText.forLanguage("en"));
        PageWords bokmal = PageText.in(
                InterfaceText.forLanguage("nb-NO"));
        for (String id : List.of("gnomonic", "spherical-mercator")) {
            out.append("| projection `").append(id).append("` | ")
                    .append(answerOrRefusal(() -> english.projection(id)))
                    .append(" | ")
                    .append(answerOrRefusal(() -> bokmal.projection(id)))
                    .append(" |\n");
        }
        out.append("| ground `grey-dusk` | ")
                .append(answerOrRefusal(() -> english.ground("grey-dusk")))
                .append(" | ")
                .append(answerOrRefusal(() -> bokmal.ground("grey-dusk")))
                .append(" |\n\nAn id that reached a title block would"
                        + " look like a word to everything except a"
                        + " reader.\n");
        return out.toString();
    }

    private static String answerOrRefusal(java.util.function.Supplier<String> ask) {
        try {
            return ask.get();
        } catch (RuntimeException refused) {
            return "*refused*";
        }
    }

    // ---- the page, and the things measured on it -------------------

    private static SceneAssembler assembler(String chartTag) {
        return chartTag.equals("latin") ? Atlas.assembler()
                : Atlas.assemblerNamedIn(chartTag);
    }

    private static ChartScene sceneFor(String chartTag) {
        return assembler(chartTag).assemble(PAGE, WIDE, HIGH);
    }

    private static ChartRenderer renderer(PageWords words) {
        return new ChartRenderer(StarSizePolicy.DEFAULT, words);
    }

    private static String[] titleLines(ChartRenderer renderer,
                                       ChartScene scene) {
        try {
            var method = ChartRenderer.class.getDeclaredMethod(
                    "titleLines", ChartScene.class, String.class);
            method.setAccessible(true);
            return (String[]) method.invoke(renderer, scene,
                    DrawnPage.of(scene).projection().name());
        } catch (ReflectiveOperationException unreachable) {
            throw new IllegalStateException(unreachable);
        }
    }

    private static List<String> marks(ChartScene scene, PageWords words) {
        List<String> said = new ArrayList<>();
        for (ChartRenderer.DrawnMark mark : renderer(words)
                .drawnMarks(scene, ChartOptions.DEFAULTS)) {
            said.add((mark.star() != null ? mark.star().id()
                    : mark.deepSky().id()) + "@"
                    + mark.ink().getBounds());
        }
        return said;
    }

    private static long ink(ChartScene scene, PageWords words) {
        BufferedImage image = new BufferedImage(400, 300,
                BufferedImage.TYPE_INT_RGB);
        Graphics2D g = image.createGraphics();
        try {
            renderer(words).render(g, scene, noFurniture());
        } finally {
            g.dispose();
        }
        long lit = 0;
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                if ((image.getRGB(x, y) & 0xFFFFFF) != 0xFFFFFF) {
                    lit++;
                }
            }
        }
        return lit;
    }

    /** The sky's ink alone: the furniture is the thing being changed. */
    private static ChartOptions noFurniture() {
        ChartOptions sky = ChartOptions.DEFAULTS;
        return new ChartOptions(sky.deepSkyObjects(),
                sky.deepSkyLabels(), sky.constellationFigures(),
                sky.constellationBoundaries(), sky.constellationNames(),
                sky.starNames(), sky.bayerLetters(),
                sky.flamsteedNumbers(), sky.equatorialGrid(), false,
                false, sky.galaxies(), sky.openClusters(),
                sky.globularClusters(), sky.nebulae(),
                sky.planetaryNebulae(), sky.palette());
    }

    private static List<String> names(ChartScene scene) {
        List<String> said = new ArrayList<>(
                scene.geography().latinNames().values());
        java.util.Collections.sort(said);
        return said;
    }

    private static void row(StringBuilder out, String what,
                            String words) {
        out.append("| ").append(what).append(" | ")
                .append(words == null ? "—"
                        : words.replace("|", "\\|")
                                .replaceAll("\\s+", " ").trim())
                .append(" |\n");
    }
}
