package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

import juranometria.app.SettingsDialog;
import juranometria.ui.language.InterfaceText;

/**
 * The Settings dialog, in both languages, for owner review
 * (Sprint 33, issue #350).
 *
 * <p>This asks a question no contract can: <strong>does the Norwegian
 * read naturally, and does it fit the controls?</strong> The packaged
 * acceptance already proves the strings load inside the image - that
 * {@code settings.title} is {@code Innstillinger} in the real runtime
 * - so nothing here is about whether the mechanism works. It is about
 * whether the words are the right words, and whether a longer one
 * has pushed a control out of shape.
 *
 * <p>Both sheets are drawn at the <strong>same size, appearance and
 * state</strong>, so anything that differs between them differs
 * because of the language and for no other reason. The override note
 * is shown on both, because a conditional sentence a reviewer never
 * sees is a sentence nobody reviewed.
 *
 * <p>A companion text file carries every string, including the ones a
 * picture cannot show: accessible names and descriptions are read
 * aloud rather than drawn, and they are the half of a translation
 * most easily left in English without anybody noticing.
 */
public final class SettingsSheetMain {

    /**
     * What this photographer holds still: there is no window to size: the canvas width is the
     * study’s own choice.
     *
     * <p>Read by the display evidence gate, which refuses a
     * generator that declares one kind and asks the capture
     * coordinator for another.
     */
    public static final SheetCapture.Kind CAPTURE_KIND =
            SheetCapture.Kind.FIXED_CANVAS;

    private SettingsSheetMain() {
    }

    /**
     * Where the sheets go: the committed directory by default, or a
     * directory a caller names as {@code args[0]}.
     *
     * <p>`InterfaceEvidenceGateTest` runs every one of these into a
     * scratch directory and compares the result with what is
     * committed. It can only do that if a generator can be told
     * where to write; one that always writes over the evidence
     * cannot be used to check it.
     */
    private static Path out =
            Path.of("docs/studies/interface-language");

    private static final int WIDE = 560;

    public static void main(String[] args) throws Exception {
        if (args.length > 0 && !args[0].isBlank()) {
            out = Path.of(args[0]);
        }
        Files.createDirectories(out);
        // The application's own look and feel, so the controls are
        // the ones a reader meets rather than a platform default
        // nothing ships.
        SwingUtilities.invokeAndWait(() -> juranometria.app.UiTheme.apply(false));

        StringBuilder said = new StringBuilder("""
                # Every word the Settings dialog says

                Issue #350. Generated by
                `juranometria.tool.SettingsSheetMain` from compiled
                application classes and their classpath resources.
                Packaged acceptance separately verifies that the
                interface language resources ship in the application
                image.

                The images beside this file show what is drawn. This
                shows what is drawn AND what is spoken: accessible
                names and descriptions are read aloud rather than
                painted, and they are the half of a translation most
                easily left in English without anyone noticing.

                %s

                """.formatted(juranometria.tool.InterfaceLanguageStatus
                        .statement("nb-NO")));

        for (String language : List.of("en", "nb-NO")) {
            JComponent[] content = new JComponent[1];
            SwingUtilities.invokeAndWait(() ->
                    content[0] = build(language));
            SwingUtilities.invokeAndWait(() -> { });
                draw(content[0], out.resolve("settings-" + language + ".png"));
            said.append(describe(language, content[0]));
        }

        Files.writeString(out.resolve("settings-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("settings sheets: "
                + out.resolve("settings-en.png") + ", "
                + out.resolve("settings-nb-NO.png") + ", and "
                + out.resolve("settings-strings.md"));
    }

    /**
     * The dialog as a reader with this interface language sees it.
     *
     * <p>The override note is forced on for both, so the one
     * conditional sentence in this surface is reviewed rather than
     * skipped for being hard to reach.
     */
    private static JComponent build(String language) {
        return SettingsDialog.contentForStudy(language);
    }

    private static void draw(JComponent content, Path to)
            throws Exception {
        // A fixed canvas: no window, and the width is the study's
        // own choice.
        BufferedImage sheet = SheetCapture.take(content,
                // The study owns this canvas, so it establishes it -
                // before anything is proved, rather than while
                // drawing.
                //
                // Lay out at the real width FIRST, then ask how tall
                // it became. Asking before laying out reported a
                // height from a different width and cropped the
                // buttons off the sheet - a reviewer would have been
                // shown a dialog with no OK on it and no way to tell
                // that was the capture's fault.
                // Lay out every container, not just the outer one.
                // validate() does nothing useful for a component
                // that was never added to a displayable window: the
                // outer panel positioned its children while the
                // nested button row never did, so OK and Cancel were
                // placed at 0x0 and the sheet showed a dialog with
                // no way to accept it.
                SheetCapture.fixedCanvas(() -> {
                    content.setSize(WIDE,
                            content.getPreferredSize().height);
                    layoutDeeply(content);
                }),
                SheetCapture.Premise.none(),
                () -> {
            // Allocates and paints from the established geometry.
            BufferedImage drawn = new BufferedImage(WIDE,
                    content.getHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g = drawn.createGraphics();
            try {
                g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                        RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, WIDE, content.getHeight());
                content.paint(g);
            } finally {
                g.dispose();
            }
            return drawn;
        });
        ImageIO.write(sheet, "png", to.toFile());
    }

    /** Lays out a container and everything inside it. */
    private static void layoutDeeply(Container from) {
        from.doLayout();
        for (Component child : from.getComponents()) {
            if (child instanceof Container nested) {
                layoutDeeply(nested);
            }
        }
    }

    /** What every control says and is called, in reading order. */
    private static String describe(String language, JComponent content) {
        StringBuilder rows = new StringBuilder("## ")
                .append(language.equals("en") ? "English" : "Norsk bokmål")
                .append(" (`").append(language).append("`)\n\n")
                .append("| kind | shown | spoken as | explained as |\n")
                .append("|---|---|---|---|\n");
        for (Component control : reading(content)) {
            String kind;
            String shown;
            if (control instanceof JLabel label) {
                kind = "label";
                shown = label.getText();
            } else if (control instanceof AbstractButton button) {
                kind = "button";
                shown = button.getText();
            } else if (control instanceof JComboBox<?> box) {
                kind = "selector";
                List<String> items = new ArrayList<>();
                for (int i = 0; i < box.getItemCount(); i++) {
                    items.add(String.valueOf(box.getItemAt(i)));
                }
                shown = String.join(" · ", items);
            } else {
                continue;
            }
            if (shown == null || shown.isBlank()) {
                continue;
            }
            JComponent said = (JComponent) control;
            rows.append("| ").append(kind)
                    .append(" | ").append(cell(shown))
                    .append(" | ").append(cell(said.getAccessibleContext()
                            .getAccessibleName()))
                    .append(" | ").append(cell(said.getAccessibleContext()
                            .getAccessibleDescription()))
                    .append(" |\n");
        }
        return rows.append('\n').toString();
    }

    private static String cell(String text) {
        return text == null || text.isBlank()
                ? "—"
                : text.replace("|", "\\|");
    }

    private static List<Component> reading(Container from) {
        List<Component> found = new ArrayList<>();
        for (Component child : from.getComponents()) {
            found.add(child);
            if (child instanceof Container nested) {
                found.addAll(reading(nested));
            }
        }
        return found;
    }
}
