package juranometria.tool;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Stream;

/**
 * The index a build makes of the language packs it can see
 * (Sprint 33, issue #348).
 *
 * <p>The contribution contract says <em>adding a pack must be
 * enough</em>. A hand-maintained list of supported languages would
 * satisfy the letter of that and not the substance - it would move
 * the enum out of Java and into a file somebody still has to edit.
 * So nothing lists the languages. Each pack carries its own data and
 * its own provenance manifest, the build walks what is there, and
 * this writes the index runtime reads.
 *
 * <p>The index is <strong>generated into the build output, not
 * committed</strong>. A committed index would be a list again, and
 * would go stale the first time somebody added a pack without
 * running the generator.
 *
 * <p>Order is by language tag, always. A jar enumerates its entries
 * in whatever order it stored them and a directory walk follows the
 * filesystem, so an index built from either would differ between
 * machines for no reason a reader could see - and a language
 * selector would list its choices differently on two computers.
 * Sorting is what makes the index a fact about the packs rather than
 * about the disk they were read from.
 *
 * <p>Test packs never reach here. Only {@code src/resources} is
 * copied into the build, so {@code x-juranometria-test} is excluded
 * by where it lives rather than by a rule that could be forgotten.
 */
public final class SkyLanguageIndexMain {

    private SkyLanguageIndexMain() {
    }

    /** Where packs live in the build output. */
    private static final String PACKS = "resources/sky-language";

    /** What runtime reads to learn which languages exist. */
    static final String INDEX = "index.tsv";

    public static void main(String[] args) throws IOException {
        Path classes = Path.of(args.length > 0 ? args[0] : "build/classes");
        Path dir = classes.resolve(PACKS);
        if (!Files.isDirectory(dir)) {
            // No packs is a legitimate build - the atlas draws Latin
            // names with no pack at all - so this writes nothing and
            // says so, rather than failing.
            System.out.println("sky-language index: no packs present");
            return;
        }

        Map<String, String> byTag = new TreeMap<>();
        Map<String, String> declaredIn = new LinkedHashMap<>();
        List<Path> manifests = new ArrayList<>();
        try (Stream<Path> found = Files.list(dir)) {
            found.filter(p -> p.getFileName().toString().endsWith(".manifest"))
                    .sorted()
                    .forEach(manifests::add);
        }

        for (Path manifest : manifests) {
            Map<String, String> stated = keyed(manifest);
            String tag = stated.getOrDefault("tag", "").strip();
            String file = manifest.getFileName().toString();
            if (tag.isBlank()) {
                throw new IllegalStateException(file
                        + " states no language tag, so nothing could"
                        + " select it");
            }
            String already = declaredIn.put(tag, file);
            if (already != null) {
                throw new IllegalStateException("two packs claim the"
                        + " language " + tag + ": " + already + " and "
                        + file + "; one of them would silently win");
            }
            Path data = dir.resolve(
                    file.substring(0, file.length() - ".manifest".length())
                            + ".tsv");
            if (!Files.isRegularFile(data)) {
                throw new IllegalStateException(file + " declares "
                        + tag + " but its names, " + data.getFileName()
                        + ", are not beside it; an indexed language"
                        + " that cannot be loaded is worse than an"
                        + " absent one");
            }
            if ("true".equals(stated.getOrDefault("fixture", "").strip())) {
                throw new IllegalStateException(file + " declares"
                        + " itself a test fixture and is in the build"
                        + " output; fixtures live under test resources"
                        + " and must not ship");
            }
            byTag.put(tag, data.getFileName().toString() + "\t"
                    + stated.getOrDefault("display-name", tag).strip());
        }

        StringBuilder index = new StringBuilder("""
                # Generated by juranometria.tool.SkyLanguageIndexMain.
                # Not committed: it is derived from the packs present
                # in this build, so adding a pack is enough and no
                # list is maintained by hand. Sorted by language tag,
                # never by the order a directory or a jar happens to
                # enumerate.
                tag\tnames\tdisplay-name
                """);
        byTag.forEach((tag, rest) ->
                index.append(tag).append('\t').append(rest).append('\n'));
        Files.writeString(dir.resolve(INDEX), index.toString(),
                StandardCharsets.UTF_8);

        System.out.printf(Locale.ROOT,
                "sky-language index: %d pack%s - %s%n", byTag.size(),
                byTag.size() == 1 ? "" : "s",
                String.join(", ", byTag.keySet()));
    }

    private static Map<String, String> keyed(Path file) throws IOException {
        Map<String, String> stated = new LinkedHashMap<>();
        for (String line : Files.readAllLines(file)) {
            if (line.isBlank() || line.startsWith("#")) {
                continue;
            }
            int is = line.indexOf('=');
            if (is > 0) {
                stated.put(line.substring(0, is).strip(),
                        line.substring(is + 1).strip());
            }
        }
        return stated;
    }
}
