package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.ListCellRenderer;
import javax.swing.SwingUtilities;

import juranometria.sky.Observer;
import juranometria.solar.SolarSystemService;
import juranometria.ui.language.InterfaceText;
import juranometria.ui.solar.SunTableDialog;

/**
 * Every word the Sun table says, photographed (Sprint 35, issue #400).
 *
 * <p>The production dialog, built through
 * {@code SunTableDialog.packedForStudy} over a stated observer and the
 * bundled pack, in both languages, in the states a reader meets: the
 * single instant, a range with its appended end, a refused range, and
 * a southern observer with the Sun below the horizon; one dark
 * capture per language. The companion records the window's own two
 * channels and every shown, hovered and spoken string, plus the
 * column explanations a screen reader hears from the headings.
 *
 * <p>Packed: the dialog states no size of its own, so the coordinator
 * settles the pack and holds it, as for the About and Export dialogs.
 */
public final class SunTableSheetMain {

    public static final SheetCapture.Kind CAPTURE_KIND =
            SheetCapture.Kind.PACKED;

    private static Path out = Path.of("docs/studies/interface-language");

    private record State(String name, String title, Observer observer,
                         boolean range, String end, String note) {
    }

    private static final Observer OSLO = new Observer(59.91, 10.75,
            Instant.parse("2026-06-21T10:00:00Z"));

    private static final List<State> STATES = List.of(
            new State("instant", "One instant, Oslo at midsummer", OSLO,
                    false, null,
                    "The fresh state: a single row at the instant Place"
                            + " and Time holds. The Sun stands 51° high"
                            + " to the south-east."),
            new State("range", "A range with an appended end", OSLO,
                    true, "2026-06-24 07:30",
                    "Daily rows from the instant, and an end that is not"
                            + " on the grid, added last and marked †."
                            + " The status line says so."),
            new State("refused", "A range that runs backwards", OSLO,
                    true, "2026-06-21 09:00",
                    "The end is before the start. The table is empty"
                            + " and the status line says why; nothing is"
                            + " guessed."),
            new State("quito", "Quito at the December solstice",
                    new Observer(-0.18, -78.5,
                            Instant.parse("2026-12-21T20:50:09Z")),
                    false, null,
                    "An equatorial observer at the IMCCE's solstice"
                            + " instant: the Sun is up, 32° high; the"
                            + " instant is shown to the minute, rounded."));

    private SunTableSheetMain() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length > 0 && !args[0].isBlank()) {
            out = Path.of(args[0]);
        }
        if (java.awt.GraphicsEnvironment.isHeadless()) {
            System.err.println("a packed dialog needs a display");
            System.exit(1);
        }
        Files.createDirectories(out);
        SolarSystemService service = SolarSystemService.load();
        StringBuilder said = new StringBuilder();
        said.append("""
                # Every word the Sun table says

                Issue #400. Generated by `juranometria.tool.SunTableSheetMain`
                from compiled application classes and their classpath
                resources, over the bundled Solar System pack. Packaged
                acceptance separately verifies that the pack and the
                interface language resources ship in the application image.

                %s

                ## The window, not a panel

                Each capture is the production dialog built through
                `SunTableDialog.packedForStudy`, which has no "English if
                omitted" overload. The title and the window description are
                read from the `JDialog` itself; every shown, hovered and
                spoken string is walked from the content; the column
                headings' explanations, which a screen reader hears and a
                hover shows, are listed from the model.

                ## What is translated here, and what is not

                Every number is notation: right ascension, declination,
                degrees, distance, diameter and the instant are formatted
                in `Locale.ROOT` by `SunTableFormat` and are identical in
                both languages, because a value must parse if a reader
                carries it into Place and Time. The words are the
                language's: the headings, the status line, the refusals,
                and the status below the horizon. Access letters are
                language too, and no two controls share one.

                """.formatted(InterfaceLanguageStatus.statement("nb-NO")));
        int sheet = 1;
        for (String language : List.of("en", "nb-NO")) {
            InterfaceText text = InterfaceText.forLanguage(language);
            said.append("## ").append(language.equals("en") ? "English"
                    : "Norsk bokmål").append(" (`").append(language)
                    .append("`)\n\n");
            for (State state : STATES) {
                said.append("### ").append(state.title()).append("\n\n")
                        .append(state.note()).append("\n\n")
                        .append(draw(text, service, state, false,
                                out.resolve("suntable-" + language + "-"
                                        + (sheet++) + "-" + state.name()
                                        + ".png")))
                        .append('\n');
            }
            said.append("### The instant, in the dark appearance\n\n")
                    .append(draw(text, service, STATES.get(0), true,
                            out.resolve("suntable-" + language + "-"
                                    + (sheet++) + "-instant-dark.png")))
                    .append('\n');
            said.append(columns(text));
        }
        Files.writeString(out.resolve("suntable-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("sun table sheets: " + (sheet - 1) + " images and "
                + out.resolve("suntable-strings.md"));
    }

    /** What each heading says to a screen reader, per language. */
    private static String columns(InterfaceText said) {
        StringBuilder out = new StringBuilder(
                "#### The headings, and what they explain\n\n"
                        + "| heading | explanation |\n|---|---|\n");
        juranometria.ui.solar.SunTableModel model =
                new juranometria.ui.solar.SunTableModel(said);
        for (int c = 0; c < model.getColumnCount(); c++) {
            out.append("| ").append(model.getColumnName(c)).append(" | ")
                    .append(model.columnExplanation(c).replace("|", "\\|"))
                    .append(" |\n");
        }
        return out.append('\n').toString();
    }

    private static String draw(InterfaceText said, SolarSystemService service,
                               State state, boolean dark, Path to)
            throws Exception {
        JFrame[] owner = new JFrame[1];
        SunTableDialog[] dialog = new SunTableDialog[1];
        SheetCapture.tracing(to.getFileName() + " state=" + state.name());
        try {
            SwingUtilities.invokeAndWait(() -> {
                juranometria.app.UiTheme.apply(dark);
                owner[0] = new JFrame("study");
                dialog[0] = SunTableDialog.packedForStudy(owner[0],
                        () -> state.observer(), service, said);
                if (state.range()) {
                    dialog[0].content().rangeView.setSelected(true);
                    dialog[0].content().end.setText(state.end());
                    dialog[0].content().update();
                }
            });
            return capture(dialog[0], state, to);
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (dialog[0] != null) {
                    dialog[0].dispose();
                }
                if (owner[0] != null) {
                    owner[0].dispose();
                }
            });
        }
    }

    /** The state this sheet claims, asked inside the coordinator's block. */
    private static String disagreement(SunTableDialog dialog, State state) {
        SunTableDialog.Content content = dialog.content();
        if (content.rangeView.isSelected() != state.range()) {
            return "the view is " + (content.rangeView.isSelected()
                    ? "the range" : "the instant") + ", not the state's";
        }
        if (state.range() && !state.end().equals(content.end.getText())) {
            return "the end field reads " + content.end.getText();
        }
        return null;
    }

    private static String capture(SunTableDialog dialog, State state, Path to)
            throws Exception {
        Set<String> said = new LinkedHashSet<>();
        JComponent content = (JComponent) dialog.getContentPane();
        BufferedImage image = SheetCapture.take(dialog, content,
                SheetCapture.packed(),
                held -> {
                    String wrong = disagreement(dialog, state);
                    return wrong == null ? null
                            : "it claims \"" + state.title() + "\" and " + wrong;
                },
                () -> {
                    BufferedImage drawn = new BufferedImage(
                            Math.max(1, content.getWidth()),
                            Math.max(1, content.getHeight()),
                            BufferedImage.TYPE_INT_RGB);
                    Graphics2D g = drawn.createGraphics();
                    try {
                        g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                                RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                        g.setColor(Color.WHITE);
                        g.fillRect(0, 0, drawn.getWidth(), drawn.getHeight());
                        content.paint(g);
                    } finally {
                        g.dispose();
                    }
                    add(said, dialog.getTitle(), "");
                    add(said, dialog.getAccessibleContext()
                            .getAccessibleDescription(), "");
                    collect(content, said);
                    return drawn;
                });
        ImageIO.write(image, "png", to.toFile());
        StringBuilder out = new StringBuilder();
        out.append("![](").append(to.getFileName()).append(")\n\n")
                .append("Packed ").append(image.getWidth()).append(" × ")
                .append(image.getHeight()).append(" px.\n\n")
                .append("| shown, hovered or spoken |\n|---|\n");
        for (String one : said) {
            out.append("| ").append(one.replace("|", "\\|")).append(" |\n");
        }
        return out.toString();
    }

    private static void collect(Container from, Set<String> said) {
        if (from instanceof JComponent self) {
            record(self, said);
        }
        for (Component child : from.getComponents()) {
            if (child instanceof JComponent widget) {
                record(widget, said);
            }
            if (child instanceof Container nested) {
                collect(nested, said);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static void record(JComponent widget, Set<String> said) {
        String off = widget.isEnabled() ? "" : " [unavailable]";
        if (widget instanceof AbstractButton button) {
            add(said, button.getText(), off);
        }
        if (widget instanceof JLabel label) {
            add(said, label.getText(), off);
        }
        if (widget instanceof JComboBox) {
            JComboBox<Object> box = (JComboBox<Object>) widget;
            ListCellRenderer<Object> renderer =
                    (ListCellRenderer<Object>) box.getRenderer();
            JList<Object> list = new JList<>();
            for (int i = 0; i < box.getItemCount(); i++) {
                Component cell = renderer.getListCellRendererComponent(
                        list, box.getItemAt(i), i, false, false);
                if (cell instanceof JLabel label) {
                    add(said, label.getText(), off);
                }
            }
        }
        if (widget instanceof JTable table) {
            for (int c = 0; c < table.getColumnCount(); c++) {
                add(said, table.getColumnName(c), off);
            }
            for (int r = 0; r < table.getRowCount(); r++) {
                StringBuilder row = new StringBuilder();
                for (int c = 0; c < table.getColumnCount(); c++) {
                    row.append(c == 0 ? "" : " · ")
                            .append(table.getValueAt(r, c));
                }
                add(said, row.toString(), off);
            }
        }
        add(said, widget.getToolTipText(), off);
        if (widget.getAccessibleContext() != null) {
            add(said, widget.getAccessibleContext().getAccessibleName(), off);
            add(said, widget.getAccessibleContext().getAccessibleDescription(),
                    off);
        }
    }

    private static void add(Set<String> said, String text, String off) {
        if (text == null || text.isBlank()) {
            return;
        }
        String plain = text.replaceAll("<[^>]+>", "").replace('\n', ' ')
                .replaceAll("\\s+", " ").strip();
        if (!plain.isEmpty()) {
            said.add(plain + off);
        }
    }
}
