package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import juranometria.ui.language.InterfaceText;
import juranometria.ui.language.SwingText;

/**
 * The toolkit's own dialogs, in both languages
 * (Sprint 33, issue #350).
 *
 * <p>Every sentence in these was already the atlas's. The frame
 * around them was Swing's, resolved against the operating system, so
 * a Norwegian reader answered a Norwegian question with
 * <strong>Yes</strong> and <strong>No</strong> - and the JDK ships no
 * Norwegian for Swing at all, so it happened on every machine.
 *
 * <p>Drawn from <strong>real components</strong> under the
 * application's own look and feel, with the toolkit's words installed
 * the way the application installs them. Three forms - the
 * confirmation a reader answers, the message that reports what
 * happened, and the file chooser - in English and Norwegian.
 */
public final class SwingChromeSheetMain {

    /**
     * What this photographer holds still: production only packs this window, so its size is its
     * layout’s preference.
     *
     * <p>Read by the display evidence gate, which refuses a
     * generator that declares one kind and asks the capture
     * coordinator for another.
     */
    public static final SheetCapture.Kind CAPTURE_KIND =
            SheetCapture.Kind.PACKED;

    private SwingChromeSheetMain() {
    }

    /**
     * Where the sheets go: the committed directory by default, or a
     * directory a caller names as {@code args[0]}.
     *
     * <p>`InterfaceEvidenceGateTest` runs every one of these into a
     * scratch directory and compares the result with what is
     * committed. It can only do that if a generator can be told
     * where to write; one that always writes over the evidence
     * cannot be used to check it.
     */
    private static Path out =
            Path.of("docs/studies/interface-language");

    /** One dialog form, and the atlas's own sentence inside it. */
    private record Form(String name, String title, String key,
                        String note) {
    }

    private static final List<Form> FORMS = List.of(
            new Form("confirm", "The question a reader answers",
                    "export.replace.question",
                    "Asked before an existing file is replaced. The"
                            + " question was always the atlas's; the"
                            + " two buttons beneath it were the"
                            + " toolkit's."),
            new Form("message", "What happened, reported",
                    "export.written.message",
                    "Shown after a sheet is written. One button, and"
                            + " `OK` is the same word in both"
                            + " languages - which is why it proves"
                            + " nothing on its own and the"
                            + " confirmation above is the telling"
                            + " one."),
            new Form("chooser", "Where the sheet is put", null,
                    "The largest of the three: thirty-four of the"
                            + " forty-one keys. Six of its buttons say"
                            + " one thing to a pointer and another to"
                            + " a screen reader, and both halves are"
                            + " listed in the companion."));

    public static void main(String[] args) throws Exception {
        if (args.length > 0 && !args[0].isBlank()) {
            out = Path.of(args[0]);
        }
        if (java.awt.GraphicsEnvironment.isHeadless()) {
            System.err.println("these are dialogs and need a display");
            System.exit(1);
        }
        Files.createDirectories(out);
        StringBuilder said = new StringBuilder();
        said.append("""
                # The toolkit's own words, in both languages

                Issue #350. Generated by
                `juranometria.tool.SwingChromeSheetMain` from compiled
                application classes and their classpath resources.

                %s

                Swing supplies the buttons, labels, hovers and spoken
                names of these three dialogs from its own resource
                bundle, resolved against `Locale.getDefault()` - the
                **operating system**, not the language the reader
                chose. The JDK ships no Norwegian bundle at all, so a
                Norwegian reader met English here on every machine,
                and a reader on a German desktop met German under
                Norwegian sentences.

                The atlas installs its own over them, in **both**
                languages: an English interface on a German desktop
                had the same defect in the other direction.

                Forty-one keys. **Access keys are not among them** -
                Swing's `…Mnemonic` entries stay with the eighteen
                access letters already deferred.

                """.formatted(juranometria.tool.InterfaceLanguageStatus
                        .statement("nb-NO")));

        int sheet = 1;
        for (String language : List.of("en", "nb-NO")) {
            InterfaceText words = InterfaceText.forLanguage(language);
            said.append("## ").append(language.equals("en") ? "English"
                            : "Norsk bokmål").append(" (`")
                    .append(language).append("`)\n\n");
            for (Form form : FORMS) {
                said.append("### ").append(form.title()).append("\n\n")
                        .append(form.note()).append("\n\n")
                        .append(draw(language, words, form,
                                out.resolve("swing-" + language + "-"
                                        + (sheet++) + "-" + form.name()
                                        + ".png")))
                        .append('\n');
            }
        }
        said.append(everyKey());
        Files.writeString(out.resolve("swing-chrome-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        removeFixtures();
        System.out.println("swing chrome sheets: 6 images and "
                + out.resolve("swing-chrome-strings.md"));
    }

    /** All forty-one, side by side, hovers and spoken names included. */
    private static String everyKey() {
        SwingText english = SwingText.in(InterfaceText.forLanguage("en"));
        SwingText norsk = SwingText.in(
                InterfaceText.forLanguage("nb-NO"));
        StringBuilder out = new StringBuilder(
                "## Every key the atlas installs\n\n"
                        + "| toolkit key | channel | `en` | `nb-NO` |\n"
                        + "|---|---|---|---|\n");
        for (String key : SwingText.toolkitKeys()) {
            out.append("| `").append(key).append("` | ")
                    .append(channelOf(key)).append(" | ")
                    .append(english.say(key)).append(" | ")
                    .append(norsk.say(key)).append(" |\n");
        }
        return out.append("\n**")
                .append(SwingText.toolkitKeys().size())
                .append(" keys.**\n").toString();
    }

    /** How a reader meets this one: by eye, by pointer, or by ear. */
    private static String channelOf(String key) {
        if (key.endsWith("AccessibleName")) {
            return "spoken";
        }
        if (key.endsWith("ToolTipText")) {
            return "hovered";
        }
        return "shown";
    }

    /** One form in one language, from a real component. */
    private static String draw(String language, InterfaceText words,
                               Form form, Path to) throws Exception {
        Set<String> said = new LinkedHashSet<>();
        BufferedImage[] image = new BufferedImage[1];
        Container[] probe = new Container[1];
        JDialog[] holder = new JDialog[1];
        try {
            SwingUtilities.invokeAndWait(() -> {
                // The application's own ordered pair (#362, #350): a
                // look and feel first, then the words, because
                // installing a look and feel replaces the defaults
                // table.
                juranometria.app.UiTheme.apply(false);
                SwingText.in(words).installInto(UIManager.getDefaults());

                probe[0] = form.name().equals("chooser")
                        ? chooser(words)
                        : pane(form, words);
                holder[0] = new JDialog();
                holder[0].setContentPane(probe[0]);
            });
            // Building and painting are two steps, not one, because
            // the rule has to run between them: pack to a fixed
            // point, drain, settle, and own focus nowhere. A dialog
            // packed once is a guess at its own size.
            image[0] = juranometria.tool.SheetCapture.of(holder[0],
                    (JComponent) probe[0], SheetCapture.packed());
            SwingUtilities.invokeAndWait(() -> {
                walk(probe[0], said);
                if (form.name().equals("chooser")) {
                    requireSaveState(said, SwingText.in(words));
                }
            });
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (holder[0] != null) {
                    holder[0].dispose();
                }
            });
        }
        ImageIO.write(image[0], "png", to.toFile());

        StringBuilder out = new StringBuilder();
        out.append("![](").append(to.getFileName()).append(")\n\n")
                .append(image[0].getWidth()).append(" × ")
                .append(image[0].getHeight()).append(" px, `")
                .append(language).append("`.\n\n")
                .append("| what a reader meets |\n|---|\n");
        for (String one : said) {
            out.append("| ").append(one.replace("|", "\\|"))
                    .append(" |\n");
        }
        return out.toString();
    }

    private static Container pane(Form form, InterfaceText words) {
        boolean confirm = form.name().equals("confirm");
        String sentence = confirm
                ? words.say(form.key(), "orion.svg", "~/Documents")
                : words.say(form.key(), "orion.svg", "SVG", "194460");
        return new JOptionPane(sentence,
                confirm ? JOptionPane.WARNING_MESSAGE
                        : JOptionPane.INFORMATION_MESSAGE,
                confirm ? JOptionPane.YES_NO_OPTION
                        : JOptionPane.DEFAULT_OPTION);
    }

    /**
     * The chooser production shows: a SAVE dialog.
     *
     * <p>A default {@code JFileChooser} is in its OPEN state and says
     * {@code Open}, {@code Look In:} and "Open selected file". The
     * atlas calls {@code showSaveDialog}, so a sheet of the open
     * state would be a picture of a surface no reader meets -
     * approving words the export never shows while leaving the ones
     * it does show unreviewed.
     */
    private static Container chooser(InterfaceText words) {
        JFileChooser chooser = new JFileChooser(fixture());
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        chooser.setDialogTitle(words.say("export.chooser.title"));
        chooser.setSelectedFile(new java.io.File("orion.svg"));
        return chooser;
    }

    /**
     * A folder of example reader data, made for the photograph.
     *
     * <p>This sheet used to open on whatever {@code JFileChooser}
     * opens on by default, which is the <strong>home directory of
     * whoever ran it</strong>. The committed sheets therefore
     * carried a listing of my machine - including scratch
     * directories with generated names - and could never reproduce:
     * 11,019 pixels of the Norwegian sheet changed between two
     * commits because files had come and gone in my home folder.
     *
     * <p>Evidence may not depend on the machine's contents. This is
     * a fixed set of plausible names in a folder with a fixed name,
     * built fresh each run and removed afterwards, so the picture is
     * of the chooser rather than of a desk.
     */
    private static java.io.File fixture() {
        try {
            // A FIXED location, not a temp directory with a
            // generated name. CI found the difference: this sheet
            // disagreed between two runs on Linux, where the
            // chooser's directory control shows more of the path
            // than macOS does - so the random parent's name was in
            // the picture. A fixture whose own name changes every
            // run is not a fixture.
            Path parent = Path.of("build", "chrome-fixture");
            removeTree(parent);
            Path folder = Files.createDirectories(
                    parent.resolve("Documents"));
            FIXTURES.add(parent);
            for (String name : List.of("Kart", "Notater")) {
                Files.createDirectory(folder.resolve(name));
            }
            for (String name : List.of("andromeda.pdf", "orion.svg",
                    "perseus.png")) {
                Files.writeString(folder.resolve(name), "");
            }
            return folder.toFile();
        } catch (java.io.IOException e) {
            throw new IllegalStateException("the chooser needs a"
                    + " folder to show, and one could not be made", e);
        }
    }

    /** Fixture folders to remove when the sheets are written. */
    private static final List<Path> FIXTURES = new java.util.ArrayList<>();

    /** Removes every fixture this run created. */
    private static void removeFixtures() throws java.io.IOException {
        for (Path parent : FIXTURES) {
            removeTree(parent);
        }
        FIXTURES.clear();
    }

    /** Clears a fixture, whether or not a previous run left one. */
    private static void removeTree(Path parent) throws java.io.IOException {
        if (!Files.exists(parent)) {
            return;
        }
        try (var files = Files.walk(parent)) {
            files.sorted(java.util.Comparator.reverseOrder())
                    .forEach(one -> one.toFile().delete());
        }
    }

    /**
     * The three values that say this is the save chooser.
     *
     * <p>Asserted before anything is written: a generator that fell
     * back to the open state would otherwise publish a plausible
     * sheet of the wrong surface.
     */
    private static void requireSaveState(Set<String> said,
                                         SwingText words) {
        for (String key : List.of("FileChooser.saveButtonText",
                "FileChooser.saveInLabelText",
                "FileChooser.saveButtonToolTipText")) {
            String expected = words.say(key);
            if (said.stream().noneMatch(one ->
                    one.endsWith(": " + expected))) {
                throw new IllegalStateException("this is not the save"
                        + " chooser: it does not say \"" + expected
                        + "\" (" + key + "). Production calls"
                        + " showSaveDialog, and a sheet of the open"
                        + " state approves words no reader meets.");
            }
        }
    }

    private static void walk(Container from, Set<String> said) {
        for (Component child : from.getComponents()) {
            if (child instanceof AbstractButton button) {
                add(said, "shown", button.getText());
                add(said, "hovered", button.getToolTipText());
                if (button.getAccessibleContext() != null) {
                    add(said, "spoken", button.getAccessibleContext()
                            .getAccessibleName());
                }
            }
            if (child instanceof JLabel label) {
                add(said, "shown", label.getText());
            }
            if (child instanceof JComponent widget) {
                add(said, "hovered", widget.getToolTipText());
            }
            if (child instanceof Container nested) {
                walk(nested, said);
            }
        }
    }

    private static void add(Set<String> said, String channel,
                            String text) {
        if (text == null || text.isBlank()
                || text.chars().noneMatch(Character::isLetter)) {
            return;
        }
        said.add(channel + ": " + text.replaceAll("<[^>]*>", " ")
                .replaceAll("\\s+", " ").trim());
    }

}
