package juranometria.tool;

import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/**
 * The test-and-evidence friction study (Sprint 26, issue #241).
 *
 * <p>Writes the measurements the maintenance gate stands on:
 * mechanical inventories of shared-state touches, display
 * dependence, input routes, premises, and generated evidence.
 * Deterministic - it reads committed sources and prints sorted
 * facts, so regenerating it on the same tree yields the same bytes.
 *
 * <p>Timings are deliberately absent: elapsed time depends on the
 * machine, the cache and the queue, and a byte-reproducible report
 * must not carry numbers that honest regeneration would change.
 * They live in the decision document with their conditions stated.
 */
public final class TestEvidenceStudyMain {

    private TestEvidenceStudyMain() {
    }

    public static void main(String[] args) throws IOException {
        List<TestEvidenceScan.File> files =
                TestEvidenceScan.scan(Path.of("test"));
        PrintStream out = System.out;

        out.println("# Test and CI evidence: the measurements");
        out.println();
        out.println("Generated by `make test-evidence-study`"
                + " (juranometria.tool.TestEvidenceStudyMain), a"
                + " mechanical scan of the committed test sources."
                + " The classification rules are the scanner's"
                + " (`TestEvidenceScan`); what a textual rule cannot"
                + " decide is assigned in the decision document, not"
                + " guessed here.");
        out.println();

        // ---- shared state ------------------------------------------
        out.println("## Process-wide state the suite touches");
        out.println();
        List<TestEvidenceScan.File> touching = files.stream()
                .filter(f -> !f.globalState().isEmpty()).toList();
        out.println("| file | touches | protection |");
        out.println("|---|---|---|");
        for (TestEvidenceScan.File f : touching) {
            out.printf("| %s | %s | %s |%n", f.path(),
                    String.join(", ", f.globalState()),
                    f.unprotectedState().isEmpty() ? f.stateClass()
                            : "UNPROTECTED: " + String.join(", ",
                                    f.unprotectedState()));
        }
        out.println();
        out.printf("**%d files** touch process-wide state: %d"
                        + " protected by the shared SwingSession"
                        + " guard, %d restoring locally - the"
                        + " JUnit-fixture preference shape the"
                        + " consolidation (#224) deliberately kept,"
                        + " plus the guard itself - and %d"
                        + " unprotected.%n",
                touching.size(),
                count(touching, "protected-shared"),
                count(touching, "protected-locally"),
                count(touching, "UNPROTECTED"));
        out.println();
        long realPrefs = 0;
        try (Stream<Path> tree = Files.walk(Path.of("test"))) {
            for (Path source : tree
                    .filter(p -> p.toString().endsWith(".java"))
                    .sorted().toList()) {
                if (TestEvidenceScan.opensRealPreferences(
                        Files.readString(source))) {
                    realPrefs++;
                }
            }
        }
        out.printf("**%d test files** open the application's real"
                + " preference node. Zero is the standing state, and"
                + " the gate pins it there.%n", realPrefs);
        out.println();

        // ---- evidence executables under src ------------------------
        out.println("## Evidence executables under src");
        out.println();
        out.println("The study mains and the packaged acceptance are"
                + " single-JVM runs: a look and feel or a default font"
                + " they set dies with the process, but a preference"
                + " write outlives it. The same mechanical rule is"
                + " applied and the decision document reads each"
                + " flagged case for which of those it is.");
        out.println();
        List<TestEvidenceScan.File> executables =
                TestEvidenceScan.scanEvidenceExecutables().stream()
                        .filter(f -> !f.globalState().isEmpty())
                        .toList();
        out.println("| executable | touches | protection |");
        out.println("|---|---|---|");
        for (TestEvidenceScan.File f : executables) {
            out.printf("| %s | %s | %s |%n", f.path(),
                    String.join(", ", f.globalState()),
                    f.unprotectedState().isEmpty() ? f.stateClass()
                            : "UNPROTECTED: " + String.join(", ",
                                    f.unprotectedState()));
        }
        out.println();
        out.printf("**%d evidence executables** touch process-wide"
                        + " state; %d carry an unpaired touch.%n",
                executables.size(),
                executables.stream().filter(f ->
                        !f.unprotectedState().isEmpty()).count());
        out.println();

        // ---- display dependence ------------------------------------
        out.println("## Display-dependent tests, their premises and"
                + " their routes");
        out.println();
        List<TestEvidenceScan.File> display = files.stream()
                .filter(TestEvidenceScan.File::displayDependent)
                .toList();
        out.println("| file | premises stated | routes used |");
        out.println("|---|---|---|");
        for (TestEvidenceScan.File f : display) {
            out.printf("| %s | %s | %s |%n", f.path(),
                    f.premises().isEmpty() ? "none"
                            : String.join(", ", f.premises()),
                    f.routes().isEmpty() ? "none"
                            : String.join(", ", f.routes()));
        }
        out.println();
        out.printf("**%d display-dependent files.** %d state a"
                        + " focused-window or focus-owner premise, %d"
                        + " state a reachability premise, and %d use a"
                        + " back-door action (doClick or"
                        + " postActionEvent) somewhere - each either a"
                        + " menu convention or a debt the discipline"
                        + " issue #243 owns.%n",
                display.size(),
                display.stream().filter(f ->
                        f.premises().contains("focused-window")
                                || f.premises().contains("focus-owner"))
                        .count(),
                display.stream().filter(f ->
                        f.premises().contains("point-reachable"))
                        .count(),
                display.stream().filter(f ->
                        f.routes().contains("back-door-click")
                                || f.routes().contains(
                                        "back-door-commit")).count());
        out.println();

        // ---- routes across the whole suite --------------------------
        out.println("## Input routes across the whole suite");
        out.println();
        out.printf("- files dispatching real pointer events: %d%n",
                files.stream().filter(f ->
                        f.routes().contains("pointer-events")).count());
        out.printf("- files dispatching real keyboard events: %d%n",
                files.stream().filter(f ->
                        f.routes().contains("keyboard-events")).count());
        out.printf("- files using doClick somewhere: %d%n",
                files.stream().filter(f ->
                        f.routes().contains("back-door-click")).count());
        out.printf("- files using postActionEvent somewhere: %d%n",
                files.stream().filter(f ->
                        f.routes().contains("back-door-commit")).count());
        out.println();

        // ---- platform assumptions ----------------------------------
        out.println("## Platform assumptions written into tests");
        out.println();
        List<TestEvidenceScan.File> assuming = files.stream()
                .filter(f -> !f.platformAssumptions().isEmpty())
                .toList();
        for (TestEvidenceScan.File f : assuming) {
            out.printf("- %s: %s%n", f.path(),
                    String.join(", ", f.platformAssumptions()));
        }
        out.printf("%n**%d files** name a look and feel, a shortcut"
                + " mask or an operating system.%n", assuming.size());
        out.println();

        // ---- event-thread traffic ----------------------------------
        out.println("## Event-thread traffic, counted not judged");
        out.println();
        out.println("Whether a particular read happens on the event"
                + " thread is control flow, which text cannot decide;"
                + " issue #220 proved the cost of guessing, three"
                + " times. What can be counted is the traffic:");
        out.println();
        int reads = files.stream()
                .mapToInt(TestEvidenceScan.File::liveReads).sum();
        int handOffs = files.stream()
                .mapToInt(TestEvidenceScan.File::edtHandOffs).sum();
        out.printf("- reads of live chart state (currentScene,"
                + " pageOffsetY, navigation.state): **%d** across"
                + " the suite%n", reads);
        out.printf("- explicit event-thread hand-offs (invokeAndWait):"
                + " **%d**%n", handOffs);
        out.println();

        // ---- generated evidence ------------------------------------
        out.println("## Generated evidence, classified");
        out.println();
        java.util.Map<String, List<String>> classes =
                new java.util.TreeMap<>();
        try (Stream<Path> tree = Files.walk(Path.of("docs/studies"))) {
            for (Path artifact : tree.filter(Files::isRegularFile)
                    .sorted().toList()) {
                classes.computeIfAbsent(
                        TestEvidenceScan.artifactClass(
                                artifact.getFileName().toString()),
                        k -> new ArrayList<>()).add(artifact.toString()
                        .replace(java.io.File.separatorChar, '/'));
            }
        }
        // The SOFA oracle's generator lives under scripts, which the
        // docs walk cannot see - the decision promised both halves
        // of the fixture and the first scan reached only the data
        // (review).
        try (Stream<Path> tree = Files.walk(Path.of("scripts"))) {
            for (Path artifact : tree.filter(Files::isRegularFile)
                    .filter(f -> f.toString().endsWith(".c"))
                    .sorted().toList()) {
                classes.computeIfAbsent(
                        TestEvidenceScan.artifactClass(
                                artifact.getFileName().toString()),
                        k -> new ArrayList<>()).add(artifact.toString()
                        .replace(java.io.File.separatorChar, '/'));
            }
        }
        out.println("| class | the contract | files |");
        out.println("|---|---|---|");
        out.printf("| deterministic-report | regenerates"
                        + " byte-for-byte on the same tree | %d |%n",
                classes.getOrDefault("deterministic-report",
                        List.of()).size());
        out.printf("| byte-exact-fixture | committed data with"
                        + " provenance; never regenerated casually"
                        + " | %d |%n",
                classes.getOrDefault("byte-exact-fixture",
                        List.of()).size());
        out.printf("| renderer-drawn | byte-reproducible per"
                        + " machine; production ink, no widgets"
                        + " | %d |%n",
                classes.getOrDefault("renderer-drawn",
                        List.of()).size());
        out.printf("| widget-rendered-inspection | Swing painted"
                        + " offscreen; platform-rendered, reviewed by"
                        + " eye | %d |%n",
                classes.getOrDefault("widget-rendered-inspection",
                        List.of()).size());
        out.printf("| session-photograph | a packed window on a"
                        + " display; drifts between desktop sessions"
                        + " | %d |%n",
                classes.getOrDefault("session-photograph",
                        List.of()).size());
        out.println();
        out.println("The byte-exact fixtures:");
        for (String path : classes.getOrDefault("byte-exact-fixture",
                List.of())) {
            out.println("- " + path);
        }
        out.println();
        out.println("The widget-rendered artifacts (a new one arrives"
                + " by a reviewed addition to the scanner's list, not"
                + " a habit):");
        for (String path : classes.getOrDefault(
                "widget-rendered-inspection", List.of())) {
            out.println("- " + path);
        }
        out.println();
        out.println("The session photographs:");
        for (String path : classes.getOrDefault("session-photograph",
                List.of())) {
            out.println("- " + path);
        }
        out.println();
        out.println("The reference images under docs/reference are"
                + " **canonical**: CI compares rendered bytes against"
                + " them, and changing one is a reviewed decision.");
    }

    private static long count(List<TestEvidenceScan.File> files,
                              String stateClass) {
        return files.stream()
                .filter(f -> f.stateClass().equals(stateClass)).count();
    }
}
