package juranometria.tool;

import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/**
 * The test-and-evidence friction study (Sprint 26, issue #241).
 *
 * <p>Writes the measurements the maintenance gate stands on:
 * mechanical inventories of shared-state touches, display
 * dependence, input routes, premises, and generated evidence.
 * Deterministic - it reads committed sources and prints sorted
 * facts, so regenerating it on the same tree yields the same bytes.
 *
 * <p>Timings are deliberately absent: elapsed time depends on the
 * machine, the cache and the queue, and a byte-reproducible report
 * must not carry numbers that honest regeneration would change.
 * They live in the decision document with their conditions stated.
 */
public final class TestEvidenceStudyMain {

    private TestEvidenceStudyMain() {
    }

    public static void main(String[] args) throws IOException {
        List<TestEvidenceScan.File> files =
                TestEvidenceScan.scan(Path.of("test"));
        PrintStream out = System.out;

        out.println("# Test and CI evidence: the measurements");
        out.println();
        out.println("Generated by `make test-evidence-study`"
                + " (juranometria.tool.TestEvidenceStudyMain), a"
                + " mechanical scan of the committed test sources."
                + " The classification rules are the scanner's"
                + " (`TestEvidenceScan`); what a textual rule cannot"
                + " decide is assigned in the decision document, not"
                + " guessed here.");
        out.println();

        // ---- shared state ------------------------------------------
        out.println("## Process-wide state the suite touches");
        out.println();
        List<TestEvidenceScan.File> touching = files.stream()
                .filter(f -> !f.globalState().isEmpty()).toList();
        out.println("| file | touches | protection |");
        out.println("|---|---|---|");
        for (TestEvidenceScan.File f : touching) {
            out.printf("| %s | %s | %s |%n", f.path(),
                    String.join(", ", f.globalState()), f.stateClass());
        }
        out.println();
        out.printf("**%d files** touch process-wide state: %d"
                        + " protected by the shared SwingSession"
                        + " guard, %d restoring locally (correct but"
                        + " duplicated - the consolidation issue #224"
                        + " owns them), %d unprotected.%n",
                touching.size(),
                count(touching, "protected-shared"),
                count(touching, "protected-locally"),
                count(touching, "UNPROTECTED"));
        out.println();
        long realPrefs = 0;
        try (Stream<Path> tree = Files.walk(Path.of("test"))) {
            for (Path source : tree
                    .filter(p -> p.toString().endsWith(".java"))
                    .sorted().toList()) {
                if (TestEvidenceScan.opensRealPreferences(
                        Files.readString(source))) {
                    realPrefs++;
                }
            }
        }
        out.printf("**%d test files** open the application's real"
                + " preference node. Zero is the standing state, and"
                + " the gate pins it there.%n", realPrefs);
        out.println();

        // ---- display dependence ------------------------------------
        out.println("## Display-dependent tests, their premises and"
                + " their routes");
        out.println();
        List<TestEvidenceScan.File> display = files.stream()
                .filter(TestEvidenceScan.File::displayDependent)
                .toList();
        out.println("| file | premises stated | routes used |");
        out.println("|---|---|---|");
        for (TestEvidenceScan.File f : display) {
            out.printf("| %s | %s | %s |%n", f.path(),
                    f.premises().isEmpty() ? "none"
                            : String.join(", ", f.premises()),
                    f.routes().isEmpty() ? "none"
                            : String.join(", ", f.routes()));
        }
        out.println();
        out.printf("**%d display-dependent files.** %d state a"
                        + " focused-window or focus-owner premise, %d"
                        + " state a reachability premise, and %d use a"
                        + " back-door action (doClick or"
                        + " postActionEvent) somewhere - each either a"
                        + " menu convention or a debt the discipline"
                        + " issue #243 owns.%n",
                display.size(),
                display.stream().filter(f ->
                        f.premises().contains("focused-window")
                                || f.premises().contains("focus-owner"))
                        .count(),
                display.stream().filter(f ->
                        f.premises().contains("point-reachable"))
                        .count(),
                display.stream().filter(f ->
                        f.routes().contains("back-door-click")
                                || f.routes().contains(
                                        "back-door-commit")).count());
        out.println();

        // ---- routes across the whole suite --------------------------
        out.println("## Input routes across the whole suite");
        out.println();
        out.printf("- files dispatching real pointer events: %d%n",
                files.stream().filter(f ->
                        f.routes().contains("pointer-events")).count());
        out.printf("- files dispatching real keyboard events: %d%n",
                files.stream().filter(f ->
                        f.routes().contains("keyboard-events")).count());
        out.printf("- files using doClick somewhere: %d%n",
                files.stream().filter(f ->
                        f.routes().contains("back-door-click")).count());
        out.printf("- files using postActionEvent somewhere: %d%n",
                files.stream().filter(f ->
                        f.routes().contains("back-door-commit")).count());
        out.println();

        // ---- platform assumptions ----------------------------------
        out.println("## Platform assumptions written into tests");
        out.println();
        List<TestEvidenceScan.File> assuming = files.stream()
                .filter(f -> !f.platformAssumptions().isEmpty())
                .toList();
        for (TestEvidenceScan.File f : assuming) {
            out.printf("- %s: %s%n", f.path(),
                    String.join(", ", f.platformAssumptions()));
        }
        out.printf("%n**%d files** name a look and feel, a shortcut"
                + " mask or an operating system.%n", assuming.size());
        out.println();

        // ---- event-thread traffic ----------------------------------
        out.println("## Event-thread traffic, counted not judged");
        out.println();
        out.println("Whether a particular read happens on the event"
                + " thread is control flow, which text cannot decide;"
                + " issue #220 proved the cost of guessing, three"
                + " times. What can be counted is the traffic:");
        out.println();
        int reads = files.stream()
                .mapToInt(TestEvidenceScan.File::liveReads).sum();
        int handOffs = files.stream()
                .mapToInt(TestEvidenceScan.File::edtHandOffs).sum();
        out.printf("- reads of live chart state (currentScene,"
                + " pageOffsetY, navigation.state): **%d** across"
                + " the suite%n", reads);
        out.printf("- explicit event-thread hand-offs (invokeAndWait):"
                + " **%d**%n", handOffs);
        out.println();

        // ---- generated evidence ------------------------------------
        out.println("## Generated evidence, classified");
        out.println();
        List<String> reports = new ArrayList<>();
        List<String> images = new ArrayList<>();
        List<String> photographs = new ArrayList<>();
        try (Stream<Path> tree = Files.walk(Path.of("docs/studies"))) {
            for (Path artifact : tree.filter(Files::isRegularFile)
                    .sorted().toList()) {
                String name = artifact.getFileName().toString();
                String path = artifact.toString()
                        .replace(java.io.File.separatorChar, '/');
                if (name.endsWith(".md")) {
                    reports.add(path);
                } else if (name.startsWith("dialog-real")) {
                    photographs.add(path);
                } else if (name.endsWith(".png")
                        || name.endsWith(".txt")
                        || name.endsWith(".c")) {
                    images.add(path);
                }
            }
        }
        out.printf("- **deterministic reports** (must regenerate"
                + " byte-for-byte on the same tree): %d files%n",
                reports.size());
        for (String path : reports) {
            out.println("  - " + path);
        }
        out.printf("- **platform-rendered inspection artifacts**"
                + " (regenerated on the maintainer's machine,"
                + " reviewed by eye; identical bytes are not the"
                + " contract): %d files%n", images.size());
        out.printf("- **session-dependent photographs** (drift a few"
                + " hundred bytes between desktop sessions; the"
                + " packed geometry, not the bytes, is the claim):"
                + " %d files%n", photographs.size());
        for (String path : photographs) {
            out.println("  - " + path);
        }
        out.println();
        out.println("The reference images under docs/reference are"
                + " **canonical**: CI compares rendered bytes against"
                + " them, and changing one is a reviewed decision.");
    }

    private static long count(List<TestEvidenceScan.File> files,
                              String stateClass) {
        return files.stream()
                .filter(f -> f.stateClass().equals(stateClass)).count();
    }
}
