package juranometria.tool;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.prefs.Preferences;

import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

import juranometria.app.Atlas;
import juranometria.app.AtlasChrome;
import juranometria.chart.SelectionMode;
import juranometria.chart.SkyPosition;
import juranometria.ui.AtlasToolbar;
import juranometria.ui.ChartViewController;
import juranometria.ui.InspectorToggle;
import juranometria.ui.SceneAssembler;
import juranometria.ui.language.SkyLanguageSession;
import juranometria.ui.language.SkyLanguageStore;

/**
 * The toolbar and its search field, as the application composes them
 * (Sprint 33, issue #350).
 *
 * <p><strong>Through {@link AtlasChrome}, from a stored choice.</strong>
 * That is the whole point of this sheet rather than a convenience. The
 * toolbar was once externalised, translated and proved by eight
 * passing contracts while the application still showed it in English,
 * because the defect was in the composition and every picture had been
 * taken of components built with a language handed straight to them. A
 * sheet that asked for Norwegian directly would photograph the same
 * blind spot. So this begins where startup begins - a language written
 * to a preference node and read once - and never constructs either
 * control itself.
 *
 * <p>It installs its own look and feel before any component exists
 * (#362): a photographer that inherits whatever a peer left behind is
 * photographing the peer.
 *
 * <p>Two of the four states are <strong>synthetic</strong> and are
 * labelled as such in the companion. The shipped catalogue is all-sky
 * and cannot produce {@code NO_FIT}, so that state is reached with a
 * regional catalogue - a real one, built with a coverage cone, not a
 * fabricated picture of data that does not exist.
 */
public final class ToolbarSheetMain {

    private ToolbarSheetMain() {
    }

    /**
     * Where the sheets go: the committed directory by default, or a
     * directory a caller names as {@code args[0]}.
     *
     * <p>`InterfaceEvidenceGateTest` runs every one of these into a
     * scratch directory and compares the result with what is
     * committed. It can only do that if a generator can be told
     * where to write; one that always writes over the evidence
     * cannot be used to check it.
     */
    private static Path out =
            Path.of("docs/studies/interface-language");

    /** One arrangement of the bar, and how it was reached. */
    private record State(String name, String title, String query,
                         boolean regional, boolean synthetic,
                         String note) {
    }

    private static final List<State> STATES = List.of(
            new State("idle", "The bar at rest", null, false, false,
                    "The shipped catalogue, nothing typed."),
            new State("results", "A query with several answers", "NGC",
                    false, false,
                    "The shipped catalogue. Every row is a catalogue"
                            + " identity pair and is not translated."),
            new State("nomatch", "A query that finds nothing", "qqzzx",
                    false, false,
                    "The shipped catalogue. The item is disabled"
                            + " because there really is nothing to"
                            + " choose."),
            new State("nofit", "A result outside the catalogue's coverage",
                    "M 31", true, true,
                    "**Synthetic.** The shipped catalogue is all-sky and"
                            + " cannot produce this: NO_FIT is returned"
                            + " only when no field width fits a result's"
                            + " position. Reached with a real regional"
                            + " catalogue - a ten-degree cone around"
                            + " Orion - searching for M 31 in"
                            + " Andromeda."));

    public static void main(String[] args) throws Exception {
        if (args.length > 0 && !args[0].isBlank()) {
            out = Path.of(args[0]);
        }
        Files.createDirectories(out);
        StringBuilder said = new StringBuilder();
        said.append("""
                # Every word the toolbar and its search field say

                Issue #350. Generated by
                `juranometria.tool.ToolbarSheetMain` from compiled
                application classes and their classpath resources.
                Packaged acceptance separately verifies that the
                interface language resources ship in the application
                image.

                %s

                ## Composed, not requested

                Each capture is built through `AtlasChrome`, the
                application's own composition seam, starting from a
                language written to a preference node and read once by
                `SkyLanguageSession`. Neither control is constructed
                here.

                That is deliberate. A sheet that asked each component
                for Norwegian would have photographed a correct
                toolbar during the whole period when the application
                was handing it English - which is exactly what
                happened, and what `AtlasChromeCompositionTest` now
                holds.

                ## What is translated here, and what is not

                Keystrokes are the platform's and appear as this
                desktop spells them. Catalogue designations, the search
                examples, every result's `label · identity`, magnitudes,
                the degree sign and the version value are canonical and
                are handed to sentences as arguments. `V`, `·` and the
                numbers are notation.

                """.formatted(juranometria.tool.InterfaceLanguageStatus
                        .statement("nb-NO")));

        int sheet = 1;
        for (String language : List.of("en", "nb-NO")) {
            said.append("## ").append(language.equals("en") ? "English"
                    : "Norsk bokmål").append(" (`").append(language)
                    .append("`)\n\n");
            for (State state : STATES) {
                said.append("### ").append(state.title());
                if (state.synthetic()) {
                    said.append(" — synthetic");
                }
                said.append("\n\n").append(state.note()).append("\n\n")
                        .append(draw(language, state,
                                out.resolve("toolbar-" + language + "-"
                                        + (sheet++) + "-" + state.name()
                                        + ".png")))
                        .append('\n');
            }
        }
        Files.writeString(out.resolve("toolbar-strings.md"),
                said.toString(), StandardCharsets.UTF_8);
        System.out.println("toolbar sheets: 8 images and "
                + out.resolve("toolbar-strings.md"));
    }

    /** Draws one state in one language and returns its strings. */
    private static String draw(String language, State state, Path to)
            throws Exception {
        Preferences node = Preferences.userRoot()
                .node("juranometria-study-toolbar-" + System.nanoTime());
        JFrame[] owner = new JFrame[1];
        AtlasChrome[] controls = new AtlasChrome[1];
        try {
            SwingUtilities.invokeAndWait(() -> {
                // Before any component exists, and stated rather than
                // inherited from whatever ran first (#362).
                juranometria.app.UiTheme.apply(false);

                SkyLanguageStore store = SkyLanguageStore.forNode(node);
                store.save(store.choice(Atlas.languages())
                        .withInterface(language));
                SkyLanguageSession session = SkyLanguageSession.begin(
                        store, Atlas.languages());

                SceneAssembler assembler = state.regional()
                        ? new SceneAssembler(
                                juranometria.catalog.TiledCatalogue.load(),
                                new SkyPosition(83.8, -5.4), 10.0, 0.5)
                        : Atlas.assembler();
                ChartViewController controller =
                        new ChartViewController(assembler::fits);
                InspectorToggle toggle = new InspectorToggle();
                toggle.bind(() -> { }, () -> true);

                controls[0] = AtlasChrome.of(session, controller,
                        Atlas.search(), assembler, toggle, "2.0.0",
                        () -> { }, new SelectionMode());

                owner[0] = new JFrame("study");
                SheetCapture.prepareShownWindow(owner[0]);
                owner[0].setContentPane(controls[0].toolbar());
                owner[0].pack();
                owner[0].setVisible(true);
            });
            SwingUtilities.invokeAndWait(() -> { });
            if (state.query() != null) {
                // Typed and entered, which is the route a reader
                // takes. The field's own action listener does the
                // rest; nothing here reaches past the public surface
                // to call the handler directly.
                SwingUtilities.invokeAndWait(() -> {
                    controls[0].searchField().setText(state.query());
                    controls[0].searchField().postActionEvent();
                });
                SwingUtilities.invokeAndWait(() -> { });
            }
            return capture(owner[0], controls[0].toolbar(), to);
        } finally {
            SwingUtilities.invokeAndWait(() -> {
                if (owner[0] != null) {
                    owner[0].dispose();
                }
            });
            node.removeNode();
        }
    }

    /**
     * The bar, and the list beneath it if one is open.
     *
     * <p>The result list is a window of its own rather than a child of
     * the field, so painting the bar alone photographs a surface with
     * its answer missing.
     */
    private static String capture(JFrame owner, AtlasToolbar bar, Path to)
            throws Exception {
        // The shared rule first: queue drained, window packed to a
        // fixed point, layout settled, focus owned by nobody. This
        // sheet composes two windows into one image and so paints
        // itself, but it may not decide for itself WHEN.
        SheetCapture.settle(owner, bar);
        Set<String> said = new LinkedHashSet<>();
        BufferedImage[] image = new BufferedImage[1];
        SwingUtilities.invokeAndWait(() -> {
            SheetCapture.neutralFocusNow();
            Component popup = openListOf(owner);
            int width = Math.max(bar.getWidth(),
                    popup == null ? 0 : popup.getWidth());
            int height = bar.getHeight()
                    + (popup == null ? 0 : popup.getHeight() + 4);
            BufferedImage drawn = new BufferedImage(Math.max(1, width),
                    Math.max(1, height), BufferedImage.TYPE_INT_RGB);
            Graphics2D g = drawn.createGraphics();
            try {
                g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                        RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, drawn.getWidth(), drawn.getHeight());
                bar.paint(g);
                if (popup != null) {
                    g.translate(0, bar.getHeight() + 4);
                    popup.paint(g);
                }
            } finally {
                g.dispose();
            }
            image[0] = drawn;
            collect(bar, said);
            if (popup instanceof Container list) {
                collect(list, said);
            }
        });
        ImageIO.write(image[0], "png", to.toFile());

        StringBuilder report = new StringBuilder();
        report.append("![](").append(to.getFileName()).append(")\n\n")
                .append("| shown, hovered or spoken |\n|---|\n");
        for (String one : said) {
            report.append("| ").append(one.replace("|", "\\|"))
                    .append(" |\n");
        }
        return report.toString();
    }

    /** The open result list, if the field has one showing. */
    private static Component openListOf(JFrame owner) {
        for (Window window : Window.getWindows()) {
            if (!window.isShowing() || window == owner) {
                continue;
            }
            for (Component child : window.getComponents()) {
                Component found = popupIn(child);
                if (found != null) {
                    return found;
                }
            }
        }
        return null;
    }

    private static Component popupIn(Component from) {
        if (from instanceof javax.swing.JPopupMenu menu) {
            return menu;
        }
        if (from instanceof Container container) {
            for (Component child : container.getComponents()) {
                Component found = popupIn(child);
                if (found != null) {
                    return found;
                }
            }
        }
        return null;
    }

    private static void collect(Container from, Set<String> said) {
        if (from instanceof JComponent self) {
            record(self, said);
        }
        for (Component child : from.getComponents()) {
            if (child instanceof JComponent widget) {
                record(widget, said);
            }
            if (child instanceof Container nested) {
                collect(nested, said);
            }
        }
    }

    private static void record(JComponent widget, Set<String> said) {
        if (widget instanceof AbstractButton button) {
            add(said, button.getText());
        }
        if (widget instanceof JLabel label) {
            add(said, label.getText());
        }
        Object placeholder =
                widget.getClientProperty("JTextField.placeholderText");
        if (placeholder != null) {
            add(said, String.valueOf(placeholder));
        }
        add(said, widget.getToolTipText());
        if (widget.getAccessibleContext() != null) {
            add(said, widget.getAccessibleContext().getAccessibleName());
            add(said, widget.getAccessibleContext()
                    .getAccessibleDescription());
        }
    }

    private static void add(Set<String> said, String text) {
        if (text == null || text.isBlank()) {
            return;
        }
        // A wrap is replaced by a space, never deleted: Chart Options
        // published "angitt ikatalogen" by deleting one.
        said.add(text.replaceAll("<[^>]*>", " ")
                .replaceAll("\\s+", " ").trim());
    }
}
