/* Generates reference vectors for JUranometria's ecliptic reference
   geometry.  Uses routines provided by SOFA under licence; this file
   is not SOFA software and is not endorsed by SOFA.  It calls the
   unmodified library to print the J2000 mean obliquity and the
   equatorial (ICRS/J2000) directions of chosen ecliptic longitudes,
   so the atlas's fixed mean-ecliptic-of-J2000 model can be checked
   against an authority. */
#include <stdio.h>
#include "sofa.h"
#include "sofam.h"

int main(void) {
    double djm0, djm, jd2000, rm[3][3], v[3], eq[3], ra, dec, eps;
    iauCal2jd(2000, 1, 1, &djm0, &djm);
    jd2000 = djm0 + djm + 0.5;              /* 2000-01-01T12:00 = J2000.0 */

    eps = iauObl80(djm0, djm + 0.5);        /* IAU 1980 mean obliquity  */
    printf("# JUranometria ecliptic reference vectors\n");
    printf("# IAU SOFA release 2023-10-11, generated by scripts/ecliptic-vectors.c\n");
    printf("# Not SOFA software; not endorsed by, SOFA. The atlas takes\n");
    printf("# no dependency on SOFA at run time or at build time.\n");
    printf("obliquity_j2000_deg %.9f\n", eps * DR2D);

    /* ICRS -> ecliptic (of date) rotation; at J2000 this is the J2000
       ecliptic frame including frame bias. Transpose gives ecliptic
       -> ICRS, so an ecliptic direction becomes an equatorial one. */
    iauEcm06(djm0, djm + 0.5, rm);
    printf("# lambda_deg  beta_deg  ra_j2000_deg  dec_j2000_deg\n");
    for (int i = 0; i < 8; i++) {
        double lambda = i * 45.0;
        iauS2c(lambda * DD2R, 0.0, v);      /* ecliptic unit vector */
        iauTrxp(rm, v, eq);                 /* ecliptic -> ICRS      */
        iauC2s(eq, &ra, &dec);
        printf("ecl %.4f %.4f %.9f %.9f\n", lambda, 0.0,
               iauAnp(ra) * DR2D, dec * DR2D);
    }
    return 0;
}
